"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useTeacherClient } from "../../../lib/teacher-client";
import "./preparation.css";

type TimetableLesson={subject?:string;className?:string;notes?:string};
type WorkRow={id:string;date:string;period:number;className:string;lessonTitle?:string;objectives?:string;strategies?:string;introduction?:string;lessonFlow?:string;activity?:string;assessment?:string;homework?:string;values?:string;preparation?:string;prepared?:boolean};
type Lesson={period:number;className:string;notes:string;work?:WorkRow;fromSaved?:boolean};
type FormState={lessonTitle:string;objectives:string;strategies:string;introduction:string;lessonFlow:string;activity:string;assessment:string;homework:string;values:string};
const emptyForm:FormState={lessonTitle:"",objectives:"",strategies:"",introduction:"",lessonFlow:"",activity:"",assessment:"",homework:"",values:""};
const dayKeys=["sunday","monday","tuesday","wednesday","thursday","friday","saturday"];
const ar=(v:number)=>new Intl.NumberFormat("ar-SA-u-nu-arab").format(v);
function riyadhDate(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;}
function weekdayFor(d:string){return dayKeys[new Date(`${d}T12:00:00+03:00`).getDay()]||"sunday";}
function escapeHtml(v:string){return v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c));}
function signature(f:FormState){return JSON.stringify(f);}
function sameLesson(a:{period:number;className:string},b:{period:number;className:string}){return Number(a.period)===Number(b.period)&&String(a.className).trim()===String(b.className).trim();}
export default function TeacherPreparationPage(){
 const session=useTeacherClient();const subjectId=String(session?.subjectKey||"").split("--")[0];
 const [selectedDate,setSelectedDate]=useState(riyadhDate);const [lessons,setLessons]=useState<Lesson[]>([]);const [selected,setSelected]=useState<Lesson|null>(null);const [form,setForm]=useState<FormState>(emptyForm);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [dirty,setDirty]=useState(false);const lastSaved=useRef(signature(emptyForm));const selectedDay=useMemo(()=>weekdayFor(selectedDate),[selectedDate]);
 function open(l:Lesson){setSelected(l);const r=l.work;const f={lessonTitle:r?.lessonTitle||l.notes||"",objectives:r?.objectives||"",strategies:r?.strategies||"",introduction:r?.introduction||"",lessonFlow:r?.lessonFlow||r?.preparation||"",activity:r?.activity||"",assessment:r?.assessment||"",homework:r?.homework||"",values:r?.values||""};setForm(f);lastSaved.current=signature(f);setDirty(false);}
 const load=useCallback(async()=>{if(!subjectId)return;setLoading(true);setMessage("");setSelected(null);setForm(emptyForm);setDirty(false);try{const tr=await fetch(`/api/teacher/timetable?subjectId=${encodeURIComponent(subjectId)}`,{cache:"no-store",credentials:"same-origin"});const td=await tr.json().catch(()=>({}));if(!tr.ok)throw new Error(td.message||"تعذر تحميل الجدول");const table=td.lessons&&typeof td.lessons==="object"?td.lessons as Record<string,TimetableLesson>:{};const scheduled=Object.entries(table).flatMap(([cell,l])=>{const x=cell.match(/^(sunday|monday|tuesday|wednesday|thursday)-([1-7])$/);if(!x||x[1]!==selectedDay||!l.className)return[];return[{period:Number(x[2]),className:String(l.className),notes:String(l.notes||"")}];}).sort((a,b)=>a.period-b.period);const p=new URLSearchParams({subjectId,date:selectedDate});[...new Set(scheduled.map(x=>x.className))].forEach(n=>p.append("className",n));const wr=await fetch(`/api/teacher/lesson-work?${p}`,{cache:"no-store",credentials:"same-origin"});const wd=await wr.json().catch(()=>({}));if(!wr.ok)throw new Error(wd.message||"تعذر تحميل التحضير");let rows=Array.isArray(wd.rows)?wd.rows as WorkRow[]:[];
 // إذا تغيّر الجدول، نطلب محفوظات التاريخ كاملة مرة واحدة حتى لا تختفي التحضيرات السابقة.
 if(scheduled.length&&rows.length===0){const all=await fetch(`/api/teacher/lesson-work?subjectId=${encodeURIComponent(subjectId)}&date=${encodeURIComponent(selectedDate)}`,{cache:"no-store",credentials:"same-origin"});const ad=await all.json().catch(()=>({}));if(all.ok&&Array.isArray(ad.rows))rows=ad.rows as WorkRow[];}
 const current:Lesson[]=scheduled.map(x=>({...x,work:rows.find(r=>sameLesson(r,x))}));const saved:Lesson[]=rows.filter(r=>!current.some(x=>sameLesson(x,r))).map(r=>({period:Number(r.period),className:String(r.className),notes:String(r.lessonTitle||"تحضير محفوظ"),work:r,fromSaved:true}));const next=[...current,...saved].sort((a,b)=>a.period-b.period||a.className.localeCompare(b.className,"ar"));setLessons(next);if(next.length)open(next[0]);if(saved.length)setMessage("تم إظهار التحضيرات السابقة المحفوظة حتى لو تغيّر الجدول الحالي.");}catch(e){setLessons([]);setMessage(e instanceof Error?e.message:"تعذر تحميل التحضير");}finally{setLoading(false);}},[subjectId,selectedDate,selectedDay]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{const tick=()=>{const today=riyadhDate();setSelectedDate(current=>current===today?current:today);};const id=window.setInterval(tick,60000);return()=>window.clearInterval(id);},[]);
 function update<K extends keyof FormState>(k:K,v:FormState[K]){setForm(c=>({...c,[k]:v}));setDirty(true);}
 const save=useCallback(async(auto=false)=>{if(!selected||!subjectId||!form.lessonTitle.trim()||signature(form)===lastSaved.current)return;setSaving(true);if(!auto)setMessage("");try{const r=await fetch("/api/teacher/lesson-work",{method:"PATCH",headers:{"Content-Type":"application/json"},credentials:"same-origin",body:JSON.stringify({subjectId,date:selectedDate,period:selected.period,className:selected.className,...form})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"تعذر حفظ التحضير");const row=d.row as WorkRow;lastSaved.current=signature(form);setDirty(false);setLessons(c=>c.map(x=>x.period===selected.period&&x.className===selected.className?{...x,work:row}:x));setSelected(c=>c?{...c,work:row}:c);setMessage(auto?"تم الحفظ تلقائيًا.":`تم حفظ تحضير ${selectedDate}.`);}catch(e){setMessage(e instanceof Error?e.message:"تعذر حفظ التحضير");}finally{setSaving(false);}},[selected,subjectId,form,selectedDate]);
 useEffect(()=>{if(!dirty||saving||!form.lessonTitle.trim())return;const id=window.setTimeout(()=>void save(true),1400);return()=>window.clearTimeout(id);},[dirty,saving,form,save]);
 function printPreparation(){if(!selected)return;const popup=window.open("","_blank","width=980,height=900");if(!popup)return setMessage("اسمح بالنوافذ المنبثقة للطباعة.");const fields=[["الأهداف",form.objectives],["الاستراتيجيات",form.strategies],["التمهيد",form.introduction],["سير الدرس",form.lessonFlow],["النشاط",form.activity],["التقويم",form.assessment],["الواجب",form.homework],["القيم",form.values]].filter(([,v])=>String(v).trim());popup.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>تحضير ${escapeHtml(form.lessonTitle)}</title><style>@page{size:A4;margin:12mm}body{font-family:Tahoma,Arial;color:#173b45}.meta,.fields{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.meta div,.field{border:1px solid #d9e5e3;border-radius:10px;padding:9px}.wide{grid-column:1/-1}</style></head><body><h1>تحضير درس</h1><section class="meta"><div>الدرس: <b>${escapeHtml(form.lessonTitle)}</b></div><div>الفصل: <b>${escapeHtml(selected.className)}</b></div><div>الحصة: <b>${ar(selected.period)}</b></div><div>التاريخ: <b>${selectedDate}</b></div></section><section class="fields">${fields.map(([l,v])=>`<article class="field ${l==="سير الدرس"?"wide":""}"><b>${l}</b><p>${escapeHtml(String(v))}</p></article>`).join("")}</section></body></html>`);popup.document.close();}
 return <main className="prep-page" dir="rtl"><section className="prep-head"><div><small>التحضير اليومي</small><h1>تحضير المعلم</h1><p>حصص اليوم من جدولك، مع إبقاء التحضيرات السابقة المحفوظة ظاهرة.</p></div><div className="prep-date"><label><span>تاريخ التحضير</span><input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value||riyadhDate())}/></label><button type="button" onClick={()=>setSelectedDate(riyadhDate())}>اليوم</button><Link href="/teacher/timetable">الجدول</Link></div></section>{message?<p className="prep-message">{message}</p>:null}<section className="prep-layout"><aside className="prep-lessons"><header><small>{selectedDate}</small><b>{loading?"…":`${ar(lessons.length)} حصة`}</b></header>{lessons.length?lessons.map(l=><button type="button" key={`${l.period}-${l.className}`} className={selected?.period===l.period&&selected.className===l.className?"active":""} onClick={()=>open(l)}><span>{ar(l.period)}</span><div><b>{l.className}</b><small>{l.fromSaved?"تحضير سابق محفوظ":l.notes||session?.subject||"المادة"}</small></div><i>{l.work?.prepared?"محفوظ":"تحضير"}</i></button>):<div className="prep-empty"><b>{loading?"جارٍ التحميل…":"لا توجد حصص أو تحضيرات في هذا التاريخ"}</b><span>تظهر حصص الجدول وأي تحضير سابق محفوظ.</span></div>}</aside><section className="prep-form">{selected?<><header><div><small>{selectedDate} • {selected.className} • الحصة {ar(selected.period)}</small><h2>{form.lessonTitle||"تحضير الحصة"}</h2></div><span>{saving?"يتم الحفظ…":dirty?"تعديل غير محفوظ":selected.work?.prepared?"محفوظ":"غير مكتمل"}</span></header><div className="prep-fields">{([["lessonTitle","عنوان الدرس","input"],["objectives","الأهداف"],["strategies","الاستراتيجيات"],["introduction","التمهيد"],["activity","النشاط"],["lessonFlow","سير الدرس"],["assessment","التقويم"],["homework","الواجب"],["values","القيم والمهارات"]] as const).map(([k,l,t])=><label key={k} className={k==="lessonTitle"||k==="lessonFlow"||k==="values"?"wide":""}><span>{l}</span>{t==="input"?<input value={form[k]} onChange={e=>update(k,e.target.value)}/>:<textarea value={form[k]} onChange={e=>update(k,e.target.value)}/>}</label>)}</div><footer><button className="save" type="button" onClick={()=>void save(false)} disabled={saving}>{saving?"جارٍ الحفظ…":"حفظ الآن"}</button><button type="button" onClick={printPreparation}>طباعة A4</button></footer></>:<div className="prep-form-empty"><b>اختر حصة</b><span>التحضير مرتبط بجدول المعلم ومحفوظاته السابقة.</span></div>}</section></section></main>;
}
