import { unstable_cache } from "next/cache";
import { NextResponse } from "next/server";
import { getSubjectConfig, isSubjectKey } from "../../../../lib/subject-config";
import { normalizeAssignments } from "../../../../lib/teacher-assignments";
import { normalizeClass } from "../../../../lib/unified-roster";
import { TEACHER_CLASS_SCOPES_COLLECTION, normalizeClassIds, teacherClassScopeId } from "../../../../lib/teacher-class-scope";
import { adminDb } from "../../../../lib/server/firebase-admin";
import { requireSession } from "../../../../lib/server/portal-auth";

type Lesson = { subject: string; className: string; notes: string };
type Schedule = Record<string, Lesson>;
type TimetableCacheEntry = { lessons: Schedule; expiresAt: number };
const FIRESTORE_TIMEOUT_MS=12000, TIMETABLE_CACHE_TTL_MS=60*60*1000;
const VALID_CELL=/^(sunday|monday|tuesday|wednesday|thursday)-[1-7]$/;
const timetableCache=new Map<string,TimetableCacheEntry>(), timetableInflight=new Map<string,Promise<Schedule>>(), timetableWriteInflight=new Map<string,Promise<Schedule>>();
async function withTimeout<T>(promise:Promise<T>,milliseconds=FIRESTORE_TIMEOUT_MS){let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([promise,new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error("timetable_timeout")),milliseconds);})]);}finally{if(timer)clearTimeout(timer);}}
function cleanSchedule(value:unknown,subjectLabel:string){if(!value||typeof value!=="object")return{} as Schedule;const cleaned:Schedule={};Object.entries(value as Record<string,unknown>).forEach(([key,raw])=>{if(!VALID_CELL.test(key)||!raw||typeof raw!=="object")return;const lesson=raw as Partial<Lesson>,className=normalizeClass(lesson.className);if(!className)return;cleaned[key]={subject:subjectLabel,className,notes:String(lesson.notes||"").trim().slice(0,500)};});return cleaned;}
function schedulesEqual(a:Schedule,b:Schedule){const ak=Object.keys(a).sort(),bk=Object.keys(b).sort();return ak.length===bk.length&&ak.every((key,index)=>key===bk[index]&&a[key]?.subject===b[key]?.subject&&a[key]?.className===b[key]?.className&&a[key]?.notes===b[key]?.notes);}
function timetableReference(teacherId:string,subjectId:string){return adminDb().collection(`portalV2Data/${teacherId}/subjects/${subjectId}/timetable`).doc("weekly");}
async function teacherContext(subjectId:string,requestedGrade?:number){const session=await requireSession("teacher");if(!session||!session.user)return{error:NextResponse.json({ok:false,message:"انتهت جلسة المعلم، سجل الدخول مرة أخرى."},{status:401})};if(!isSubjectKey(subjectId))return{error:NextResponse.json({ok:false,message:"المادة غير صحيحة."},{status:400})};const assignments=normalizeAssignments(session.user.assignments,session.user.subjectIds).filter(item=>item.subjectId===subjectId);if(!assignments.length)return{error:NextResponse.json({ok:false,message:"هذه المادة غير مسندة إلى حسابك."},{status:403})};const grades=[...new Set(assignments.map(item=>Number(String(item.grade||"").match(/[123]/)?.[0]||0)).filter(Boolean))];const grade=requestedGrade&&grades.includes(requestedGrade)?requestedGrade:(grades.length===1?grades[0]:0);if(!grade)return{error:NextResponse.json({ok:false,message:"حدد المرحلة المرتبطة بالجدول."},{status:400})};const scopeSnapshot=await adminDb().collection(TEACHER_CLASS_SCOPES_COLLECTION).doc(teacherClassScopeId(session.userId,subjectId,grade)).get();const allowedClasses=new Set(normalizeClassIds(scopeSnapshot.data()?.selectedClassIds).map(normalizeClass).filter(Boolean));return{session,grade,allowedClasses,subjectLabel:getSubjectConfig(subjectId).label,reference:timetableReference(session.userId,subjectId)};}
function errorResponse(error:unknown,action:"تحميل"|"حفظ"){const message=error instanceof Error?error.message:"";if(message==="timetable_timeout")return NextResponse.json({ok:false,message:`انتهت مهلة ${action} الجدول. تم الاحتفاظ بالتعديل على الجهاز.`},{status:504});const code=error&&typeof error==="object"&&"code" in error?String((error as {code?:unknown}).code||""):"";if(code==="resource-exhausted"||message.includes("RESOURCE_EXHAUSTED")||message.toLowerCase().includes("quota exceeded"))return NextResponse.json({ok:false,message:"خدمة الحفظ السحابي مزدحمة مؤقتًا. تم الاحتفاظ بالتعديل على الجهاز."},{status:429});console.error(`timetable_${action==="حفظ"?"save":"load"}_failed`,error);return NextResponse.json({ok:false,message:`تعذر ${action} الجدول الآن. لم يتم فقد أي حصة سابقة.`},{status:500});}
function persistentTimetableReader(teacherId:string,subjectId:string,subjectLabel:string){return unstable_cache(async():Promise<Schedule>=>{const snapshot=await withTimeout(timetableReference(teacherId,subjectId).get());const data=snapshot.exists?snapshot.data() as {lessons?:unknown}:undefined;return cleanSchedule(data?.lessons,subjectLabel);},["teacher-timetable-shared-v4",teacherId,subjectId],{revalidate:3600});}
async function loadTimetableCached(teacherId:string,subjectId:string,subjectLabel:string){const key=`${teacherId}:${subjectId}`,cached=timetableCache.get(key);if(cached&&cached.expiresAt>Date.now())return cached.lessons;const existing=timetableInflight.get(key);if(existing)return existing;const pending=(async()=>{const lessons=await persistentTimetableReader(teacherId,subjectId,subjectLabel)();timetableCache.set(key,{lessons,expiresAt:Date.now()+TIMETABLE_CACHE_TTL_MS});return lessons;})();timetableInflight.set(key,pending);try{return await pending;}finally{timetableInflight.delete(key);}}
export async function GET(request:Request){const url=new URL(request.url),subjectId=String(url.searchParams.get("subjectId")||"").split("--")[0],grade=Number(url.searchParams.get("grade")||0),context=await teacherContext(subjectId,grade);if("error" in context)return context.error;try{const all=await loadTimetableCached(context.session.userId,subjectId,context.subjectLabel),lessons=Object.fromEntries(Object.entries(all).filter(([,lesson])=>context.allowedClasses.has(normalizeClass(lesson.className)))) as Schedule;return NextResponse.json({ok:true,lessons},{headers:{"Cache-Control":"private, max-age=300, stale-while-revalidate=3300"}});}catch(error){return errorResponse(error,"تحميل");}}
export async function PATCH(request:Request){const body=await request.json().catch(()=>({})) as {subjectId?:unknown;grade?:unknown;lessons?:unknown},subjectId=String(body.subjectId||"").split("--")[0],context=await teacherContext(subjectId,Number(body.grade||0));if("error" in context)return context.error;if(!context.allowedClasses.size)return NextResponse.json({ok:false,message:"لا توجد فصول محددة لك من الإدارة لهذه المرحلة."},{status:403});const submitted=cleanSchedule(body.lessons,context.subjectLabel);if(Object.values(submitted).some(lesson=>!context.allowedClasses.has(normalizeClass(lesson.className))))return NextResponse.json({ok:false,message:"إحدى الحصص مرتبطة بفصل غير مسند إلى حسابك."},{status:403});const cacheKey=`${context.session.userId}:${subjectId}`,writeKey=`${cacheKey}:${context.grade}`;try{const prior=timetableWriteInflight.get(writeKey);if(prior)return NextResponse.json({ok:true,lessons:await prior,deduplicated:true},{headers:{"Cache-Control":"no-store, max-age=0"}});const pending=(async()=>{const cached=timetableCache.get(cacheKey);let existing:Schedule;if(cached&&cached.expiresAt>Date.now())existing=cached.lessons;else{const snapshot=await withTimeout(context.reference.get()),data=snapshot.exists?snapshot.data() as {lessons?:unknown}:undefined;existing=cleanSchedule(data?.lessons,context.subjectLabel);}const retained=Object.fromEntries(Object.entries(existing).filter(([,lesson])=>!context.allowedClasses.has(normalizeClass(lesson.className)))) as Schedule,lessons={...retained,...submitted};if(!schedulesEqual(existing,lessons)){const now=new Date().toISOString();await withTimeout(context.reference.set({lessons,teacherId:context.session.userId,teacherName:context.session.name||"",subjectKey:subjectId,updatedAt:now,savedThroughApiAt:now},{merge:true}));}timetableCache.set(cacheKey,{lessons,expiresAt:Date.now()+TIMETABLE_CACHE_TTL_MS});return lessons;})();timetableWriteInflight.set(writeKey,pending);try{return NextResponse.json({ok:true,lessons:await pending},{headers:{"Cache-Control":"no-store, max-age=0"}});}finally{timetableWriteInflight.delete(writeKey);}}catch(error){return errorResponse(error,"حفظ");}}
