"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { SUBJECT_CONFIG } from "../../../lib/subject-config";
import "../admin-rebuild.css";

type Assignment = { id?: string; subjectId: string; subjectLabel?: string; grade: string; section: string; label?: string };
type Teacher = { id: string; name: string; active: boolean; subjectIds: string[]; assignments: Assignment[] };

const SUBJECTS = Object.values(SUBJECT_CONFIG).map(item => [item.key, item.label] as const).sort((a,b)=>a[1].localeCompare(b[1],"ar"));
const GRADES = ["الأول الثانوي","الثاني الثانوي","الثالث الثانوي"] as const;
const SECTIONS = ["الكل","١","٢","٣","٤","٥","٦","٧"] as const;
const emptyAssignment = (): Assignment => ({ subjectId:"", grade:"", section:"" });
const MANUAL_SUBJECT_OPTION = "__manual_subject__";
const ar = (value:number) => new Intl.NumberFormat("ar-SA-u-nu-arab").format(value||0);

const SUBJECT_TRANSLATIONS: Record<string,string> = {"اللغة الصينية":"chinese","الصينية":"chinese","اللغة الفرنسية":"french","الفرنسية":"french","اللغة الالمانية":"german","اللغة الألمانية":"german","الألمانية":"german","البرمجة":"programming","الروبوت":"robotics","الروبوتات":"robotics","الذكاء الاصطناعي":"artificial-intelligence","الأمن السيبراني":"cybersecurity","الاقتصاد":"economics","القانون":"law","التسويق":"marketing","المحاسبة":"accounting","علم النفس":"psychology","الفلسفة":"philosophy","المهارات الرقمية":"digital-skills"};
function normalizeArabicText(value:string){return value.trim().replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/\s+/g," ");}
function transliterateArabic(value:string){const map:Record<string,string>={ا:"a",ب:"b",ت:"t",ث:"th",ج:"j",ح:"h",خ:"kh",د:"d",ذ:"dh",ر:"r",ز:"z",س:"s",ش:"sh",ص:"s",ض:"d",ط:"t",ظ:"z",ع:"a",غ:"gh",ف:"f",ق:"q",ك:"k",ل:"l",م:"m",ن:"n",ه:"h",و:"w",ي:"y",ء:"",ئ:"y",ؤ:"w"};return normalizeArabicText(value).split("").map(char=>map[char]??(/[a-z0-9]/i.test(char)?char.toLowerCase():char===" "?"-":"")).join("").replace(/-+/g,"-").replace(/^-|-$/g,"");}
function customSubjectIdentity(label:string){const normalized=normalizeArabicText(label);const translated=Object.entries(SUBJECT_TRANSLATIONS).find(([name])=>normalizeArabicText(name)===normalized)?.[1];const slug=translated||transliterateArabic(label)||"subject";return `custom-${slug}~${encodeURIComponent(label.trim())}`;}
function customSubjectLabel(subjectId:string){const marker=subjectId.indexOf("~");if(!subjectId.startsWith("custom-")||marker<0)return "";try{return decodeURIComponent(subjectId.slice(marker+1));}catch{return "";}}

function AssignmentEditor({rows,setRows}:{rows:Assignment[];setRows:(rows:Assignment[])=>void}){
  const update=(index:number,key:keyof Assignment,value:string)=>setRows(rows.map((row,i)=>i===index?{...row,[key]:value}:row));
  const changeSubject=(index:number,value:string)=>{if(value!==MANUAL_SUBJECT_OPTION){const known=SUBJECTS.find(([id])=>id===value)?.[1]||customSubjectLabel(value);setRows(rows.map((row,i)=>i===index?{...row,subjectId:value,subjectLabel:known||undefined}:row));return;}const label=window.prompt("اكتب اسم المادة كما تريد أن يظهر:","")?.trim();if(!label)return;setRows(rows.map((row,i)=>i===index?{...row,subjectId:customSubjectIdentity(label),subjectLabel:label}:row));};
  return <div className="admin2-assignment-box"><div className="admin2-assignment-title"><span>المواد والحصص المسندة</span><small>اربط المعلم بالمادة والصف والفصل، ويمكن إضافة أكثر من تكليف.</small></div>{rows.map((row,index)=><div className="admin2-assignment-row" key={index}><label>المادة<select required value={row.subjectId} onChange={e=>changeSubject(index,e.target.value)}><option value="">اختر المادة</option>{SUBJECTS.map(([id,label])=><option key={id} value={id}>{label}</option>)}<option value={MANUAL_SUBJECT_OPTION}>＋ إضافة مادة يدويًا…</option></select></label><label>الصف<select required value={row.grade} onChange={e=>update(index,"grade",e.target.value)}><option value="">اختر الصف</option>{GRADES.map(item=><option key={item}>{item}</option>)}</select></label><label>الفصل<select required value={row.section} onChange={e=>update(index,"section",e.target.value)}><option value="">اختر الفصل</option>{SECTIONS.map(item=><option key={item}>{item==="الكل"?"جميع الفصول":item}</option>)}</select></label>{rows.length>1&&<button type="button" className="admin2-btn danger compact" onClick={()=>setRows(rows.filter((_,i)=>i!==index))}>حذف</button>}</div>)}<button type="button" className="admin2-btn soft admin2-add-assignment" onClick={()=>setRows([...rows,emptyAssignment()])}>+ إضافة تكليف آخر</button></div>;
}

export default function AdminTeachersPage(){
  const [teachers,setTeachers]=useState<Teacher[]>([]),[name,setName]=useState(""),[teacherPassword,setTeacherPassword]=useState(""),[assignments,setAssignments]=useState<Assignment[]>([emptyAssignment()]),[editing,setEditing]=useState<Teacher|null>(null),[resetPassword,setResetPassword]=useState(""),[deleting,setDeleting]=useState<Teacher|null>(null),[deleteSubjectData,setDeleteSubjectData]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[showCreate,setShowCreate]=useState(false),[search,setSearch]=useState("");
  const load=useCallback(async()=>{try{const response=await fetch("/api/admin/teachers",{cache:"no-store"});if(response.status===401||response.status===403){window.location.assign("/admin");return;}const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"تعذر التحميل");setTeachers(Array.isArray(data.teachers)?data.teachers:[]);}catch{setMessage("تعذر تحميل بيانات المعلمين الآن.");}},[]);
  useEffect(()=>{void load();},[load]);
  const subjectLabel=(id:string)=>SUBJECTS.find(([key])=>key===id)?.[1]||customSubjectLabel(id)||id;
  const assignmentLabel=(a:Assignment)=>a.label||`${a.subjectLabel||subjectLabel(a.subjectId)} — ${a.grade}${a.section?` — ${a.section==="الكل"?"جميع الفصول":`فصل ${a.section}`}`:""}`;
  const filtered=useMemo(()=>{const q=search.trim().toLocaleLowerCase("ar");return q?teachers.filter(t=>t.name.toLocaleLowerCase("ar").includes(q)||t.assignments?.some(a=>assignmentLabel(a).toLocaleLowerCase("ar").includes(q))):teachers;},[teachers,search]);
  const active=teachers.filter(t=>t.active).length,assignmentsCount=teachers.reduce((n,t)=>n+(t.assignments?.length||0),0),subjectsCount=new Set(teachers.flatMap(t=>t.subjectIds||[])).size;
  async function createTeacher(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const response=await fetch("/api/admin/teachers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,password:teacherPassword,assignments}),cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok){setMessage(data.message||"تعذر إضافة المعلم");return;}setName("");setTeacherPassword("");setAssignments([emptyAssignment()]);setShowCreate(false);setMessage("تمت إضافة المعلم وربط تكليفاته.");await load();}finally{setBusy(false);}}
  async function saveTeacher(){if(!editing)return;setBusy(true);try{const response=await fetch(`/api/admin/teachers/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:editing.name,assignments:editing.assignments,password:resetPassword||undefined}),cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok){setMessage(data.message||"تعذر حفظ التعديل");return;}setEditing(null);setResetPassword("");setMessage("تم حفظ التعديلات.");await load();}finally{setBusy(false);}}
  async function toggle(t:Teacher){setBusy(true);try{await fetch(`/api/admin/teachers/${t.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!t.active}),cache:"no-store"});await load();}finally{setBusy(false);}}
  async function confirmDelete(){if(!deleting)return;setBusy(true);try{const suffix=deleteSubjectData?"?deleteSubjectData=1":"";const response=await fetch(`/api/admin/teachers/${deleting.id}${suffix}`,{method:"DELETE",cache:"no-store"});const data=await response.json().catch(()=>({}));if(!response.ok){setMessage(data.message||"تعذر الحذف");return;}setDeleting(null);setDeleteSubjectData(false);setMessage("تم تنفيذ حذف الحساب حسب الخيار المحدد.");await load();}finally{setBusy(false);}}

  return <section className="admin2 admin-teachers-dedicated" dir="rtl"><header className="admin2-head"><div><small>إدارة المعلمين</small><h1>المعلمون والمواد المسندة</h1><p>إضافة وتعديل وإيقاف الحسابات وربط المواد والصفوف والفصول بدون إطالة.</p></div><button className="admin2-btn soft" onClick={()=>void load()} disabled={busy}>تحديث</button></header><section className="admin2-stats"><article><span>المعلمون</span><strong>{ar(teachers.length)}</strong><small>حساب مسجل</small></article><article><span>المفعّلون</span><strong>{ar(active)}</strong><small>{ar(teachers.length-active)} متوقف</small></article><article><span>المواد</span><strong>{ar(subjectsCount)}</strong><small>مادة مستخدمة</small></article><article><span>التكليفات</span><strong>{ar(assignmentsCount)}</strong><small>مادة / صف / فصل</small></article></section>{message&&<p className="admin2-message">{message}</p>}<section className="admin-teacher-commandbar"><div className="admin-teacher-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث باسم المعلم أو المادة أو الصف…"/><small>{ar(filtered.length)} نتيجة</small></div><button type="button" className="admin2-btn primary" onClick={()=>setShowCreate(true)}>+ إضافة معلم</button></section><section className="admin2-panel admin-teachers-panel"><div className="admin2-list">{filtered.map(teacher=><article className="admin2-teacher" key={teacher.id}><span className="admin2-avatar">{teacher.name.trim().charAt(0)||"م"}</span><div className="admin-teacher-copy"><div className="admin-teacher-name-row"><strong>{teacher.name}</strong><span className={`admin2-state ${teacher.active?"on":"off"}`}>{teacher.active?"مفعل":"متوقف"}</span></div><p>{teacher.assignments?.map(assignmentLabel).join(" • ")||"لا توجد تكليفات"}</p><small>{ar(teacher.assignments?.length||0)} تكليف</small></div><div className="admin2-actions"><button className="admin2-btn soft" onClick={()=>{setEditing({...teacher,assignments:teacher.assignments?.length?teacher.assignments:[emptyAssignment()]});setResetPassword("");}}>تعديل</button><button className="admin2-btn soft" onClick={()=>void toggle(teacher)}>{teacher.active?"إيقاف":"تفعيل"}</button><button className="admin2-btn danger" onClick={()=>setDeleting(teacher)}>حذف</button></div></article>)}{!filtered.length&&<div className="admin2-empty">لا توجد نتائج.</div>}</div></section>
  {showCreate&&<div className="admin2-modal"><section className="admin2-modal-card"><header className="admin2-modal-head"><div><small>حساب جديد</small><h2>إضافة معلم</h2></div><button className="admin2-btn soft" onClick={()=>setShowCreate(false)}>إغلاق</button></header><form className="admin2-form" onSubmit={createTeacher}><div className="admin-create-credentials"><label>اسم المعلم<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>الرقم السري<input type="password" value={teacherPassword} onChange={e=>setTeacherPassword(e.target.value)} minLength={8} required/></label></div><AssignmentEditor rows={assignments} setRows={setAssignments}/><div className="admin2-modal-actions"><button type="button" className="admin2-btn soft" onClick={()=>setShowCreate(false)}>إلغاء</button><button className="admin2-btn primary" disabled={busy}>حفظ وإضافة</button></div></form></section></div>}
  {editing&&<div className="admin2-modal"><section className="admin2-modal-card"><header className="admin2-modal-head"><div><small>تعديل الحساب</small><h2>{editing.name}</h2></div><button className="admin2-btn soft" onClick={()=>setEditing(null)}>إغلاق</button></header><div className="admin2-form"><label>اسم المعلم<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>تغيير الرقم السري<input type="password" minLength={8} value={resetPassword} onChange={e=>setResetPassword(e.target.value)}/></label><AssignmentEditor rows={editing.assignments} setRows={rows=>setEditing({...editing,assignments:rows})}/></div><div className="admin2-modal-actions"><button className="admin2-btn soft" onClick={()=>setEditing(null)}>إلغاء</button><button className="admin2-btn primary" onClick={()=>void saveTeacher()} disabled={busy}>حفظ التعديلات</button></div></section></div>}
  {deleting&&<div className="admin2-modal"><section className="admin2-modal-card"><header className="admin2-modal-head"><div><small>تأكيد الحذف</small><h2>{deleting.name}</h2></div><button className="admin2-btn soft" onClick={()=>setDeleting(null)}>إغلاق</button></header><label className="admin2-delete-choice"><input type="checkbox" checked={deleteSubjectData} onChange={e=>setDeleteSubjectData(e.target.checked)}/><span><strong>حذف بيانات المواد والدرجات التابعة لهذا المعلم</strong><small>اتركه غير محدد لحذف الحساب فقط وحفظ البيانات السابقة.</small></span></label><div className="admin2-modal-actions"><button className="admin2-btn soft" onClick={()=>setDeleting(null)}>إلغاء</button><button className="admin2-btn danger" onClick={()=>void confirmDelete()} disabled={busy}>تأكيد الحذف</button></div></section></div>}
  </section>;
}