"use client";

import { useEffect, useMemo, useState } from "react";
import { doc, setDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import { tenantCollection } from "../../../lib/teacher-tenant";
import { useTeacherClient } from "../../../lib/teacher-client";
import { calculateGradePlanResult, type GradeStudentLike } from "../../../lib/grade-plan";
import { useGradePlan } from "../../../lib/use-grade-plan";
import "./mastery-dashboard.css";

type Student=GradeStudentLike&{id:string;storageId?:string;name?:string;class?:string;className?:string;code?:string;accessCode?:string;studentCode?:string;teacherNote?:string};
type SchoolClass={id:string;name:string;grade?:number;section?:string};
type StatusFilter="all"|"mastered"|"support"|"incomplete";
type MasteryRow=Student&{sectionLabel:string;earned:number;maximum:number;percentage:number|null;recorded:boolean;status:StatusFilter};
const PERCENTAGES=[100,95,90,85,80,75,70,65,60,55,50,45,40,35,30,25,20,15,10,5,0];
function aliases(s:Student){return [...new Set([s.id,s.code,s.accessCode,s.studentCode].map(v=>String(v||"").trim()).filter(Boolean))];}
function fmt(n:number){return Number.isInteger(n)?String(n):n.toFixed(1).replace(/\.0$/,"");}

export default function MasteryDashboard(){
 const session=useTeacherClient(); const {activePlan}=useGradePlan(true);
 const teacherId=session.teacherId||"",teacherName=session.teacherName||"المعلم",subjectKey=session.subjectKey||"history",subject=session.subject||"المادة",activeGrade=session.activeGrade||null;
 const [storedStudents,setStoredStudents]=useState<Student[]>([]),[scopeStudents,setScopeStudents]=useState<Student[]>([]),[scopeClasses,setScopeClasses]=useState<SchoolClass[]>([]);
 const [loading,setLoading]=useState(false),[selectedClass,setSelectedClass]=useState(""),[selectedSection,setSelectedSection]=useState("");
 const [masteryThreshold,setMasteryThreshold]=useState(80),[exactPercentage,setExactPercentage]=useState("all"),[statusFilter,setStatusFilter]=useState<StatusFilter>("all");
 const [selectedIds,setSelectedIds]=useState<string[]>([]),[message,setMessage]=useState(""),[referralOpen,setReferralOpen]=useState(false),[reason,setReason]=useState("انخفاض مستوى الإتقان والتحصيل الدراسي");
 const referralsPath=useMemo(()=>teacherId?tenantCollection(teacherId,subjectKey as never,"counselorReferrals"):"",[teacherId,subjectKey]);
 useEffect(()=>{if(!teacherId||!subjectKey)return setStoredStudents([]);let active=true;const c=new AbortController();fetch(`/api/teacher/grade-data?subjectId=${encodeURIComponent(String(subjectKey).split("--")[0])}`,{credentials:"same-origin",signal:c.signal}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"تعذر تحميل الدرجات.");return d}).then(d=>{if(!active)return;const byCode=d.byCode&&typeof d.byCode==="object"?d.byCode:{};setStoredStudents(Object.entries(byCode).map(([code,row])=>({...(row as object),id:String((row as any).documentId||code),code:String((row as any).code||(row as any).accessCode||(row as any).studentCode||code)})) as Student[])}).catch(e=>{if(active&&e?.name!=="AbortError")setMessage(e instanceof Error?e.message:"تعذر تحميل الدرجات.")});return()=>{active=false;c.abort()}},[teacherId,subjectKey]);
 useEffect(()=>{if(!teacherId||!subjectKey||!activeGrade){setScopeStudents([]);setScopeClasses([]);return}let active=true;const c=new AbortController();setLoading(true);const p=new URLSearchParams({subjectId:subjectKey,grade:String(activeGrade)});fetch(`/api/teacher/students?${p}`,{signal:c.signal}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"تعذر تحميل الطلاب.");return d}).then(d=>{if(active){setScopeStudents(Array.isArray(d.students)?d.students:[]);setScopeClasses(Array.isArray(d.classes)?d.classes:[])}}).catch(e=>{if(active&&e?.name!=="AbortError")setMessage(e instanceof Error?e.message:"تعذر تحميل الطلاب.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false;c.abort()}},[teacherId,subjectKey,activeGrade]);
 useEffect(()=>{if(!activePlan?.sections?.length)return setSelectedSection("");if(!selectedSection||!activePlan.sections.some(s=>s.id===selectedSection))setSelectedSection(activePlan.sections[0].id)},[activePlan,selectedSection]);
 const students=useMemo(()=>{const live=new Map<string,Student>();storedStudents.forEach(s=>aliases(s).forEach(a=>live.set(a,s)));return scopeStudents.map(roster=>{const found=aliases(roster).map(a=>live.get(a)).find(Boolean);const cls=String(roster.className||roster.class||"").trim();return {...roster,...(found||{}),id:roster.id,storageId:found?.id||roster.id,class:cls,className:cls}}).sort((a,b)=>(a.name||"").localeCompare(b.name||"","ar"))},[scopeStudents,storedStudents]);
 const classes=useMemo(()=>scopeClasses.map(c=>{const n=String(c.name||"").trim(),s=String(c.section||"").trim();return !s||n.includes(s)?n:`${n} (${s})`}).filter(Boolean),[scopeClasses]);
 const selectedPlanSection=activePlan?.sections.find(s=>s.id===selectedSection);
 const rows=useMemo<MasteryRow[]>(()=>{if(!activePlan||!selectedSection)return[];return students.filter(s=>!selectedClass||(s.class||"")===selectedClass||selectedClass.startsWith(`${s.class||""} (`)).map(student=>{const result=calculateGradePlanResult(activePlan,student);const section=result.sections.find(s=>s.id===selectedSection);if(!section||section.maximum<=0)return {...student,sectionLabel:selectedPlanSection?.label||"—",earned:0,maximum:0,percentage:null,recorded:false,status:"incomplete"};const recorded=section.recordedMaximum>0;const pct=recorded?Math.max(0,Math.min(100,Math.round(section.percentage*10)/10)):null;return {...student,sectionLabel:section.label,earned:section.earned,maximum:section.maximum,percentage:pct,recorded,status:!recorded?"incomplete":pct!==null&&pct>=masteryThreshold?"mastered":"support"}})},[activePlan,selectedSection,students,selectedClass,masteryThreshold,selectedPlanSection?.label]);
 const shownRows=useMemo(()=>rows.filter(r=>{if(statusFilter!=="all"&&r.status!==statusFilter)return false;if(exactPercentage!=="all"){if(r.percentage===null)return false;return Math.abs(r.percentage-Number(exactPercentage))<0.05}return true}),[rows,statusFilter,exactPercentage]);
 const mastered=rows.filter(r=>r.status==="mastered"),support=rows.filter(r=>r.status==="support"),incomplete=rows.filter(r=>r.status==="incomplete"),scored=rows.filter(r=>r.percentage!==null);
 const average=scored.length?Math.round(scored.reduce((a,r)=>a+(r.percentage||0),0)/scored.length*10)/10:0;
 const selectedSupport=rows.filter(r=>selectedIds.includes(r.id)&&r.status==="support");
 function toggle(id:string,checked:boolean){setSelectedIds(x=>checked?[...new Set([...x,id])]:x.filter(v=>v!==id))}
 function selectAllSupport(){setSelectedIds(support.map(r=>r.id));setStatusFilter("support");setExactPercentage("all")}
 async function sendReferral(){if(!selectedSupport.length)return setMessage("حدد طالبًا غير متقن واحدًا على الأقل.");if(!reason.trim())return setMessage("اكتب سبب الإحالة.");const now=new Date().toISOString();await Promise.all(selectedSupport.map(r=>setDoc(doc(db,referralsPath,crypto.randomUUID()),{studentId:r.id,studentName:r.name||"",className:r.class||"",grade:activeGrade,percentage:r.percentage??0,earned:r.earned,maximum:r.maximum,masterySectionId:selectedSection,masterySectionLabel:r.sectionLabel,masteryThreshold,reason:reason.trim(),referralType:"mastery",referralTypeLabel:"إحالة إتقان وتحصيل",status:"جديدة",teacherId,teacherName,subjectId:subjectKey,subject,explicitTeacherAction:true,createdAt:now})));setMessage(`تمت إحالة ${selectedSupport.length} طالب للمرشد.`);setReferralOpen(false);setSelectedIds([])}
 if(!teacherId)return <main className="mastery-dashboard" dir="rtl"><p>جارٍ التجهيز…</p></main>;
 return <main className="mastery-dashboard" dir="rtl">
  <section className="mastery-filters-card"><div className="mastery-filters">
   <label>الوحدة<select value={selectedSection} onChange={e=>{setSelectedSection(e.target.value);setSelectedIds([])}}>{activePlan?.sections.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
   <label>الفصل<select value={selectedClass} onChange={e=>{setSelectedClass(e.target.value);setSelectedIds([])}}><option value="">جميع الفصول</option>{classes.map(c=><option key={c}>{c}</option>)}</select></label>
   <label>نسبة الطالب<select value={exactPercentage} onChange={e=>setExactPercentage(e.target.value)}><option value="all">جميع النسب</option>{PERCENTAGES.map(p=><option key={p} value={p}>{p}% فقط</option>)}</select></label>
   <label>الحالة<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value as StatusFilter)}><option value="all">الجميع</option><option value="mastered">متقن</option><option value="support">غير متقن</option><option value="incomplete">غير مرصود</option></select></label>
   <label>حد الإتقان<select value={masteryThreshold} onChange={e=>setMasteryThreshold(Number(e.target.value))}><option value={90}>90%</option><option value={85}>85%</option><option value={80}>80%</option><option value={75}>75%</option><option value={70}>70%</option></select></label>
  </div></section>
  {!activePlan&&<div className="mastery-alert">لا توجد خطة درجات معتمدة.</div>}{loading&&<div className="mastery-alert">جارٍ تحميل الطلاب…</div>}
  <section className="mastery-stats"><div><span>نسبة الوحدة</span><strong>100%</strong></div><div><span>عدد الطلاب</span><strong>{rows.length}</strong></div><div><span>متوسط التحصيل</span><strong>{fmt(average)}%</strong></div><button onClick={()=>{setStatusFilter("mastered");setExactPercentage("all")}}><span>متقنون</span><strong>{mastered.length}</strong></button><button onClick={()=>{setStatusFilter("support");setExactPercentage("all")}}><span>غير متقنين</span><strong>{support.length}</strong></button><button onClick={()=>{setStatusFilter("incomplete");setExactPercentage("all")}}><span>غير مرصود</span><strong>{incomplete.length}</strong></button></section>
  <section className="mastery-panel"><div className="mastery-actions"><button onClick={selectAllSupport}>تحديد غير المتقنين</button><button className="referral" onClick={()=>{if(!selectedSupport.length)selectAllSupport();setReferralOpen(true)}}>إحالة للمرشد</button><button className="print" onClick={()=>window.print()}>طباعة</button></div>
   <div className="mastery-table-wrap"><table><thead><tr><th>تحديد</th><th>الطالب</th><th>الفصل</th><th>درجة الوحدة</th><th>نسبة الوحدة</th><th>حقق الطالب</th><th>الحالة</th><th>ملاحظة المعلم</th></tr></thead><tbody>{shownRows.map(r=><tr key={r.id}><td><input type="checkbox" disabled={r.status!=="support"} checked={selectedIds.includes(r.id)} onChange={e=>toggle(r.id,e.target.checked)}/></td><td className="student"><b>{r.name||"—"}</b><small>{r.code||r.accessCode||""}</small></td><td>{r.class||"—"}</td><td className="score"><b>{r.recorded?`${fmt(r.earned)} / ${fmt(r.maximum)}`:"—"}</b></td><td><span className="unit-full">100%</span></td><td><strong className={`achieved ${r.status}`}>{r.percentage===null?"—":`${fmt(r.percentage)}%`}</strong></td><td><span className={`status ${r.status}`}>{r.status==="mastered"?"متقن":r.status==="support"?"غير متقن":"غير مرصود"}</span></td><td className="note">{r.teacherNote||"—"}</td></tr>)}</tbody></table>{!shownRows.length&&<p className="empty">لا يوجد طلاب مطابقون للاختيار.</p>}</div>
  </section>
  {referralOpen&&<div className="mastery-modal" onClick={()=>setReferralOpen(false)}><section onClick={e=>e.stopPropagation()}><header><div><h3>إحالة غير المتقنين</h3><p>{selectedSupport.length} طالب</p></div><button onClick={()=>setReferralOpen(false)}>×</button></header><div className="referral-list">{selectedSupport.map(r=><div key={r.id}><b>{r.name}</b><span>{r.class} • {fmt(r.percentage||0)}%</span></div>)}</div><label>سبب الإحالة<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><footer><button onClick={()=>setReferralOpen(false)}>إلغاء</button><button className="confirm" onClick={()=>void sendReferral()}>تسجيل الإحالة</button></footer></section></div>}
  {message&&<div className="mastery-toast">{message}</div>}
 </main>
}
