"use client";
import { useEffect,useMemo,useState } from "react";
import { collection,doc,onSnapshot,updateDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import "./follow-up.css";
type UnitRecord={attendance?:number;participation?:number;homework?:number;unitExam?:number;total?:number;maximumTotal?:number;percentage?:number};
type Student={id:string;name?:string;class?:string;nationalId?:string;researchScore?:number;teacherNote?:string;units?:Record<string,UnitRecord>;parentCounselorNoticeSentAt?:string;parentCounselorNoticeSeenAt?:string};
const unitKeys=["unit1","unit2","unit3","unit4","unit5"];
const counselor={phone:"966598353651",label:"الموجه الطلابي"};
function studentTotal(s:Student){return unitKeys.reduce((sum,key)=>{const r=s.units?.[key]||{};return sum+Number(r.total??((r.attendance||0)+(r.participation||0)+(r.homework||0)+(r.unitExam||0)));},0)+Number(s.researchScore||0)}
function missingCount(s:Student){let c=0;unitKeys.forEach(k=>{const r=s.units?.[k]||{};if(r.attendance===undefined)c++;if(r.participation===undefined)c++;if(r.homework===undefined)c++;if(r.unitExam===undefined)c++});if(s.researchScore===undefined)c++;return c}
function level(t:number){if(t>=90)return{label:"متقن بتميز",className:"excellent"};if(t>=80)return{label:"متقن",className:"mastered"};if(t>=60)return{label:"غير متقن",className:"warning"};return{label:"يحتاج تدخلاً",className:"danger"}}
export default function FollowUpPage(){
 const [students,setStudents]=useState<Student[]>([]),[selectedClass,setSelectedClass]=useState(""),[threshold,setThreshold]=useState(80),[noteStudent,setNoteStudent]=useState<Student|null>(null),[note,setNote]=useState(""),[saved,setSaved]=useState(""),[reportOpen,setReportOpen]=useState(false),[notifyParents,setNotifyParents]=useState(false),[selectedStudentIds,setSelectedStudentIds]=useState<string[]>([]);
 useEffect(()=>onSnapshot(collection(db,"students"),snap=>{const list=snap.docs.map(d=>({id:d.id,...d.data()})) as Student[];list.sort((a,b)=>(a.name||"").localeCompare(b.name||"","ar"));setStudents(list)}),[]);
 const classes=useMemo(()=>Array.from(new Set(students.map(s=>(s.class||"").trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"ar")),[students]);
 const visible=useMemo(()=>students.filter(s=>!selectedClass||(s.class||"").trim()===selectedClass),[students,selectedClass]);
 const ranked=useMemo(()=>visible.map(s=>({...s,total:studentTotal(s),missing:missingCount(s)})).sort((a,b)=>b.total-a.total),[visible]);
 const nonMastered=useMemo(()=>ranked.filter(s=>s.total<threshold),[ranked,threshold]);
 const selectedStudents=useMemo(()=>nonMastered.filter(s=>selectedStudentIds.includes(s.id)),[nonMastered,selectedStudentIds]);
 const average=ranked.length?Math.round(ranked.reduce((sum,s)=>sum+s.total,0)/ranked.length):0,incomplete=ranked.filter(s=>s.missing>0);
 function openReport(){if(!nonMastered.length){setSaved("لا يوجد طلاب يحتاجون متابعة حالياً.");setTimeout(()=>setSaved(""),2500);return}setNotifyParents(false);setSelectedStudentIds(nonMastered.map(s=>s.id));setReportOpen(true)}
 function printList(){document.body.classList.add("printing-follow-up");window.print();setTimeout(()=>document.body.classList.remove("printing-follow-up"),300)}
 function exportPdf(){printList()}
 async function sendToCounselor(){const targets=selectedStudents;if(!targets.length){setSaved("حدد طالباً واحداً على الأقل للإرسال.");return}if(notifyParents){const now=new Date().toISOString();await Promise.all(targets.map(s=>s.parentCounselorNoticeSentAt?Promise.resolve():updateDoc(doc(db,"students",s.id),{parentCounselorNoticeSentAt:now})))}const msg=`السلام عليكم ورحمة الله وبركاته،\n\nتم رفع أسماء الطلاب الذين لم يحققوا نسبة الإتقان المطلوبة في مادة التاريخ:\n\n${targets.map((s,i)=>`${i+1}. ${s.name||"—"} — ${studentTotal(s)}%`).join("\n")}\n\nالمعلم: الأستاذ حسن علي الطويل\nمادة التاريخ – مدرسة التهذيب الثانوية`;window.open(`https://wa.me/${counselor.phone}?text=${encodeURIComponent(msg)}`,"_blank");setSaved(notifyParents?"تم تجهيز البلاغ وفتح واتساب للموجه، وسيظهر تنبيه ولي الأمر عند دخوله البوابة لأول مرة.":"تم فتح واتساب للموجه بالبلاغ الجاهز");setReportOpen(false);setTimeout(()=>setSaved(""),3500)}
 async function copyList(){const lines=["الطلاب غير المتقنين في مادة التاريخ",`الفصل: ${selectedClass||"جميع الفصول"}`,`المعيار: أقل من ${threshold}%`,...nonMastered.map((s,i)=>`${i+1}. ${s.name||"—"} | ${s.class||"—"} | ${s.nationalId||"—"} | ${s.total}/100`)];await navigator.clipboard.writeText(lines.join("\n"));setSaved("تم نسخ القائمة للموجّه الطلابي");setTimeout(()=>setSaved(""),2200)}
 async function saveNote(){if(!noteStudent)return;await updateDoc(doc(db,"students",noteStudent.id),{teacherNote:note.trim()});setSaved("تم حفظ ملاحظة المعلم وتظهر الآن لولي الأمر");setTimeout(()=>setSaved(""),2500)}
 return <main className="follow-page" dir="rtl">
 <section className="follow-head"><div><span>متابعة التحصيل الدراسي</span><h1>الإتقان والتنبيهات الذكية</h1><p>قائمة فورية للطلاب الأقل من معيار الإتقان مع أدوات جاهزة للموجّه الطلابي.</p></div><div className="follow-filters"><label>الفصل<select value={selectedClass} onChange={e=>setSelectedClass(e.target.value)}><option value="">جميع الفصول</option>{classes.map(c=><option key={c}>{c}</option>)}</select></label><label>معيار الإتقان<select value={threshold} onChange={e=>setThreshold(Number(e.target.value))}><option value={80}>أقل من ٨٠٪</option><option value={75}>أقل من ٧٥٪</option><option value={70}>أقل من ٧٠٪</option></select></label></div></section>
 <section className="follow-overview"><article><span>عدد الطلاب</span><strong>{ranked.length}</strong></article><article><span>متوسط الفصل</span><strong>{average}%</strong></article><article className="warn"><span>غير المتقنين</span><strong>{nonMastered.length}</strong></article><article className="alert"><span>ناقصو الرصد</span><strong>{incomplete.length}</strong></article></section>
 <section className="follow-grid"><article className="follow-card top-card"><header><div><h2>أفضل الطلاب</h2><p>الترتيب حسب المجموع النهائي.</p></div></header><div className="top-students">{ranked.slice(0,3).map((s,i)=><div key={s.id}><b>{["🥇","🥈","🥉"][i]}</b><span>{s.name}</span><strong>{s.total}</strong><small>{s.total-average>=0?`أعلى من المتوسط بـ ${s.total-average}`:`أقل من المتوسط بـ ${average-s.total}`}</small></div>)}</div></article><article className="follow-card alerts-card"><header><div><h2>تنبيهات الرصد</h2><p>طلاب لديهم خانات لم تُرصد بعد.</p></div></header><div className="alerts-list">{incomplete.slice(0,8).map(s=><div key={s.id}><span>{s.name}</span><b>{s.missing} خانة ناقصة</b></div>)}{!incomplete.length&&<p className="empty">جميع الدرجات مكتملة.</p>}</div></article></section>
 <section className="follow-card nonmastered-card print-follow-target"><header><div><h2>الطلاب غير المتقنين</h2><p>أقل من {threshold}% — جاهزة للنسخ أو الطباعة والإبلاغ للموجه الطلابي.</p></div><div className="follow-actions"><button onClick={copyList}>نسخ القائمة</button><button className="counselor-button" onClick={openReport}>📱 إبلاغ الموجه الطلابي عبر واتساب</button><button onClick={printList}>طباعة القائمة</button></div></header><div className="follow-print-title"><h2>مدرسة التهذيب الثانوية</h2><p>قائمة الطلاب غير المتقنين في مادة التاريخ</p><small>إعداد / الأستاذ حسن علي الطويل</small></div><div className="follow-table-wrap"><table><thead><tr><th>م</th><th>اسم الطالب</th><th>الفصل</th><th>السجل المدني</th><th>المجموع</th><th>المستوى</th><th>مقارنة بالمتوسط</th><th>ملاحظة</th></tr></thead><tbody>{nonMastered.map((s,i)=>{const l=level(s.total);return <tr key={s.id}><td>{i+1}</td><td><b>{s.name}</b></td><td>{s.class}</td><td>{s.nationalId||"—"}</td><td><strong>{s.total}/100</strong></td><td><span className={`level ${l.className}`}>{l.label}</span></td><td>{s.total-average>=0?`+${s.total-average}`:s.total-average}</td><td><button className="note-btn" onClick={()=>{setNoteStudent(s);setNote(s.teacherNote||"")}}>إضافة ملاحظة</button></td></tr>})}</tbody></table>{!nonMastered.length&&<p className="empty">لا يوجد طلاب أقل من معيار الإتقان المحدد.</p>}</div></section>
 {reportOpen&&<div className="report-modal" onClick={()=>setReportOpen(false)}><section onClick={e=>e.stopPropagation()}><div className="report-modal-head"><div><span>تقرير جاهز للإرسال</span><h3>إبلاغ الموجه الطلابي عبر واتساب</h3><p>حدد الطلاب الذين تريد إرسالهم فقط</p></div><button className="report-close" onClick={()=>setReportOpen(false)}>×</button></div><div className="report-table-wrap"><table><thead><tr><th><input type="checkbox" checked={selectedStudentIds.length===nonMastered.length&&nonMastered.length>0} onChange={e=>setSelectedStudentIds(e.target.checked?nonMastered.map(s=>s.id):[])}/></th><th>اسم الطالب</th><th>النسبة</th></tr></thead><tbody>{nonMastered.map(s=><tr key={s.id}><td><input type="checkbox" checked={selectedStudentIds.includes(s.id)} onChange={e=>setSelectedStudentIds(prev=>e.target.checked?[...prev,s.id]:prev.filter(id=>id!==s.id))}/></td><td><b>{s.name||"—"}</b></td><td>{s.total}%</td></tr>)}</tbody></table></div><label className="parent-notify-option"><input type="checkbox" checked={notifyParents} onChange={e=>setNotifyParents(e.target.checked)}/><span><b>إبلاغ ولي الأمر من خلال البوابة</b><small>سيظهر تنبيه لولي الأمر عند أول إبلاغ فقط لكل طالب.</small></span></label><div style={{marginBottom:12,padding:10,borderRadius:10,background:"rgba(0,0,0,.04)"}}><b>الموجه الطلابي</b><br/><small>واتساب: 966598353651</small></div><div className="report-modal-actions"><button onClick={()=>setReportOpen(false)}>إلغاء</button><button onClick={exportPdf}>📄 تصدير PDF</button><button onClick={printList}>🖨️ طباعة</button><button className="primary" onClick={sendToCounselor}>📱 فتح واتساب للموجه</button></div></section></div>}
 {noteStudent&&<div className="note-modal" onClick={()=>setNoteStudent(null)}><section onClick={e=>e.stopPropagation()}><h3>ملاحظة المعلم</h3><p>{noteStudent.name}</p><textarea value={note} onChange={e=>setNote(e.target.value)}/><div><button onClick={()=>setNoteStudent(null)}>إلغاء</button><button onClick={saveNote}>حفظ وإظهارها لولي الأمر</button></div></section></div>}
 {saved&&<div className="follow-toast">{saved}</div>}</main>;
}
