from pathlib import Path

path=Path('app/teacher/attendance/page.tsx')
text=path.read_text(encoding='utf-8')

old=''' useEffect(()=>{if(!ready)return;let active=true;const params=new URLSearchParams({subjectId:subjectKey});if(session?.activeGrade)params.set("grade",String(session.activeGrade));const localKey=`ostadh-lahooni:timetable:${teacherId}:${session?.workspaceKey||subjectKey}:${session?.activeGrade||"all"}`;const apply=(lessons:TimetableLesson[])=>{if(active)setTimetableClasses([...new Set(lessons.map(l=>normalizeClass(l.className)).filter(Boolean))])};fetch(`/api/teacher/timetable?${params}`,{credentials:"same-origin",cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{const lessons=data?.lessons&&typeof data.lessons==="object"?Object.values(data.lessons) as TimetableLesson[]:[];apply(lessons)}).catch(()=>{try{const data=JSON.parse(localStorage.getItem(localKey)||"null"),lessons=data?.lessons&&typeof data.lessons==="object"?Object.values(data.lessons) as TimetableLesson[]:[];apply(lessons)}catch{}});return()=>{active=false}},[ready,teacherId,subjectKey,session?.workspaceKey,session?.activeGrade]);
'''
new=''' useEffect(()=>{if(!ready)return;let active=true,loading=false;const params=new URLSearchParams({subjectId:subjectKey});if(session?.activeGrade)params.set("grade",String(session.activeGrade));const localKey=`ostadh-lahooni:timetable:${teacherId}:${session?.workspaceKey||subjectKey}:${session?.activeGrade||"all"}`;const apply=(lessons:TimetableLesson[])=>{if(active)setTimetableClasses([...new Set(lessons.map(l=>normalizeClass(l.className)).filter(Boolean))])};const refresh=async()=>{if(!active||loading)return;loading=true;try{const r=await fetch(`/api/teacher/timetable?${params}`,{credentials:"same-origin",cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json();const lessons=data?.lessons&&typeof data.lessons==="object"?Object.values(data.lessons) as TimetableLesson[]:[];apply(lessons)}catch{try{const data=JSON.parse(localStorage.getItem(localKey)||"null"),lessons=data?.lessons&&typeof data.lessons==="object"?Object.values(data.lessons) as TimetableLesson[]:[];apply(lessons)}catch{}}finally{loading=false}};const whenActive=()=>{if(document.visibilityState==="visible")void refresh()};void refresh();window.addEventListener("focus",whenActive);document.addEventListener("visibilitychange",whenActive);return()=>{active=false;window.removeEventListener("focus",whenActive);document.removeEventListener("visibilitychange",whenActive)}},[ready,teacherId,subjectKey,session?.workspaceKey,session?.activeGrade]);
'''
if old not in text: raise RuntimeError('timetable block changed; guarded patch stopped')
text=text.replace(old,new,1)

old2=''' useEffect(()=>{if(!selectedClass||!attendancePath){setRecords({});setHasSavedRecord(false);return}const defaults=Object.fromEntries(classStudents.map(st=>[studentCode(st),"present" as AttendanceStatus])),key=attendanceKey(teacherId,subjectKey,selectedClass,selectedDate),documentId=`${safeId(selectedClass)}_${selectedDate}`,local=readRecords(key)||readRecords(legacyAttendanceKey(teacherId,subjectKey,selectedClass,selectedDate)),deleted=Boolean(localStorage.getItem(attendanceDeletedKey(teacherId,subjectKey,selectedClass,selectedDate)));setRecords(defaults);setHasSavedRecord(false);let active=true;const useLocalFallback=()=>{if(!active||!local||deleted)return;setRecords(Object.fromEntries(classStudents.map(st=>[studentCode(st),local[studentCode(st)]||"present"])));setHasSavedRecord(true);setMessage("تعذر الوصول للسحابة؛ تم عرض نسخة الحضور المحفوظة على هذا الجهاز مؤقتًا.")};if(!navigator.onLine){useLocalFallback();return()=>{active=false}}withTimeout(getDoc(doc(db,attendancePath,documentId)),5000).then(s=>{if(!active)return;if(!s.exists()){if(local&&!deleted)useLocalFallback();return}const data=s.data() as AttendanceDocument,saved=data.records||{},next=Object.fromEntries(classStudents.map(st=>[studentCode(st),saved[studentCode(st)]||"present"])) as Record<string,AttendanceStatus>;setRecords(next);setHasSavedRecord(true);localStorage.setItem(key,JSON.stringify(next));const index=readAttendanceIndex(teacherId,subjectKey);index[documentId]=data;localStorage.setItem(attendanceIndexKey(teacherId,subjectKey),JSON.stringify(index))}).catch(()=>useLocalFallback());return()=>{active=false}},[selectedClass,selectedDate,classStudents,attendancePath,teacherId,subjectKey]);
'''
new2=''' useEffect(()=>{if(!selectedClass||!attendancePath){setRecords({});setHasSavedRecord(false);return}const defaults=Object.fromEntries(classStudents.map(st=>[studentCode(st),"present" as AttendanceStatus])),key=attendanceKey(teacherId,subjectKey,selectedClass,selectedDate),documentId=`${safeId(selectedClass)}_${selectedDate}`,local=readRecords(key)||readRecords(legacyAttendanceKey(teacherId,subjectKey,selectedClass,selectedDate)),deleted=Boolean(localStorage.getItem(attendanceDeletedKey(teacherId,subjectKey,selectedClass,selectedDate)));setRecords(defaults);setHasSavedRecord(false);let active=true,loading=false;const useLocalFallback=()=>{if(!active||!local||deleted)return;setRecords(Object.fromEntries(classStudents.map(st=>[studentCode(st),local[studentCode(st)]||"present"])));setHasSavedRecord(true);setMessage("تعذر الوصول للسحابة؛ تم عرض نسخة الحضور المحفوظة على هذا الجهاز مؤقتًا.")};const refresh=async()=>{if(!active||loading||saving||deleting)return;loading=true;try{if(!navigator.onLine){useLocalFallback();return}const s=await withTimeout(getDoc(doc(db,attendancePath,documentId)),5000);if(!active)return;if(!s.exists()){if(local&&!deleted)useLocalFallback();return}const data=s.data() as AttendanceDocument,saved=data.records||{},next=Object.fromEntries(classStudents.map(st=>[studentCode(st),saved[studentCode(st)]||"present"])) as Record<string,AttendanceStatus>;setRecords(next);setHasSavedRecord(true);localStorage.setItem(key,JSON.stringify(next));const index=readAttendanceIndex(teacherId,subjectKey);index[documentId]=data;localStorage.setItem(attendanceIndexKey(teacherId,subjectKey),JSON.stringify(index))}catch{useLocalFallback()}finally{loading=false}};const whenActive=()=>{if(document.visibilityState==="visible")void refresh()};void refresh();window.addEventListener("focus",whenActive);document.addEventListener("visibilitychange",whenActive);window.addEventListener("online",whenActive);return()=>{active=false;window.removeEventListener("focus",whenActive);document.removeEventListener("visibilitychange",whenActive);window.removeEventListener("online",whenActive)}},[selectedClass,selectedDate,classStudents,attendancePath,teacherId,subjectKey,saving,deleting]);
'''
if old2 not in text: raise RuntimeError('attendance block changed; guarded patch stopped')
text=text.replace(old2,new2,1)
path.write_text(text,encoding='utf-8')
print('Attendance and timetable now refresh safely on activation/online without polling or live Firestore listeners.')
