"use client";

import { FormEvent, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import Link from "next/link";
import { calculateGradePlanResult, normalizeGradePlan, type GradePlan, type GradeValueMap } from "../../lib/grade-plan";
import "./student-portal-v1000.css";

type GradeDeduction={id?:string;planId?:string;scope?:"plan"|"section"|"item";sectionId?:string;itemId?:string;amount?:number;reason?:string;note?:string;reversedAt?:string};
type AttendanceSummary={present?:number;absent?:number;late?:number;excused?:number;escaped?:number;total?:number;disciplineRate?:number};
type TeacherNote={id?:string;label?:string;message?:string;createdAt?:string;teacherName?:string;subject?:string};
type StudentRecord={gradePlan?:GradePlan|null;gradeValues?:GradeValueMap;gradePlanValues?:Record<string,GradeValueMap>;gradeDeductions?:GradeDeduction[];name?:string;class?:string;accessCode?:string;teacherName?:string;teacherNotes?:TeacherNote[];teacherNote?:string;attendanceSummary?:AttendanceSummary};
type Match={id:string;teacherId:string;subjectKey:string;subjectLabel:string;teacherName:string;icon?:string;accessToken:string;data:StudentRecord};
type StudentView="home"|"grades"|"report"|"certificate";
type SubjectMetric={match:Match;plan:GradePlan|null;result:ReturnType<typeof calculateGradePlanResult>|null;earned:number;maximum:number;percentage:number;completion:number;deducted:number;hasData:boolean};

const CODE_PATTERN=/^TH[123]\d{3}$/;
const LOGO="/icons/lahooni-identity-320.jpg";
const AVATAR="/student/student-avatar.svg";
const ar=(value:number)=>new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:2}).format(Number.isFinite(value)?value:0);
const gradeWord=(value:number)=>value>=90?"ممتاز":value>=80?"جيد جدًا":value>=70?"جيد":value>=60?"مقبول":"يحتاج دعمًا";

function normalizeStudentCode(value:string){return value.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);}
function activeDeductions(data:StudentRecord,plan:GradePlan){return (Array.isArray(data.gradeDeductions)?data.gradeDeductions:[]).filter(item=>!item.reversedAt&&Number(item.amount||0)>0&&(!item.planId||item.planId===plan.id));}
function metricFor(match:Match):SubjectMetric{
  const data=match.data||{};const plan=normalizeGradePlan(data.gradePlan);
  if(!plan)return{match,plan:null,result:null,earned:0,maximum:100,percentage:0,completion:0,deducted:0,hasData:false};
  const values=data.gradePlanValues?.[plan.id]||data.gradeValues||{};
  const result=calculateGradePlanResult(plan,{...data,gradeValues:values});
  const deductions=activeDeductions(data,plan);const deducted=Number(deductions.reduce((sum,item)=>sum+Math.max(0,Number(item.amount||0)),0).toFixed(2));
  const earned=Math.max(0,Number((result.earned-deducted).toFixed(2)));const maximum=result.maximum||100;
  return{match,plan,result,earned,maximum,percentage:maximum?Math.round(earned/maximum*100):0,completion:Math.round(result.completion||0),deducted,hasData:result.recordedMaximum>0};
}
function statusLabel(metric:SubjectMetric){if(!metric.plan)return"بانتظار الخطة";if(!metric.hasData)return"بانتظار الرصد";if(metric.completion<100)return"الرصد مستمر";if(metric.percentage>=90)return"متميز";if(metric.percentage>=80)return"متقدم";if(metric.percentage>=70)return"جيد";return"يحتاج دعمًا";}
function subjectSymbol(key:string){const value=key.split("--")[0];if(value==="history")return"🏛️";if(value==="critical-thinking")return"🧠";if(/math|financial/.test(value))return"∑";if(/science|physics|chemistry|biology/.test(value))return"⚗️";if(/arabic|linguistic/.test(value))return"ض";if(value==="english")return"A";if(/islam|quran|hadith|fiqh|tawhid|tafsir/.test(value))return"☪";if(/digital|computer/.test(value))return"⌘";return"📘";}
function compactDate(){return new Intl.DateTimeFormat("ar-SA",{year:"numeric",month:"long",day:"numeric",timeZone:"Asia/Riyadh"}).format(new Date());}

export default function StudentPage(){
  const [accessCode,setAccessCode]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
  const [matches,setMatches]=useState<Match[]>([]);const [selectedKey,setSelectedKey]=useState("");const [subjectGate,setSubjectGate]=useState(false);const [view,setView]=useState<StudentView>("home");const automaticLoginStarted=useRef(false);

  async function hydrate(match:Match){try{const response=await fetch("/api/student/profile",{headers:{Authorization:`Bearer ${match.accessToken}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));return response.ok&&payload.data?{...match,data:payload.data as StudentRecord}:match;}catch{return match;}}
  function speakWelcome(name:string){try{if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`مرحبًا ${name}. أهلًا بك في بوابة أستاذ لحوني التعليمية. نتمنى لك يومًا دراسيًا مميزًا.`);utterance.lang="ar-SA";utterance.rate=.94;utterance.pitch=1;window.speechSynthesis.speak(utterance);}catch{}}
  async function hydrateAll(raw:Match[]){const enriched=await Promise.all(raw.map(hydrate));setMatches(current=>current.length?enriched:current);}
  async function lookup(value:string,allowVoice=true){const code=normalizeStudentCode(value);setMessage("");if(!CODE_PATTERN.test(code))return setMessage("أدخل كود الطالب الصحيح المكوّن من 6 خانات.");setLoading(true);try{const response=await fetch("/api/student/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessCode:code}),cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)return setMessage(payload.message||"تعذر الدخول بكود الطالب.");const raw=Array.isArray(payload.matches)?payload.matches as Match[]:[];if(!raw.length)return setMessage("لا توجد مواد مرتبطة بهذا الطالب حتى الآن.");setAccessCode(code);setMatches(raw);setSelectedKey("");setView("home");setSubjectGate(true);setLoading(false);const knownName=raw[0]?.data?.name||"طالبنا";if(allowVoice)window.setTimeout(()=>speakWelcome(knownName),120);void hydrateAll(raw);}catch{setMessage("تعذر الاتصال بالبوابة الآن.");setLoading(false);}}
  function submit(event:FormEvent){event.preventDefault();void lookup(accessCode,true);}
  function chooseSubject(key:string){setSelectedKey(key);setSubjectGate(false);setView("home");window.scrollTo({top:0,behavior:"smooth"});}
  function logout(){try{window.speechSynthesis?.cancel();}catch{}setMatches([]);setSelectedKey("");setSubjectGate(false);setView("home");setAccessCode("");setMessage("");}

  useEffect(()=>{const query=new URLSearchParams(window.location.search);const code=normalizeStudentCode(query.get("code")||"");if(code)setAccessCode(code);if(query.size)window.history.replaceState({},"","/student");if(CODE_PATTERN.test(code)&&!automaticLoginStarted.current){automaticLoginStarted.current=true;void lookup(code,false);}},[]);
  useEffect(()=>{if(!selectedKey)return;let active=true;let busy=false;const refresh=async()=>{if(!active||busy||document.visibilityState!=="visible")return;const current=matches.find(item=>item.subjectKey===selectedKey);if(!current)return;busy=true;const updated=await hydrate(current);if(active)setMatches(list=>list.map(item=>item.subjectKey===selectedKey?updated:item));busy=false;};const onFocus=()=>void refresh();const onVisible=()=>{if(document.visibilityState==="visible")void refresh();};window.addEventListener("focus",onFocus);document.addEventListener("visibilitychange",onVisible);return()=>{active=false;window.removeEventListener("focus",onFocus);document.removeEventListener("visibilitychange",onVisible);};},[selectedKey,matches]);

  const metrics=useMemo(()=>matches.map(metricFor),[matches]);
  const selectedMetric=useMemo(()=>metrics.find(item=>item.match.subjectKey===selectedKey)||null,[metrics,selectedKey]);
  const studentName=matches[0]?.data?.name||"الطالب";const className=matches[0]?.data?.class||"الفصل غير محدد";
  const scored=metrics.filter(item=>item.hasData);const overall=scored.length?Math.round(scored.reduce((sum,item)=>sum+item.percentage,0)/scored.length):0;
  const overallCompletion=metrics.length?Math.round(metrics.reduce((sum,item)=>sum+item.completion,0)/metrics.length):0;
  const discipline=metrics.length?Math.round(metrics.reduce((sum,item)=>sum+Number(item.match.data.attendanceSummary?.disciplineRate??100),0)/metrics.length):100;

  if(!matches.length)return <main className="student-current-login" dir="rtl"><div className="student-scene"/><section className="scl-frame"><header className="scl-brand"><Link href="/"><img src={LOGO} alt="بوابة أستاذ لحوني التعليمية"/><span><small>بوابة أستاذ لحوني التعليمية</small><strong>بوابة الطالب وولي الأمر</strong></span></Link><Link href="/" className="scl-back">الرئيسية العامة</Link></header><div className="scl-grid"><section className="scl-intro"><span className="scl-kicker">● المساحة التعليمية الذكية</span><h1>كل تقدمك الدراسي<br/><em>أمامك بصورة أوضح</em></h1><p>نفس هوية بوابة أستاذ لحوني، ولكن بمساحة مخصصة للطالب: موادك، تحصيلك، تحليلك الدراسي وشهادتك في تجربة واحدة.</p><div className="scl-features"><article><i>↗</i><b>تحليل حي</b><span>رسوم وإحصائيات للتقدم</span></article><article><i>◎</i><b>خطة المعلم</b><span>درجات مرتبطة بالخطة الفعلية</span></article><article><i>✦</i><b>شهادة ذكية</b><span>جميع المواد في صفحة واحدة</span></article></div></section><form className="scl-card" onSubmit={submit}><div className="scl-card-glow"/><img src={LOGO} alt="هوية البوابة"/><small>دخول آمن وسريع</small><h2>أهلًا بك في بوابتك</h2><p>أدخل كود الطالب، وسنفتح قائمة موادك مباشرة بينما تُحمّل التفاصيل في الخلفية.</p><label><span>كود الطالب</span><div className="scl-input"><b>◈</b><input value={accessCode} onChange={e=>setAccessCode(normalizeStudentCode(e.target.value))} placeholder="TH1234" autoCapitalize="characters" autoComplete="off" inputMode="text" autoFocus/></div></label>{message?<p className="scl-error">{message}</p>:null}<button type="submit" disabled={loading}><span>{loading?"جارٍ التحقق…":"دخول بوابة الطالب"}</span><b>←</b></button><em>يتم عرض المواد والبيانات المرتبطة بك فقط.</em></form></div><footer><b>أستاذ لحوني</b> • تعليم أذكى، متابعة أوضح</footer></section></main>;

  if(subjectGate||!selectedKey)return <main className="student-current-gate" dir="rtl"><div className="student-scene"/><section className="scg-shell"><header><Link href="/" className="scg-brand"><img src={LOGO} alt="هوية البوابة"/><span><small>بوابة أستاذ لحوني التعليمية</small><strong>اختر مسارك الدراسي</strong></span></Link><div className="scg-student"><img src={AVATAR} alt="طالب"/><span><small>مرحبًا</small><strong>{studentName}</strong><b>{className}</b></span><button onClick={()=>speakWelcome(studentName)} title="تشغيل الترحيب">🔊</button></div></header><section className="scg-title"><span>موادك المرتبطة</span><h1>اختر المادة وابدأ متابعة تقدمك</h1><p>كل بطاقة تعرض قراءة سريعة للتحصيل، وبعد الدخول تظهر لك الإحصائيات التفصيلية وخطة المعلم.</p></section><div className="scg-subjects">{metrics.map((item,index)=><button key={item.match.subjectKey} onClick={()=>chooseSubject(item.match.subjectKey)} style={{"--delay":`${index*55}ms`} as CSSProperties}><i>{subjectSymbol(item.match.subjectKey)}</i><span><small>المادة</small><b>{item.match.subjectLabel}</b><em>{item.match.teacherName}</em></span><div className="scg-score"><strong>{item.hasData?`${ar(item.percentage)}٪`:"—"}</strong><small>{statusLabel(item)}</small></div><u style={{"--p":`${item.percentage}%`} as CSSProperties}/></button>)}</div><footer><button onClick={logout}>تسجيل الخروج</button><Link href="/">العودة للبوابة الرئيسية</Link></footer></section></main>;

  if(!selectedMetric)return null;
  const plan=selectedMetric.plan;const result=selectedMetric.result;const sections=result?.sections||[];const dimensions=result?.dimensions||[];
  const nav:Array<{key:StudentView;label:string;hint:string;icon:string}>=[{key:"home",label:"الرئيسية",hint:"الإحصائيات والتقدم",icon:"⌂"},{key:"grades",label:"درجاتي",hint:"تفاصيل المادة",icon:"◫"},{key:"report",label:"تقرير التحصيل",hint:"خطة المعلم كاملة",icon:"≡"},{key:"certificate",label:"الشهادة",hint:"جميع المواد",icon:"✦"}];
  const bestSubject=[...metrics].filter(m=>m.hasData).sort((a,b)=>b.percentage-a.percentage)[0];
  const attendance=selectedMetric.match.data.attendanceSummary;

  return <main className="student-current-shell" dir="rtl"><div className="student-scene"/><aside className="sc-sidebar"><Link href="/" className="sc-brand"><img src={LOGO} alt="هوية البوابة"/><span><small>أستاذ لحوني</small><b>بوابة الطالب</b></span></Link><section className="sc-profile"><div className="sc-avatar"><img src={AVATAR} alt="صورة الطالب"/><i/></div><div><small>الطالب</small><strong>{studentName}</strong><span>{className}</span></div></section><button className="sc-subject" onClick={()=>setSubjectGate(true)}><i>{subjectSymbol(selectedMetric.match.subjectKey)}</i><span><small>المادة الحالية</small><b>{selectedMetric.match.subjectLabel}</b><em>تغيير المادة ←</em></span></button><nav>{nav.map(item=><button key={item.key} className={view===item.key?"active":""} onClick={()=>setView(item.key)}><i>{item.icon}</i><span><b>{item.label}</b><small>{item.hint}</small></span></button>)}</nav><section className="sc-side-progress"><header><span>مؤشر المادة</span><b>{selectedMetric.hasData?`${ar(selectedMetric.percentage)}٪`:"—"}</b></header><u><i style={{width:`${selectedMetric.percentage}%`}}/></u><small>{statusLabel(selectedMetric)}</small></section><footer><button onClick={()=>speakWelcome(studentName)}>🔊 الترحيب</button><button onClick={logout}>خروج</button></footer></aside><section className="sc-stage"><header className="sc-head"><div><span className="sc-breadcrumb">{selectedMetric.match.subjectLabel} / {selectedMetric.match.teacherName}</span><h1>{nav.find(item=>item.key===view)?.label}</h1></div><div className="sc-head-tools"><span>{compactDate()}</span><button onClick={()=>setSubjectGate(true)}>المواد</button></div></header>

  {view==="home"?<div className="sc-home"><section className="sc-hero"><div><span className="sc-kicker">قراءة ذكية للتحصيل</span><h2>{studentName}، هذه صورتك التعليمية الآن</h2><p>{selectedMetric.plan?`تعتمد هذه المؤشرات مباشرة على خطة ${selectedMetric.match.subjectLabel} التي اختارها المعلم، ويبلغ اكتمال الرصد ${ar(selectedMetric.completion)}٪.`:"بانتظار اعتماد خطة التحصيل من معلم المادة."}</p><div className="sc-hero-chips"><span>أفضل مادة: <b>{bestSubject?.match.subjectLabel||"بانتظار الرصد"}</b></span><span>الانضباط: <b>{ar(discipline)}٪</b></span></div></div><div className="sc-ring" style={{"--p":`${selectedMetric.percentage}%`} as CSSProperties}><span><b>{selectedMetric.hasData?ar(selectedMetric.percentage):"—"}</b><small>٪</small></span></div></section><section className="sc-kpis"><article className="teal"><i>↗</i><span>متوسط المواد</span><b>{scored.length?`${ar(overall)}٪`:"—"}</b><small>{gradeWord(overall)}</small></article><article className="gold"><i>◎</i><span>اكتمال الرصد</span><b>{ar(overallCompletion)}٪</b><small>لجميع المواد</small></article><article className="blue"><i>✓</i><span>الانضباط</span><b>{ar(discipline)}٪</b><small>{Number(attendance?.absent||0)} غياب • {Number(attendance?.late||0)} تأخر</small></article><article className="violet"><i>▦</i><span>المواد المرتبطة</span><b>{ar(metrics.length)}</b><small>{ar(scored.length)} مواد بها رصد</small></article></section><div className="sc-analytics-grid"><section className="sc-chart-card"><header><div><small>مقارنة المواد</small><h3>مؤشر التحصيل العام</h3></div><b>{scored.length?`${ar(overall)}٪`:"—"}</b></header><div className="sc-subject-bars">{metrics.map(item=><div key={item.match.subjectKey}><span>{item.match.subjectLabel}</span><u><i style={{width:`${item.percentage}%`}}/></u><b>{item.hasData?`${ar(item.percentage)}٪`:"—"}</b></div>)}</div></section><section className="sc-chart-card"><header><div><small>المادة الحالية</small><h3>توزيع خطة التحصيل</h3></div><b>{ar(selectedMetric.completion)}٪</b></header><div className="sc-column-chart">{(sections.length?sections:[{id:"none",label:"بانتظار الرصد",percentage:0}]).map((section:any)=><div key={section.id}><b>{ar(section.percentage||0)}٪</b><u><i style={{height:`${Math.max(5,section.percentage||0)}%`}}/></u><span>{section.label}</span></div>)}</div></section></div></div>:null}

  {view==="grades"?<section className="sc-page sc-grades"><header className="sc-page-title"><div><span>درجات المادة</span><h2>{selectedMetric.match.subjectLabel}</h2><p>عرض بصري للدرجات المسجلة، مع توضيح درجة كل عنصر وسقفه المحدد في خطة المعلم.</p></div><div className="sc-score-orb"><b>{selectedMetric.hasData?ar(selectedMetric.earned):"—"}</b><span>من {ar(selectedMetric.maximum)}</span></div></header>{!plan?<div className="sc-empty">لم يعتمد المعلم خطة تحصيل لهذه المادة حتى الآن.</div>:<div className="sc-grade-sections">{sections.map((section,index)=><article key={section.id} style={{"--section-index":index} as CSSProperties}><header><div><small>محور التحصيل {ar(index+1)}</small><h3>{section.label}</h3></div><span><b>{ar(section.earned)}</b> / {ar(section.maximum)}</span></header><div className="sc-section-meter"><i style={{width:`${section.percentage}%`}}/></div><div className="sc-grade-items">{section.items.map(item=><div key={item.key} className={item.recorded?"recorded":"pending"}><span><i>{item.recorded?"✓":"•"}</i><b>{item.item.label}</b><small>{item.recorded?"تم الرصد":"بانتظار الرصد"}</small></span><strong>{item.recorded?ar(item.value):"—"}<em>/ {ar(item.maximum)}</em></strong><u><i style={{width:`${item.maximum?Math.min(100,item.counted/item.maximum*100):0}%`}}/></u></div>)}</div></article>)}</div>}{selectedMetric.deducted>0?<aside className="sc-deduction"><b>خصم معتمد</b><span>تم تطبيق خصم قدره {ar(selectedMetric.deducted)} درجة على النتيجة الحالية.</span></aside>:null}</section>:null}

  {view==="report"?<section className="sc-page sc-report"><header className="sc-page-title"><div><span>تقرير التحصيل العلمي</span><h2>قراءة كاملة لخطة {selectedMetric.match.subjectLabel}</h2><p>التقرير مبني مباشرة على الخطة التي اعتمدها المعلم، ويعرض المحاور والعناصر ومؤشرات القوة والتقدم.</p></div><div className="sc-report-status"><small>الحالة</small><b>{statusLabel(selectedMetric)}</b><span>اكتمال {ar(selectedMetric.completion)}٪</span></div></header><div className="sc-report-summary"><article><span>الدرجة الحالية</span><b>{selectedMetric.hasData?ar(selectedMetric.earned):"—"}<small> / {ar(selectedMetric.maximum)}</small></b></article><article><span>النسبة</span><b>{selectedMetric.hasData?`${ar(selectedMetric.percentage)}٪`:"—"}</b></article><article><span>الخطة</span><b className="text">{plan?.mode==="periods"?"الفترتان":plan?.mode==="units"?"الوحدات":plan?.mode==="custom"?"مخصصة":"من 100"}</b></article><article><span>الخصومات</span><b>{ar(selectedMetric.deducted)}</b></article></div>{plan?<><section className="sc-report-table"><header><span>المحور</span><span>المسجل</span><span>الدرجة</span><span>النسبة</span><span>الحالة</span></header>{sections.map(section=><div key={section.id}><strong>{section.label}</strong><span>{ar(section.recordedMaximum)} / {ar(section.maximum)}</span><span>{ar(section.earned)} / {ar(section.maximum)}</span><b>{ar(section.percentage)}٪</b><em className={section.complete?"done":"live"}>{section.complete?"مكتمل":"مستمر"}</em></div>)}</section><section className="sc-dimensions"><header><small>تحليل نوعي</small><h3>مؤشرات عناصر التقييم</h3></header><div>{dimensions.map(d=><article key={d.key}><span>{d.label}</span><b>{ar(d.percentage)}٪</b><u><i style={{width:`${d.percentage}%`}}/></u><small>{ar(d.earned)} من {ar(d.maximum)}</small></article>)}</div></section></>:<div className="sc-empty">بانتظار اعتماد خطة المعلم.</div>}</section>:null}

  {view==="certificate"?<section className="sc-page sc-certificate-page"><div className="sc-cert-toolbar"><div><span>الشهادة الأكاديمية الموحدة</span><b>تشمل جميع المواد المرتبطة بالطالب</b></div><button onClick={()=>window.print()}>🖨 طباعة الشهادة</button></div><article className="sc-certificate" id="student-certificate"><div className="cert-watermark">لـحـونـي</div><header><img src={LOGO} alt="هوية البوابة"/><div><small>بوابة أستاذ لحوني التعليمية</small><h2>شهادة بيان التحصيل الدراسي</h2><span>وثيقة إلكترونية صادرة من بوابة الطالب</span></div><b>◈</b></header><section className="cert-student"><div><small>اسم الطالب</small><b>{studentName}</b></div><div><small>الصف / الفصل</small><b>{className}</b></div><div><small>كود الطالب</small><b>{accessCode}</b></div><div><small>تاريخ الإصدار</small><b>{compactDate()}</b></div></section><section className="cert-summary"><div className="cert-ring" style={{"--p":`${overall}%`} as CSSProperties}><span><b>{scored.length?ar(overall):"—"}</b><small>٪</small></span></div><div><small>المعدل العام للمواد المرصودة</small><h3>{scored.length?gradeWord(overall):"بانتظار الرصد"}</h3><p>اكتمال الرصد العام {ar(overallCompletion)}٪ • مؤشر الانضباط {ar(discipline)}٪</p></div></section><section className="cert-table"><header><span>المادة</span><span>المعلم</span><span>الدرجة</span><span>النسبة</span><span>التقدير</span></header>{metrics.map(item=><div key={item.match.subjectKey}><b>{item.match.subjectLabel}</b><span>{item.match.teacherName}</span><span>{item.hasData?`${ar(item.earned)} / ${ar(item.maximum)}`:"بانتظار الرصد"}</span><strong>{item.hasData?`${ar(item.percentage)}٪`:"—"}</strong><em>{item.hasData?gradeWord(item.percentage):"—"}</em></div>)}</section><footer><div><small>ملاحظة</small><p>تعكس هذه الشهادة البيانات المرصودة في خطط التحصيل المعتمدة من معلمي المواد وقت إصدارها.</p></div><div className="cert-seal"><span>ختم البوابة</span><b>أستاذ<br/>لحوني</b><small>معتمد إلكترونيًا</small></div><div className="cert-sign"><small>إعداد وإشراف</small><b>الأستاذ حسن علي الطويل</b><span>بوابة أستاذ لحوني التعليمية</span></div></footer></article></section>:null}
  </section></main>;
}
