"use client";

import { FormEvent, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { calculateGradePlanResult, normalizeGradePlan, type GradePlan, type GradeValueMap } from "../../lib/grade-plan";
import "./student-portal-v1000.css";

type GradeDeduction={id?:string;planId?:string;scope?:"plan"|"section"|"item";sectionId?:string;itemId?:string;amount?:number;reason?:string;note?:string;reversedAt?:string};
type AttendanceDayCounts={present?:number;absent?:number;late?:number;excused?:number;escaped?:number;total?:number};
type AttendanceEvent={date:string;status:"absent"|"late"|"excused"|"escaped";period?:number|null};
type AttendanceSummary={present?:number;absent?:number;late?:number;excused?:number;escaped?:number;total?:number;disciplineRate?:number;latestDate?:string;latestDayCounts?:AttendanceDayCounts;events?:AttendanceEvent[]};
type TeacherNote={id?:string;label?:string;message?:string;createdAt?:string;teacherName?:string;subject?:string};
type CounselorReferral={id?:string;referralType?:string;referralTypeLabel?:string;reason?:string;status?:string;teacherName?:string;subject?:string;createdAt?:string;severity?:string};
type CounselorNotice={title?:string;message?:string;referralType?:string;subject?:string;teacherName?:string;referralId?:string;createdAt?:string};
type StudentRecord={gradePlan?:GradePlan|null;gradeValues?:GradeValueMap;gradePlanValues?:Record<string,GradeValueMap>;gradeDeductions?:GradeDeduction[];name?:string;class?:string;accessCode?:string;teacherName?:string;teacherNotes?:TeacherNote[];teacherNote?:string;attendanceSummary?:AttendanceSummary;counselorReferrals?:CounselorReferral[];parentCounselorLastNotice?:CounselorNotice;parentCounselorNoticeCount?:number};
type Match={id:string;teacherId:string;subjectKey:string;subjectLabel:string;teacherName:string;icon?:string;accessToken:string;data:StudentRecord};
type StudentView="home"|"discipline"|"grades"|"notes"|"report"|"certificate";
type SubjectMetric={match:Match;plan:GradePlan|null;result:ReturnType<typeof calculateGradePlanResult>|null;earned:number;maximum:number;percentage:number;completion:number;deducted:number;hasData:boolean};
type FeedItem={id:string;kind:"referral"|"note"|"alert";subject:string;title:string;text:string;meta:string;createdAt:string;tone:"violet"|"teal"|"gold"|"red"};

const CODE_PATTERN=/^TH[123]\d{3}$/;
const LOGO="/icons/lahooni-identity-320.jpg";
const AVATAR="/student/student-avatar.svg";
const ar=(value:number)=>new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:2}).format(Number.isFinite(value)?value:0);
const gradeWord=(value:number)=>value>=90?"ممتاز":value>=80?"جيد جدًا":value>=70?"جيد":value>=60?"مقبول":"يحتاج دعمًا";
const PROFILE_CACHE_TTL_MS=5*60*1000;
const profileCache=new Map<string,{expiresAt:number;match:Match}>();
const profileInflight=new Map<string,Promise<Match>>();

function normalizeStudentCode(value:string){return value.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);}
function activeDeductions(data:StudentRecord,plan:GradePlan){return (Array.isArray(data.gradeDeductions)?data.gradeDeductions:[]).filter(item=>!item.reversedAt&&Number(item.amount||0)>0&&(!item.planId||item.planId===plan.id));}
function metricFor(match:Match):SubjectMetric{
  const data=match.data||{};const plan=normalizeGradePlan(data.gradePlan);
  if(!plan)return{match,plan:null,result:null,earned:0,maximum:100,percentage:0,completion:0,deducted:0,hasData:false};
  const values=data.gradePlanValues?.[plan.id]||data.gradeValues||{};
  const result=calculateGradePlanResult(plan,{...data,gradeValues:values});
  const deductions=activeDeductions(data,plan);const deducted=Number(deductions.reduce((sum,item)=>sum+Math.max(0,Number(item.amount||0)),0).toFixed(2));
  const earned=Math.max(0,Number((result.earned-deducted).toFixed(2)));const maximum=result.maximum||100;
  return{match,plan,result,earned,maximum,percentage:maximum?Math.round(earned/maximum*100):0,completion:Math.round(result.completion||0),deducted,hasData:result.recordedMaximum>0};
}
function statusLabel(metric:SubjectMetric){if(!metric.plan)return"بانتظار الخطة";if(!metric.hasData)return"بانتظار الرصد";if(metric.completion<100)return"الرصد مستمر";if(metric.percentage>=90)return"متميز";if(metric.percentage>=80)return"متقدم";if(metric.percentage>=70)return"جيد";return"يحتاج دعمًا";}
function subjectSymbol(key:string){const value=key.split("--")[0];if(value==="history")return"🏛️";if(value==="critical-thinking")return"🧠";if(/math|financial/.test(value))return"∑";if(/science|physics|chemistry|biology/.test(value))return"⚗️";if(/arabic|linguistic/.test(value))return"ض";if(value==="english")return"A";if(/islam|quran|hadith|fiqh|tawhid|tafsir/.test(value))return"☪";if(/digital|computer/.test(value))return"⌘";return"📘";}
function compactDate(){return new Intl.DateTimeFormat("ar-SA",{year:"numeric",month:"long",day:"numeric",timeZone:"Asia/Riyadh"}).format(new Date());}
function feedDate(value:string){if(!value)return"بدون تاريخ";const date=new Date(value);if(Number.isNaN(date.getTime()))return value;return new Intl.DateTimeFormat("ar-SA",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Riyadh"}).format(date);}

export default function StudentPage(){
  const [accessCode,setAccessCode]=useState("");const [message,setMessage]=useState("");const [loading,setLoading]=useState(false);
  const [matches,setMatches]=useState<Match[]>([]);const [selectedKey,setSelectedKey]=useState("");const [subjectGate,setSubjectGate]=useState(false);const [view,setView]=useState<StudentView>("home");const automaticLoginStarted=useRef(false);

  async function hydrate(match:Match,force=false){const key=`${match.teacherId}:${match.subjectKey}:${match.id}`;const cached=profileCache.get(key);if(!force&&cached&&cached.expiresAt>Date.now())return cached.match;const pending=profileInflight.get(key);if(pending)return pending;const request=(async()=>{try{const response=await fetch("/api/student/profile",{headers:{Authorization:`Bearer ${match.accessToken}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));const next=response.ok&&payload.data?{...match,data:payload.data as StudentRecord}:match;profileCache.set(key,{expiresAt:Date.now()+PROFILE_CACHE_TTL_MS,match:next});return next;}catch{return match;}finally{profileInflight.delete(key);}})();profileInflight.set(key,request);return request;}
  function speakWelcome(name:string){try{if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`مرحبًا ${name}. أهلًا بك في بوابة أستاذ لحوني التعليمية. نتمنى لك يومًا دراسيًا مميزًا.`);utterance.lang="ar-SA";utterance.rate=.94;utterance.pitch=1;window.speechSynthesis.speak(utterance);}catch{}}
  async function hydrateAll(raw:Match[],force=false){const enriched=await Promise.all(raw.map(match=>hydrate(match,force)));setMatches(current=>current.length?enriched:current);}
  async function lookup(value:string,allowVoice=true){const code=normalizeStudentCode(value);setMessage("");if(!CODE_PATTERN.test(code))return setMessage("أدخل كود الطالب الصحيح المكوّن من 6 خانات.");setLoading(true);try{const response=await fetch("/api/student/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessCode:code}),cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)return setMessage(payload.message||"تعذر الدخول بكود الطالب.");const raw=Array.isArray(payload.matches)?payload.matches as Match[]:[];if(!raw.length)return setMessage("لا توجد مواد مرتبطة بهذا الطالب حتى الآن.");setAccessCode(code);setMatches(raw);setSelectedKey("");setView("home");setSubjectGate(true);setLoading(false);const knownName=raw[0]?.data?.name||"طالبنا";if(allowVoice)window.setTimeout(()=>speakWelcome(knownName),120);void hydrateAll(raw);}catch{setMessage("تعذر الاتصال بالبوابة الآن.");setLoading(false);}}
  function submit(event:FormEvent){event.preventDefault();void lookup(accessCode,true);}
  function chooseSubject(key:string){setSelectedKey(key);setSubjectGate(false);setView("home");window.scrollTo({top:0,behavior:"smooth"});}
  function logout(){try{window.speechSynthesis?.cancel();}catch{}setMatches([]);setSelectedKey("");setSubjectGate(false);setView("home");setAccessCode("");setMessage("");}

  useEffect(()=>{const query=new URLSearchParams(window.location.search);const code=normalizeStudentCode(query.get("code")||"");if(code)setAccessCode(code);if(query.size)window.history.replaceState({},"","/student");if(CODE_PATTERN.test(code)&&!automaticLoginStarted.current){automaticLoginStarted.current=true;void lookup(code,false);}},[]);
  // حدّث بيانات الطالب والحضور عند الرجوع للتطبيق/المتصفح بدون polling أو listener دائم.
  useEffect(()=>{
    if(!matches.length)return;
    let refreshing=false;
    const refresh=async()=>{
      if(refreshing)return;
      refreshing=true;
      try{await hydrateAll(matches,false);}finally{refreshing=false;}
    };
    const onPageShow=(event:PageTransitionEvent)=>{if(event.persisted)void refresh();};
    window.addEventListener("online",refresh);
    window.addEventListener("pageshow",onPageShow);
    return()=>{
      window.removeEventListener("online",refresh);
      window.removeEventListener("pageshow",onPageShow);
    };
  },[matches]);

  const metrics=useMemo(()=>matches.map(metricFor),[matches]);
  const selectedMetric=useMemo(()=>metrics.find(item=>item.match.subjectKey===selectedKey)||null,[metrics,selectedKey]);
  const studentName=matches[0]?.data?.name||"الطالب";const className=matches[0]?.data?.class||"الفصل غير محدد";
  const scored=metrics.filter(item=>item.hasData);const overall=scored.length?Math.round(scored.reduce((sum,item)=>sum+item.percentage,0)/scored.length):0;
  const overallCompletion=metrics.length?Math.round(metrics.reduce((sum,item)=>sum+item.completion,0)/metrics.length):0;
  const discipline=metrics.length?Math.round(metrics.reduce((sum,item)=>sum+Number(item.match.data.attendanceSummary?.disciplineRate??100),0)/metrics.length):100;
  const feed=useMemo(()=>{
    const rows:FeedItem[]=[];
    matches.forEach(match=>{
      const subject=match.subjectLabel;const data=match.data||{};
      const notes=Array.isArray(data.teacherNotes)?data.teacherNotes:[];
      notes.forEach((note,index)=>rows.push({id:`note-${match.subjectKey}-${note.id||index}`,kind:"note",subject,title:note.label||"ملاحظة من المعلم",text:note.message||"تم تسجيل ملاحظة تعليمية.",meta:note.teacherName||match.teacherName,createdAt:note.createdAt||"",tone:"teal"}));
      if(!notes.length&&data.teacherNote)rows.push({id:`legacy-note-${match.subjectKey}`,kind:"note",subject,title:"ملاحظة من المعلم",text:data.teacherNote,meta:match.teacherName,createdAt:"",tone:"teal"});
      const referrals=Array.isArray(data.counselorReferrals)?data.counselorReferrals:[];
      if(referrals.length)referrals.forEach((ref,index)=>rows.push({id:`ref-${match.subjectKey}-${ref.id||index}`,kind:"referral",subject,title:ref.referralTypeLabel||"إحالة للمرشد الطلابي",text:ref.reason||"إحالة للمتابعة مع المرشد الطلابي.",meta:`${ref.status||"جديدة"} • ${ref.teacherName||match.teacherName}`,createdAt:ref.createdAt||"",tone:"violet"}));
      else if(data.parentCounselorLastNotice?.message)rows.push({id:`notice-${match.subjectKey}-${data.parentCounselorLastNotice.referralId||"latest"}`,kind:"referral",subject,title:data.parentCounselorLastNotice.title||"إحالة للمرشد الطلابي",text:data.parentCounselorLastNotice.message,meta:data.parentCounselorLastNotice.teacherName||match.teacherName,createdAt:data.parentCounselorLastNotice.createdAt||"",tone:"violet"});
      const active=normalizeGradePlan(data.gradePlan);if(active){const deductions=activeDeductions(data,active);if(deductions.length){const total=deductions.reduce((sum,item)=>sum+Number(item.amount||0),0);rows.push({id:`deduction-${match.subjectKey}`,kind:"alert",subject,title:"تنبيه تحصيلي",text:`يوجد خصم معتمد بمقدار ${ar(total)} درجة في هذه المادة.`,meta:"التحصيل العلمي",createdAt:"",tone:"gold"});}}
      const attendance=data.attendanceSummary;const attendanceDay=attendance?.latestDayCounts||attendance;if(Number(attendanceDay?.absent||0)>0||Number(attendanceDay?.late||0)>0||Number(attendanceDay?.escaped||0)>0)rows.push({id:`attendance-${match.subjectKey}`,kind:"alert",subject,title:"آخر سجل حضور وانضباط",text:`الغياب ${ar(Number(attendanceDay?.absent||0))} • التأخر ${ar(Number(attendanceDay?.late||0))} • الهروب ${ar(Number(attendanceDay?.escaped||0))}`,meta:attendance?.latestDate?`سجل ${attendance.latestDate}`:"متابعة الانضباط",createdAt:attendance?.latestDate||"",tone:"red"});
    });
    return rows.sort((a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||"")));
  },[matches]);

  if(!matches.length)return <main className="student-current-login" dir="rtl"><div className="student-scene"/><section className="scl-frame"><header className="scl-brand"><div className="scl-brand-lock"><img src={LOGO} alt="بوابة أستاذ لحوني التعليمية"/><span><small>بوابة أستاذ لحوني التعليمية</small><strong>بوابة الطالب وولي الأمر</strong></span></div></header><div className="scl-grid"><section className="scl-intro"><span className="scl-kicker">● المساحة التعليمية الذكية</span><h1>كل تقدمك الدراسي<br/><em>أمامك بصورة أوضح</em></h1><p>نفس هوية بوابة أستاذ لحوني، ولكن بمساحة مخصصة للطالب: موادك، تحصيلك، تحليلك الدراسي وشهادتك في تجربة واحدة.</p><div className="scl-features"><article><i>↗</i><b>تحليل حي</b><span>رسوم وإحصائيات للتقدم</span></article><article><i>◎</i><b>خطة المعلم</b><span>درجات مرتبطة بالخطة الفعلية</span></article><article><i>✦</i><b>شهادة ذكية</b><span>جميع المواد في صفحة واحدة</span></article></div></section><form className="scl-card" onSubmit={submit}><div className="scl-card-glow"/><img src={LOGO} alt="هوية البوابة"/><small>دخول آمن وسريع</small><h2>أهلًا بك في بوابتك</h2><p>أدخل كود الطالب، وسنفتح قائمة موادك مباشرة بينما تُحمّل التفاصيل في الخلفية.</p><label><span>كود الطالب</span><div className="scl-input"><b>◈</b><input value={accessCode} onChange={e=>setAccessCode(normalizeStudentCode(e.target.value))} placeholder="TH1234" autoCapitalize="characters" autoComplete="off" inputMode="text" autoFocus/></div></label>{message?<p className="scl-error">{message}</p>:null}<button type="submit" disabled={loading}><span>{loading?"جارٍ التحقق…":"دخول بوابة الطالب"}</span><b>←</b></button><em>يتم عرض المواد والبيانات المرتبطة بك فقط.</em></form></div><footer><b>أستاذ لحوني</b> • تعليم أذكى، متابعة أوضح</footer></section></main>;

  if(subjectGate||!selectedKey)return <main className="student-current-gate" dir="rtl"><div className="student-scene"/><section className="scg-shell"><header><div className="scg-brand scg-brand-lock"><img src={LOGO} alt="هوية البوابة"/><span><small>بوابة أستاذ لحوني التعليمية</small><strong>اختر مسارك الدراسي</strong></span></div><div className="scg-student"><img src={AVATAR} alt="طالب"/><span><small>مرحبًا</small><strong>{studentName}</strong><b>{className}</b></span><button onClick={()=>speakWelcome(studentName)} title="تشغيل الترحيب">🔊</button></div></header><section className="scg-title"><span>موادك المرتبطة</span><h1>اختر المادة وابدأ متابعة تقدمك</h1><p>كل بطاقة تعرض قراءة سريعة للتحصيل، وبعد الدخول تظهر لك الإحصائيات التفصيلية وخطة المعلم.</p></section><div className="scg-subjects">{metrics.map((item,index)=><button key={item.match.subjectKey} onClick={()=>chooseSubject(item.match.subjectKey)} style={{"--delay":`${index*55}ms`} as CSSProperties}><i>{subjectSymbol(item.match.subjectKey)}</i><span><small>المادة</small><b>{item.match.subjectLabel}</b><em>{item.match.teacherName}</em></span><div className="scg-score"><strong>{item.hasData?`${ar(item.percentage)}٪`:"—"}</strong><small>{statusLabel(item)}</small></div><u style={{"--p":`${item.percentage}%`} as CSSProperties}/></button>)}</div><footer><button onClick={logout}>تسجيل الخروج</button></footer></section></main>;

  if(!selectedMetric)return null;
  const plan=selectedMetric.plan;const result=selectedMetric.result;const sections=result?.sections||[];const dimensions=result?.dimensions||[];
  const nav:Array<{key:StudentView;label:string;hint:string;icon:string;count?:number}>=[{key:"home",label:"الرئيسية",hint:"الإحصائيات والتقدم",icon:"⌂"},{key:"discipline",label:"الانضباط",hint:"الحضور وحالات المتابعة",icon:"✓"},{key:"grades",label:"درجاتي",hint:"تفاصيل المادة",icon:"◫"},{key:"notes",label:"الملاحظات والتنبيهات",hint:"المعلم والمرشد",icon:"!",count:feed.length},{key:"report",label:"تقرير التحصيل",hint:"خطة المعلم كاملة",icon:"≡"},{key:"certificate",label:"الشهادة",hint:"جميع المواد",icon:"✦"}];
  const bestSubject=[...metrics].filter(m=>m.hasData).sort((a,b)=>b.percentage-a.percentage)[0];
  const attendance=selectedMetric.match.data.attendanceSummary;

  return <main className="student-current-shell" dir="rtl"><div className="student-scene"/><aside className="sc-sidebar"><div className="sc-brand sc-brand-lock"><img src={LOGO} alt="هوية البوابة"/><span><small>أستاذ لحوني</small><b>بوابة الطالب</b></span></div><section className="sc-profile"><div className="sc-avatar"><img src={AVATAR} alt="صورة الطالب"/><i/></div><div><small>الطالب</small><strong>{studentName}</strong><span>{className}</span></div></section><button className="sc-subject" onClick={()=>setSubjectGate(true)}><i>{subjectSymbol(selectedMetric.match.subjectKey)}</i><span><small>المادة الحالية</small><b>{selectedMetric.match.subjectLabel}</b><em>تغيير المادة ←</em></span></button><div className="sc-quick-actions"><button onClick={()=>setSubjectGate(true)}>📚 <b>المواد</b></button><button className="logout" onClick={logout}>↪ <b>تسجيل الخروج</b></button></div><nav>{nav.map(item=><button key={item.key} className={view===item.key?"active":""} onClick={()=>setView(item.key)}><i>{item.icon}</i><span><b>{item.label}</b><small>{item.hint}</small></span>{typeof item.count==="number"&&item.count>0?<em className="sc-nav-count">{ar(item.count)}</em>:null}</button>)}</nav><section className="sc-side-progress"><header><span>مؤشر المادة</span><b>{selectedMetric.hasData?`${ar(selectedMetric.percentage)}٪`:"—"}</b></header><u><i style={{width:`${selectedMetric.percentage}%`}}/></u><small>{statusLabel(selectedMetric)}</small></section><footer><button onClick={()=>speakWelcome(studentName)}>🔊 الترحيب</button><button onClick={logout}>خروج</button></footer></aside><section className="sc-stage"><header className="sc-head"><div><span className="sc-breadcrumb">{selectedMetric.match.subjectLabel} / {selectedMetric.match.teacherName}</span><h1>{nav.find(item=>item.key===view)?.label}</h1></div><div className="sc-head-tools"><span>{compactDate()}</span><button onClick={()=>setSubjectGate(true)}>المواد</button></div></header>

  {view==="home"?<div className="sc-home"><section className="sc-hero"><div><span className="sc-kicker">قراءة ذكية للتحصيل</span><h2>{studentName}، هذه صورتك التعليمية الآن</h2><p>{selectedMetric.plan?`تعتمد هذه المؤشرات مباشرة على خطة ${selectedMetric.match.subjectLabel} التي اختارها المعلم، ويبلغ اكتمال الرصد ${ar(selectedMetric.completion)}٪.`:"بانتظار اعتماد خطة التحصيل من معلم المادة."}</p><div className="sc-hero-chips"><span>أفضل مادة: <b>{bestSubject?.match.subjectLabel||"بانتظار الرصد"}</b></span><span>الانضباط: <b>{ar(discipline)}٪</b></span></div></div><div className="sc-ring" style={{"--p":`${selectedMetric.percentage}%`} as CSSProperties}><span><b>{selectedMetric.hasData?ar(selectedMetric.percentage):"—"}</b><small>٪</small></span></div></section><section className="sc-kpis"><article className="teal"><i>↗</i><span>متوسط المواد</span><b>{scored.length?`${ar(overall)}٪`:"—"}</b><small>{gradeWord(overall)}</small></article><article className="gold"><i>◎</i><span>اكتمال الرصد</span><b>{ar(overallCompletion)}٪</b><small>لجميع المواد</small></article><article className="blue"><i>✓</i><span>الانضباط</span><b>{ar(discipline)}٪</b><small>{Number(attendance?.absent||0)} غياب • {Number(attendance?.late||0)} تأخر</small></article><article className="violet"><i>!</i><span>الملاحظات والتنبيهات</span><b>{ar(feed.length)}</b><small>من جميع المواد</small></article></section><div className="sc-analytics-grid"><section className="sc-chart-card"><header><div><small>مقارنة المواد</small><h3>مؤشر التحصيل العام</h3></div><b>{scored.length?`${ar(overall)}٪`:"—"}</b></header><div className="sc-subject-bars">{metrics.map(item=><div key={item.match.subjectKey}><span>{item.match.subjectLabel}</span><u><i style={{width:`${item.percentage}%`}}/></u><b>{item.hasData?`${ar(item.percentage)}٪`:"—"}</b></div>)}</div></section><section className="sc-chart-card"><header><div><small>المادة الحالية</small><h3>توزيع خطة التحصيل</h3></div><b>{ar(selectedMetric.completion)}٪</b></header><div className="sc-column-chart">{(sections.length?sections:[{id:"none",label:"بانتظار الرصد",percentage:0}]).map((section:any)=><div key={section.id}><b>{ar(section.percentage||0)}٪</b><u><i style={{height:`${Math.max(5,section.percentage||0)}%`}}/></u><span>{section.label}</span></div>)}</div></section></div></div>:null}

  {view==="discipline"?<section className="sc-page sc-discipline"><header className="sc-page-title"><div><span>متابعة الحضور والانضباط</span><h2>الانضباط</h2><p>البيانات مرتبطة مباشرة بسجل معلم {selectedMetric.match.subjectLabel}، وتُحسب من الحصص التي حفظ المعلم حالتها فعليًا.</p></div><div className="sc-score-orb"><b>{ar(Number(attendance?.disciplineRate??100))}</b><small>٪ انضباط</small></div></header><section className="sc-kpis discipline-kpis"><article className="teal"><i>✓</i><span>حضور</span><b>{ar(Number(attendance?.present||0))}</b><small>من الحصص المسجلة</small></article><article className="red"><i>×</i><span>غياب</span><b>{ar(Number(attendance?.absent||0))}</b><small>حالة مسجلة</small></article><article className="gold"><i>↗</i><span>تأخر</span><b>{ar(Number(attendance?.late||0))}</b><small>حالة مسجلة</small></article><article className="violet"><i>↪</i><span>استئذان</span><b>{ar(Number(attendance?.excused||0))}</b><small>حالة مسجلة</small></article><article className="red"><i>!</i><span>هروب</span><b>{ar(Number(attendance?.escaped||0))}</b><small>حالة مسجلة</small></article></section><section className="sc-chart-card discipline-summary"><header><div><small>النسبة من أصل الحصص المسجلة</small><h3>مؤشر الحضور والانضباط</h3></div><b>{ar(Number(attendance?.disciplineRate??100))}٪</b></header><div className="discipline-meter"><u><i style={{width:`${Number(attendance?.disciplineRate??100)}%`}}/></u><div><span>إجمالي الحصص: <b>{ar(Number(attendance?.total||0))}</b></span><span>آخر تحديث: <b>{attendance?.latestDate||"لا يوجد سجل بعد"}</b></span></div></div><div className="discipline-events"><h3>سجل الحالات</h3><div className="discipline-table"><div className="discipline-row head"><span>اليوم</span><span>التاريخ</span><span>الحصة</span><span>الحالة</span></div>{(attendance?.events||[]).length?(attendance?.events||[]).map((event,index)=>{const labels:Record<AttendanceEvent["status"],string>={absent:"غياب",late:"تأخر",excused:"استئذان",escaped:"هروب"};const d=new Date(`${event.date}T12:00:00`);const day=Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("ar-SA",{weekday:"long",timeZone:"Asia/Riyadh"}).format(d);return <div className="discipline-row" key={`${event.date}-${index}`}><span>{day}</span><span>{event.date}</span><span>{event.period?`الحصة ${ar(event.period)}`:"—"}</span><span className={`status-${event.status}`}>{labels[event.status]}</span></div>}):<div className="discipline-empty">لا توجد حالات غياب أو تأخر أو استئذان أو هروب مسجلة.</div>}</div></div></section></section>:null}

  {view==="grades"?<section className="sc-page sc-grades"><header className="sc-page-title"><div><span>درجات المادة</span><h2>{selectedMetric.match.subjectLabel}</h2><p>عرض بصري للدرجات المسجلة، مع توضيح درجة كل عنصر وسقفه المحدد في خطة المعلم.</p></div><div className="sc-score-orb"><b>{selectedMetric.hasData?ar(selectedMetric.earned):"—"}</b><span>من {ar(selectedMetric.maximum)}</span></div></header>{!plan?<div className="sc-empty">لم يعتمد المعلم خطة تحصيل لهذه المادة حتى الآن.</div>:<div className="sc-grade-sections">{sections.map((section,index)=><article key={section.id} style={{"--section-index":index} as CSSProperties}><header><div><small>محور التحصيل {ar(index+1)}</small><h3>{section.label}</h3></div><span><b>{ar(section.earned)}</b> / {ar(section.maximum)}</span></header><div className="sc-section-meter"><i style={{width:`${section.percentage}%`}}/></div><div className="sc-grade-items">{section.items.map(item=><div key={item.key} className={item.recorded?"recorded":"pending"}><span><i>{item.recorded?"✓":"•"}</i><b>{item.item.label}</b><small>{item.recorded?"تم الرصد":"بانتظار الرصد"}</small></span><strong>{item.recorded?ar(item.value):"—"}<em>/ {ar(item.maximum)}</em></strong><u><i style={{width:`${item.maximum?Math.min(100,item.counted/item.maximum*100):0}%`}}/></u></div>)}</div></article>)}</div>}{selectedMetric.deducted>0?<aside className="sc-deduction"><b>خصم معتمد</b><span>تم تطبيق خصم قدره {ar(selectedMetric.deducted)} درجة على النتيجة الحالية.</span></aside>:null}</section>:null}

  {view==="notes"?<section className="sc-page sc-notes"><header className="sc-page-title"><div><span>الملاحظات والتنبيهات</span><h2>مركز المتابعة الخاص بك</h2><p>يجمع ملاحظات المعلمين، تنبيهات التحصيل والانضباط، وجميع إحالات المرشد الطلابي الظاهرة لك من كل المواد.</p></div><div className="sc-notes-total"><b>{ar(feed.length)}</b><span>إجمالي السجل</span></div></header><div className="sc-notes-stats"><article><i className="violet">◆</i><span><small>إحالات المرشد</small><b>{ar(feed.filter(i=>i.kind==="referral").length)}</b></span></article><article><i className="teal">✎</i><span><small>ملاحظات المعلمين</small><b>{ar(feed.filter(i=>i.kind==="note").length)}</b></span></article><article><i className="gold">!</i><span><small>تنبيهات المتابعة</small><b>{ar(feed.filter(i=>i.kind==="alert").length)}</b></span></article></div>{feed.length?<div className="sc-feed">{feed.map(item=><article key={item.id} className={`sc-feed-item ${item.tone}`}><i className="sc-feed-icon">{item.kind==="referral"?"◆":item.kind==="note"?"✎":"!"}</i><div><header><span>{item.subject}</span><small>{feedDate(item.createdAt)}</small></header><h3>{item.title}</h3><p>{item.text}</p><footer>{item.kind==="referral"?<b>المرشد الطلابي</b>:item.kind==="note"?<b>ملاحظة تعليمية</b>:<b>تنبيه متابعة</b>}<span>{item.meta}</span></footer></div></article>)}</div>:<div className="sc-empty">لا توجد ملاحظات أو تنبيهات أو إحالات مسجلة حاليًا.</div>}</section>:null}

  {view==="report"?<section className="sc-page sc-report"><header className="sc-page-title"><div><span>تقرير التحصيل العلمي</span><h2>قراءة كاملة لخطة {selectedMetric.match.subjectLabel}</h2><p>التقرير مبني مباشرة على الخطة التي اعتمدها المعلم، ويعرض المحاور والعناصر ومؤشرات القوة والتقدم.</p></div><div className="sc-report-status"><small>الحالة</small><b>{statusLabel(selectedMetric)}</b><span>اكتمال {ar(selectedMetric.completion)}٪</span></div></header><div className="sc-report-summary"><article><span>الدرجة الحالية</span><b>{selectedMetric.hasData?ar(selectedMetric.earned):"—"}<small> / {ar(selectedMetric.maximum)}</small></b></article><article><span>النسبة</span><b>{selectedMetric.hasData?`${ar(selectedMetric.percentage)}٪`:"—"}</b></article><article><span>الخطة</span><b className="text">{plan?.mode==="periods"?"الفترتان":plan?.mode==="units"?"الوحدات":plan?.mode==="custom"?"مخصصة":"من 100"}</b></article><article><span>الخصومات</span><b>{ar(selectedMetric.deducted)}</b></article></div>{plan?<><section className="sc-report-table"><header><span>المحور</span><span>المسجل</span><span>الدرجة</span><span>النسبة</span><span>الحالة</span></header>{sections.map(section=><div key={section.id}><strong>{section.label}</strong><span>{ar(section.recordedMaximum)} / {ar(section.maximum)}</span><span>{ar(section.earned)} / {ar(section.maximum)}</span><b>{ar(section.percentage)}٪</b><em className={section.complete?"done":"live"}>{section.complete?"مكتمل":"مستمر"}</em></div>)}</section><section className="sc-dimensions"><header><small>تحليل نوعي</small><h3>مؤشرات عناصر التقييم</h3></header><div>{dimensions.map(d=><article key={d.key}><span>{d.label}</span><b>{ar(d.percentage)}٪</b><u><i style={{width:`${d.percentage}%`}}/></u><small>{ar(d.earned)} من {ar(d.maximum)}</small></article>)}</div></section></>:<div className="sc-empty">بانتظار اعتماد خطة المعلم.</div>}</section>:null}

  {view==="certificate"?<section className="sc-page sc-certificate-page"><div className="sc-cert-toolbar"><div><span>شهادة الطالب</span><b>شهادتك مرتبطة بالمادة الحالية وبياناتك فقط</b></div><button onClick={()=>window.print()}>🖨 طباعة الشهادة</button></div><article className="sc-certificate" id="student-certificate"><div className="cert-watermark">لـحـونـي</div><header><img src={LOGO} alt="هوية البوابة"/><div><small>بوابة أستاذ لحوني التعليمية</small><h2>شهادة التحصيل والانضباط</h2><span>وثيقة إلكترونية خاصة بالطالب</span></div><b>◈</b></header><section className="cert-student"><div><small>اسم الطالب</small><b>{studentName}</b></div><div><small>الصف / الفصل</small><b>{className}</b></div><div><small>المادة</small><b>{selectedMetric.match.subjectLabel}</b></div><div><small>المعلم</small><b>{selectedMetric.match.teacherName}</b></div></section><section className="cert-summary"><div className="cert-ring" style={{"--p:`${selectedMetric.percentage}%`} as CSSProperties}><span><b>{selectedMetric.hasData?ar(selectedMetric.percentage):"—"}</b><small>٪</small></span></div><div><small>التحصيل في المادة</small><h3>{selectedMetric.hasData?gradeWord(selectedMetric.percentage):"بانتظار الرصد"}</h3><p>الدرجة {selectedMetric.hasData?`${ar(selectedMetric.earned)} من ${ar(selectedMetric.maximum)}`:"بانتظار الرصد"} • الخصومات {ar(selectedMetric.deducted)} • الحضور {ar(Number(attendance?.disciplineRate??100))}٪</p></div></section><section className="cert-table cert-detail-table"><header><span>محور التقييم</span><span>المسجل</span><span>الدرجة</span><span>النسبة</span><span>الحالة</span></header>{sections.length?sections.map(section=><div key={section.id}><b>{section.label}</b><span>{ar(section.recordedMaximum)} / {ar(section.maximum)}</span><span>{ar(section.earned)} / {ar(section.maximum)}</span><strong>{ar(section.percentage)}٪</strong><em>{section.complete?"مكتمل":"مستمر"}</em></div>):<div><b>التحصيل العلمي</b><span>بانتظار الرصد</span><span>—</span><strong>—</strong><em>—</em></div>}</section><section className="cert-attendance"><div><small>حضور</small><b>{ar(Number(attendance?.present||0))}</b></div><div><small>غياب</small><b>{ar(Number(attendance?.absent||0))}</b></div><div><small>تأخر</small><b>{ar(Number(attendance?.late||0))}</b></div><div><small>استئذان</small><b>{ar(Number(attendance?.excused||0))}</b></div><div><small>هروب</small><b>{ar(Number(attendance?.escaped||0))}</b></div></section><footer><div><small>بيان الشهادة</small><p>تعكس هذه الشهادة التحصيل والحضور والانضباط المسجل للطالب في المادة وقت إصدارها. تاريخ الإصدار: {compactDate()}.</p></div><div className="cert-seal"><span>ختم البوابة</span><b>أستاذ<br/>لحوني</b><small>معتمد إلكترونيًا</small></div><div className="cert-sign"><small>المعلم</small><b>{selectedMetric.match.teacherName}</b><span>{selectedMetric.match.subjectLabel}</span></div></footer></article></section>:null}
  </section></main>;
}
