"use client";
import { useEffect, useMemo, useState } from "react";

type Question = { id: string; text: string; options: string[]; skill: string };
type Result = { score: number; total: number; percentage: number; plan: string; weakSkills: string[] };
type Diagnostic = { id: string; title: string; instructions: string; questionCount: number; questions: Question[]; completed: boolean; result: Result | null };
const messages = ["ابدأ بخطوة صغيرة، التحسن ممكن.","راجع الأساسيات واطلب مساعدة معلمك.","كل تدريب جديد يقربك من هدفك.","ركز على المهارة الأضعف أولًا.","استمرارك أهم من سرعة تقدمك.","تقدمك بدأ، لا تتوقف.","حوّل أخطاءك إلى فرص تعلم.","أنت تتحسن، واصل التدريب.","جهدك واضح وسترى نتيجته.","اقتربت من المستوى الجيد.","عمل جيد، ركز على التفاصيل.","ثباتك يصنع فرقًا حقيقيًا.","مستواك جيد وقابل للارتفاع.","أحسنت، حافظ على انتظامك.","تقدم واضح، استمر.","أداء قوي وبقيت خطوات بسيطة.","متميز، حافظ على المراجعة.","أنت قريب جدًا من القمة.","أداء رائع ومطمئن.","مبدع، واصل تميزك.","إنجاز استثنائي، أحسنت."];
function smartAdvice(result: Result) { const skills = result.weakSkills.length ? `ابدأ بمراجعة: ${result.weakSkills.join("، ")}.` : "حافظ على المراجعة المنتظمة وحل أسئلة إثرائية."; if (result.percentage < 50) return `${skills} خصص ٢٠ دقيقة يوميًا للتعلم مع المعلم ثم أعد القياس.`; if (result.percentage < 80) return `${skills} نفذ تدريبًا قصيرًا بعد كل درس وراجع الأخطاء مباشرة.`; return `${skills} انتقل إلى أنشطة أعمق وشارك زملاءك طريقة الحل.`; }

export default function StudentDiagnostics({ accessToken }: { accessToken: string }) {
  const [items, setItems] = useState<Diagnostic[]>([]), [active, setActive] = useState<Diagnostic | null>(null), [resultView, setResultView] = useState<{ title: string; result: Result } | null>(null), [answers, setAnswers] = useState<Record<string, number>>({}), [message, setMessage] = useState(""), [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false);
  async function load(selectResult = true) { setLoading(true); try { const response = await fetch("/api/student/diagnostics", { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" }); const data = await response.json(); if (response.ok) { const diagnostics = data.diagnostics || []; setItems(diagnostics); const latest = diagnostics.find((item: Diagnostic) => item.completed && item.result); if (selectResult && latest) setResultView({ title: latest.title, result: latest.result }); } else setMessage("تعذر تحميل الاختبارات."); } finally { setLoading(false); } }
  useEffect(() => { void load(true); }, [accessToken]);
  const progress = active?.questions.length ? Math.round(Object.keys(answers).length / active.questions.length * 100) : 0;
  const motivation = useMemo(() => resultView ? messages[Math.min(20, Math.max(0, Math.floor(resultView.result.percentage / 5)))] : "", [resultView]);
  async function submit() { if (!active || Object.keys(answers).length !== active.questions.length) return setMessage("أجب عن جميع الأسئلة أولًا."); setSubmitting(true); try { const response = await fetch("/api/student/diagnostics", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${accessToken}` }, body: JSON.stringify({ diagnosticId: active.id, answers }) }); const data = await response.json(); if (!response.ok) return setMessage(data.message || "تعذر تسليم الاختبار."); setResultView({ title: active.title, result: data.result }); setActive(null); setAnswers({}); setMessage("تم تسليم الاختبار وحساب خطتك العلاجية."); await load(false); } finally { setSubmitting(false); } }
  return <section className="student-diagnostics"><div className="student-section-title"><h2>الاختبارات التشخيصية</h2><p>الاختبار والنتيجة والخطة العلاجية في مكان واحد.</p></div>{message && <p className="student-diagnostic-message" role="status">{message}</p>}<div className={`diagnostic-workspace ${resultView ? "has-result" : ""}`}><div className="diagnostic-tests">{loading ? <p>جارٍ تحميل الاختبارات…</p> : !items.length ? <p>لا توجد اختبارات منشورة لهذه المادة حاليًا.</p> : items.map(item => <article key={item.id}><div><strong>{item.title}</strong><small>{item.questionCount} أسئلة • {item.completed ? "تم الأداء" : "متاح الآن"}</small></div>{item.completed && item.result ? <button className="result-button" onClick={() => setResultView({ title: item.title, result: item.result! })}>عرض النتيجة والخطة</button> : <button onClick={() => { setActive(item); setAnswers({}); setMessage(""); }}>بدء الاختبار</button>}</article>)}</div>{resultView && <aside className="diagnostic-result-panel"><header><span>✦ تحليل ذكي</span><small>{resultView.title}</small></header><div className="result-score"><strong>{resultView.result.percentage}٪</strong><span>{resultView.result.score} من {resultView.result.total}</span></div><section><h3>رسالتك التحفيزية</h3><p>{motivation}</p></section><section><h3>الخطة العلاجية</h3><p>{resultView.result.plan}</p></section><section><h3>نصيحة الذكاء الاصطناعي</h3><p>{smartAdvice(resultView.result)}</p></section>{resultView.result.weakSkills.length > 0 && <div className="weak-skills"><b>مهارات تحتاج مراجعة</b>{resultView.result.weakSkills.map(skill => <span key={skill}>{skill}</span>)}</div>}</aside>}</div>
    {active && <div className="diagnostic-modal" role="dialog" aria-modal="true"><section><header><div><small>اختبار تشخيصي</small><h2>{active.title}</h2><p>{active.instructions}</p></div><button onClick={() => setActive(null)}>إغلاق</button></header><div className="diagnostic-progress"><span style={{ width: `${progress}%` }} /><b>{progress}٪ مكتمل</b></div>{active.questions.map((question, index) => <fieldset key={question.id}><legend>{index + 1}. {question.text}</legend>{question.options.map((option, optionIndex) => <label key={optionIndex} className={answers[question.id] === optionIndex ? "selected" : ""}><input type="radio" name={question.id} checked={answers[question.id] === optionIndex} onChange={() => setAnswers(current => ({ ...current, [question.id]: optionIndex }))} /><span>{option}</span></label>)}</fieldset>)}<button className="submit-diagnostic" disabled={submitting} onClick={submit}>{submitting ? "جارٍ التصحيح…" : "تسليم الاختبار وإظهار الخطة"}</button></section></div>}
  </section>;
}
