"use client";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {usePathname} from "next/navigation";

const nav=[{href:"/admin",label:"نظرة عامة",icon:"⌂"},{href:"/admin/students",label:"الطلاب والفصول",icon:"◎"},{href:"/admin/teachers",label:"المعلمون والإسناد",icon:"◇"},{href:"/admin/competition",label:"ساحة التنافس",icon:"✦"}];
export default function AdminLayout({children}:{children:React.ReactNode}){const pathname=usePathname();const[authenticated,setAuthenticated]=useState<boolean|null>(null);useEffect(()=>{let live=true;setAuthenticated(null);fetch("/api/auth/admin-session",{cache:"no-store",credentials:"same-origin"}).then(r=>{if(live)setAuthenticated(r.ok)}).catch(()=>{if(live)setAuthenticated(false)});return()=>{live=false}},[pathname]);if(pathname==="/admin"&&authenticated!==true)return <>{children}</>;if(authenticated!==true)return <main className="a26-gate" dir="rtl"><Image src="/icons/lahooni-identity-320.jpg" alt="بوابة أستاذ لحوني التعليمية" width={76} height={76}/><b>بوابة الإدارة</b><span>جارٍ تجهيز مساحة الإدارة…</span></main>;const current=nav.findLast?.(x=>pathname.startsWith(x.href))||nav[0];async function logout(){await fetch("/api/auth/logout",{method:"POST",cache:"no-store"}).catch(()=>undefined);window.location.assign("/admin")}return <div className="a26" dir="rtl"><style>{`
.a26{--n:#082f49;--t:#0f9f98;min-height:100dvh;display:grid;grid-template-columns:280px minmax(0,1fr);background:#edf4f7;color:#102f40}.a26 *{box-sizing:border-box}.a26-side{height:100dvh;position:sticky;top:0;padding:22px 16px;display:flex;flex-direction:column;background:linear-gradient(180deg,#062c42,#083d55);color:white}.a26-brand{display:flex;gap:12px;align-items:center;padding:5px 5px 22px;border-bottom:1px solid rgba(255,255,255,.12)}.a26-brand img{border-radius:17px;background:#fff;padding:3px}.a26-brand small,.a26-user small{display:block;color:#a8ced8;font-size:10px;font-weight:700}.a26-brand strong{display:block;margin-top:3px;font-size:15px}.a26-nav{display:grid;gap:7px;margin-top:22px}.a26-nav a{min-height:51px;display:flex;align-items:center;gap:12px;padding:0 13px;border-radius:15px;color:#d8e8ed;text-decoration:none;font-size:13px;font-weight:800}.a26-nav a.active{background:white;color:#082f49;box-shadow:0 12px 26px rgba(0,0,0,.15)}.a26-nav i{width:30px;height:30px;display:grid;place-items:center;border-radius:10px;background:rgba(255,255,255,.09);font-style:normal;font-size:18px}.a26-nav a.active i{background:#e6f5f3;color:#0b827b}.a26-user{margin-top:auto;padding:15px;border:1px solid rgba(255,255,255,.12);border-radius:17px;background:rgba(255,255,255,.06)}.a26-user b{display:block;font-size:12px;margin:4px 0 10px}.a26-user button{width:100%;border:0;border-radius:11px;padding:9px;background:#fff;color:#082f49;font-weight:800;cursor:pointer}.a26-main{min-width:0;padding:20px 24px 40px}.a26-head{min-height:126px;padding:24px 28px;display:flex;align-items:center;justify-content:space-between;gap:18px;border-radius:27px;background:#fff;border:1px solid #d8e5eb;box-shadow:0 14px 38px rgba(8,47,73,.07)}.a26-head small{font-size:11px;color:#0b827b;font-weight:900}.a26-head h1{margin:5px 0 5px;color:#082f49;font-size:30px}.a26-head p{margin:0;color:#6c818c;font-size:12px}.a26-mark{padding:11px 14px;border-radius:14px;background:#e8f5f4;color:#0b7771;font-size:11px;font-weight:900}.a26-work{padding-top:17px}.a26-gate{min-height:100dvh;display:grid;place-content:center;justify-items:center;gap:9px;background:#edf4f7;color:#082f49}.a26-gate img{border-radius:20px}.a26-gate span{font-size:12px;color:#6c818c}@media(max-width:850px){.a26{grid-template-columns:1fr}.a26-side{height:auto;position:relative;padding:11px}.a26-brand{padding:3px 3px 10px}.a26-brand img{width:45px;height:45px}.a26-nav{display:flex;overflow-x:auto;margin-top:10px}.a26-nav a{flex:0 0 auto;min-height:43px}.a26-user{display:none}.a26-main{padding:10px 10px 28px}.a26-head{min-height:110px;padding:19px;border-radius:21px}.a26-head h1{font-size:24px}.a26-mark{display:none}}
`}</style><aside className="a26-side"><div className="a26-brand"><Image src="/icons/lahooni-identity-320.jpg" alt="هوية البوابة" width={58} height={58}/><div><small>مركز الإدارة المدرسية</small><strong>أستاذ لحوني التعليمية</strong></div></div><nav className="a26-nav">{nav.map(x=>{const active=x.href==="/admin"?pathname==="/admin":pathname.startsWith(x.href);return <Link key={x.href} href={x.href} className={active?"active":""}><i>{x.icon}</i>{x.label}</Link>})}</nav><div className="a26-user"><small>مدير البوابة</small><b>الأستاذ حسن علي الطويل</b><button onClick={logout}>تسجيل الخروج</button></div></aside><section className="a26-main"><header className="a26-head"><div><small>لوحة التحكم الموحدة</small><h1>{current.label}</h1><p>إدارة المدرسة والبيانات الأكاديمية من مساحة واحدة مترابطة.</p></div><span className="a26-mark">النظام الإداري • متصل</span></header><main className="a26-work">{children}</main></section></div>}
