"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
type Assignment={id?:string;subjectId:string;grade:string;section:string;label?:string};
type Teacher={id:string;name:string;active:boolean;subjectIds:string[];assignments:Assignment[]};
const SUBJECTS=[["quran-tafsir","القرآن والتفسير"],["digital-technology","التقنية الرقمية"],["critical-thinking","التفكير الناقد"],["islamic-studies","الدراسات الإسلامية"],["arabic","اللغة العربية"],["social-sciences","العلوم الاجتماعية"],["environmental-science","علوم البيئة"],["mathematics","الرياضيات"],["english","اللغة الإنجليزية"],["physics","الفيزياء"],["chemistry","الكيمياء"],["biology","علم الأحياء"],["fitness-health","اللياقة والثقافة الصحية"],["tawhid","التوحيد"],["arts","الفنون"],["history","التاريخ"],["linguistic-competencies","الكفايات اللغوية"]] as const;
const GRADES=["الأول الثانوي","الثاني الثانوي","الثالث الثانوي"] as const;
const SECTIONS=["الكل","١","٢","٣","٤","٥","٦","٧","٨"] as const;
const emptyAssignment=():Assignment=>({subjectId:"",grade:"",section:""});
function AssignmentEditor({rows,setRows}:{rows:Assignment[];setRows:(rows:Assignment[])=>void}){
 const update=(i:number,key:keyof Assignment,value:string)=>setRows(rows.map((row,n)=>n===i?{...row,[key]:value}:row));
 return <fieldset><legend>المواد والصفوف والفصول</legend><div className="v3-assignment-list">{rows.map((row,i)=><div className="v3-assignment-row" key={i}><label>المادة<select value={row.subjectId} onChange={e=>update(i,"subjectId",e.target.value)} required><option value="">اختر المادة</option>{SUBJECTS.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label><label>الصف الدراسي<select value={row.grade} onChange={e=>update(i,"grade",e.target.value)} required><option value="">اختر الصف</option>{GRADES.map(grade=><option key={grade}>{grade}</option>)}</select></label><label>الفصل<select value={row.section} onChange={e=>update(i,"section",e.target.value)} required><option value="">اختر الفصل</option>{SECTIONS.map(section=><option key={section}>{section}</option>)}</select></label>{rows.length>1&&<button type="button" className="v3-remove-assignment" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>حذف</button>}</div>)}</div><button type="button" className="v3-add-assignment" onClick={()=>setRows([...rows,emptyAssignment()])}>+ إضافة مادة أو فصل آخر</button></fieldset>;
}
export default function AdminPage(){
 const[teachers,setTeachers]=useState<Teacher[]>([]),[authenticated,setAuthenticated]=useState<boolean|null>(null),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[name,setName]=useState(""),[teacherPassword,setTeacherPassword]=useState(""),[assignments,setAssignments]=useState<Assignment[]>([emptyAssignment()]),[editing,setEditing]=useState<Teacher|null>(null),[resetPassword,setResetPassword]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const r=await fetch("/api/admin/teachers",{cache:"no-store"});if(r.status===401)return setAuthenticated(false);const d=await r.json();setTeachers(d.teachers||[]);setAuthenticated(true)},[]);useEffect(()=>{void load()},[load]);
 async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});const d=await r.json();setBusy(false);if(!r.ok||d.role!=="admin")return setMessage(d.message||"بيانات الدخول غير صحيحة");setPassword("");await load()}
 async function createTeacher(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const r=await fetch("/api/admin/teachers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,password:teacherPassword,assignments})});const d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.message||"تعذر إضافة المعلم");setName("");setTeacherPassword("");setAssignments([emptyAssignment()]);setMessage("تمت إضافة المعلم وربط مواده وصفوفه بنجاح");await load()}
 async function saveTeacher(){if(!editing)return;setBusy(true);const r=await fetch(`/api/admin/teachers/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:editing.name,assignments:editing.assignments,password:resetPassword||undefined})});const d=await r.json();setBusy(false);if(!r.ok)return setMessage(d.message||"تعذر حفظ التعديل");setEditing(null);setResetPassword("");setMessage("تم تحديث حساب المعلم");await load()}
 async function toggle(t:Teacher){await fetch(`/api/admin/teachers/${t.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({active:!t.active})});await load()}
 async function remove(t:Teacher){if(!confirm(`حذف حساب ${t.name}؟`))return;const r=await fetch(`/api/admin/teachers/${t.id}`,{method:"DELETE"});if(!r.ok)return setMessage("تعذر حذف الحساب");setMessage("تم حذف حساب المعلم");await load()}
 const subjectLabel=(id:string)=>SUBJECTS.find(([key])=>key===id)?.[1]||id;
 const assignmentLabel=(a:Assignment)=>a.label||`${subjectLabel(a.subjectId)} — ${a.grade}${a.section?` — ${a.section==="الكل"?"جميع الفصول":`فصل ${a.section}`}`:""}`;
 if(authenticated===null)return <main className="v3-loading">جارٍ تجهيز إدارة البوابة…</main>;
 if(!authenticated)return <main className="v3-login v3-admin-login" dir="rtl"><section className="v3-login-card"><Link href="/" className="v3-back">← العودة إلى البوابة الرئيسية</Link><span className="v3-login-icon">◈</span><small>هوية الإدارة</small><h1>دخول إدارة البوابة</h1><p>أدخل اسم المدير والرقم السري للوصول إلى الحسابات والصلاحيات.</p><form onSubmit={login}><label>اسم المدير<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>الرقم السري<div className="v3-password"><input type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><button type="button" onClick={()=>setShowPassword(!showPassword)}>{showPassword?"إخفاء":"إظهار"}</button></div></label>{message&&<p className="v3-error">{message}</p>}<button className="v3-primary" disabled={busy}>{busy?"جارٍ التحقق…":"دخول الإدارة"}</button></form><div className="v3-recovery"><span>نسيت اسم الدخول أو الرقم السري؟</span><a href="mailto:Hasan2016@outlook.com?subject=استعادة حساب إدارة بوابة أستاذ لحوني">استرداد الحساب بالبريد</a><small>Hasan2016@outlook.com</small></div></section><aside><b>إدارة مركزية واضحة</b><h2>المعلمون والمواد<br/>في مكان واحد</h2><p>أنشئ حساب المعلم وحدد المادة والصف والفصل لكل تكليف.</p></aside></main>;
 return <main className="v3-admin" dir="rtl"><header><div><small>لوحة التحكم المركزية</small><h1>إدارة بوابة أستاذ لحوني</h1><p>إضافة المعلمين وتحديد المادة والصف والفصل لكل تكليف.</p></div><Link href="/">العودة إلى البوابة الرئيسية</Link></header><section className="v3-stats"><article><strong>{teachers.length}</strong><span>معلم</span></article><article><strong>{teachers.filter(x=>x.active).length}</strong><span>حساب مفعل</span></article><article><strong>{teachers.reduce((sum,t)=>sum+t.assignments.length,0)}</strong><span>تكليف دراسي</span></article></section><div className="v3-admin-grid"><form className="v3-panel v3-create-teacher" onSubmit={createTeacher}><small>حساب جديد</small><h2>إضافة معلم</h2><p>اسم المعلم نفسه هو اسم الدخول.</p><label>اسم المعلم<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: حسن علي الطويل" required/></label><label>الرقم السري<input type="password" value={teacherPassword} onChange={e=>setTeacherPassword(e.target.value)} minLength={8} required/></label><AssignmentEditor rows={assignments} setRows={setAssignments}/>{message&&<p className="v3-notice">{message}</p>}<button className="v3-primary" disabled={busy}>{busy?"جارٍ الإضافة…":"إضافة المعلم"}</button></form><section className="v3-panel v3-teachers"><small>الحسابات الحالية</small><h2>المعلمون</h2>{!teachers.length&&<p className="v3-empty">لم تتم إضافة معلمين بعد.</p>}<div className="v3-teacher-list">{teachers.map(t=><article key={t.id}><span className="v3-avatar">{t.name.trim().charAt(0)||"م"}</span><div><strong>{t.name}</strong><p>{t.assignments.map(assignmentLabel).join(" • ")||"لا توجد مواد"}</p><small className={t.active?"active":"inactive"}>{t.active?"حساب مفعل":"حساب متوقف"}</small></div><div className="v3-row-actions"><button onClick={()=>{setEditing({...t,assignments:t.assignments.length?t.assignments:[emptyAssignment()]});setResetPassword("")}}>تعديل</button><button onClick={()=>toggle(t)}>{t.active?"إيقاف":"تفعيل"}</button><button className="danger" onClick={()=>remove(t)}>حذف</button></div></article>)}</div></section></div>{editing&&<div className="v3-modal" role="dialog" aria-modal="true"><section><header><div><small>إدارة الحساب</small><h2>تعديل {editing.name}</h2></div><button onClick={()=>setEditing(null)}>×</button></header><label>اسم المعلم<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>رقم سري جديد <small>اختياري</small><input type="password" minLength={8} value={resetPassword} onChange={e=>setResetPassword(e.target.value)}/></label><AssignmentEditor rows={editing.assignments} setRows={rows=>setEditing({...editing,assignments:rows})}/><div className="v3-modal-actions"><button onClick={()=>setEditing(null)}>إلغاء</button><button className="v3-primary" onClick={saveTeacher} disabled={busy}>حفظ التعديلات</button></div></section></div>}</main>;
}
