"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import "./teacher-activity-leaderboard-v4.css";
import "./admin-experience-v15.css";

type Counts = Record<string, number>;
type ActivityRow = { teacherId:string; teacherName:string; active:boolean; accountCreatedAt:string; score:number; meaningfulActions:number; activeDays:number; diversity:number; counts:Counts; firstActivityAt:string; lastActivityAt:string; dataComplete:boolean; readFailureCount:number; rank:number };
type ActivityResponse = { ok?:boolean; period?:string; rows?:ActivityRow[]; rule?:string; generatedAt?:string; coverageStartAt?:string; totalTeachers?:number; activeTeachers?:number; inactiveTeachers?:number; readFailureCount?:number; integrity?:"verified"|"partial"; message?:string };
const LABELS:Array<[string,string]>=[["attendance","تحضير"],["grades","رصد"],["note","ملاحظات"],["diagnostic","اختبارات"],["remedial","خطط علاجية"],["referral","دفعات إحالة"],["timetable","جدول"],["gradePlan","خطة دراسية"]];
const ar=(value:number)=>new Intl.NumberFormat("ar-SA-u-nu-arab").format(value||0);
function dateLabel(value?:string){if(!value)return"غير محدد";const date=new Date(value);if(Number.isNaN(date.getTime()))return"غير محدد";return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeZone:"Asia/Riyadh"}).format(date)}
function timeLabel(value?:string){if(!value)return"";const date=new Date(value);if(Number.isNaN(date.getTime()))return"";return new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Riyadh"}).format(date)}
function topCategory(row:ActivityRow){const best=LABELS.map(([key,label])=>({label,count:Number(row.counts?.[key]||0)})).sort((a,b)=>b.count-a.count)[0];return best?.count?`${best.label} ${ar(best.count)}`:"لا توجد أعمال محفوظة بعد"}
export default function TeacherActivityLeaderboard(){
 const[rows,setRows]=useState<ActivityRow[]>([]);const[meta,setMeta]=useState<ActivityResponse>({});const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=useCallback(async(force=false)=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/teacher-activity${force?"?refresh=1":""}`,{cache:"no-store"});const data=await response.json().catch(()=>({})) as ActivityResponse;if(!response.ok)throw new Error(data.message||"تعذر حساب التنافس الآن");setRows(Array.isArray(data.rows)?data.rows:[]);setMeta(data)}catch(reason){setError(reason instanceof Error?reason.message:"تعذر تحميل التنافس")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load(false)},[load]);
 const topThree=useMemo(()=>rows.slice(0,3),[rows]);const rest=useMemo(()=>rows.slice(3),[rows]);const leaderScore=Math.max(1,rows[0]?.score||0);const completeRows=rows.filter(row=>row.dataComplete).length;
 return <section className="race4" id="competition" aria-label="التنافس الموثق بين جميع المعلمين">
  <header className="race4-head"><div><small>{meta.period||"منذ تأسيس البوابة"}</small><h2>المسابقة التنافسية بين المعلمين</h2><p>ترتيب مباشر مبني على الأعمال الموثقة داخل البوابة، مع أيام النشاط وتنوع العمل.</p></div><button type="button" onClick={()=>void load(true)} disabled={loading}>{loading?"جارٍ التحقق…":"تحديث الترتيب"}</button></header>
  {!!rows.length&&<div className="race4-summary"><article><small>المعلمون</small><strong>{ar(meta.totalTeachers??rows.length)}</strong><span>ضمن التصنيف</span></article><article><small>الحسابات النشطة</small><strong>{ar(meta.activeTeachers??rows.filter(row=>row.active).length)}</strong><span>{meta.inactiveTeachers?`${ar(meta.inactiveTeachers)} متوقف`:"جميعها نشطة"}</span></article><article><small>بداية التغطية</small><strong className="date-value">{dateLabel(meta.coverageStartAt)}</strong><span>من البيانات المحفوظة</span></article><article className={meta.integrity==="partial"?"warning":"verified"}><small>سلامة القراءة</small><strong>{meta.integrity==="partial"?"تحتاج مراجعة":"مكتملة"}</strong><span>{meta.integrity==="partial"?`${ar(meta.readFailureCount||0)} مصدر متعذر`:`${ar(completeRows)} من ${ar(rows.length)}`}</span></article></div>}
  {error?<div className="race4-empty">{error}</div>:loading&&!rows.length?<div className="race4-empty">جارٍ احتساب التنافس من الأعمال المحفوظة…</div>:!rows.length?<div className="race4-empty">لا توجد حسابات معلمين مسجلة حاليًا.</div>:<><div className="race4-podium">{topThree.map(row=><article key={row.teacherId} className={`race4-podium-card place-${row.rank}`}><div className="race4-medal">{ar(row.rank)}</div><div className="race4-avatar">{row.teacherName.trim().charAt(0)||"م"}</div><div className="race4-account-state"><i className={row.active?"on":"off"}/>{row.active?"حساب نشط":"حساب متوقف"}</div><h3>{row.teacherName}</h3><strong>{ar(row.meaningfulActions)}<small>عمل موثق</small></strong><p>{ar(row.activeDays)} أيام نشاط • {ar(row.diversity)} أنواع عمل</p><span>{topCategory(row)}</span><div className="race4-meter"><i style={{width:`${Math.max(7,Math.round(row.score/leaderScore*100))}%`}}/></div></article>)}</div>{!!rest.length&&<div className="race4-board"><header className="race4-board-head"><b>بقية الترتيب</b><span>{ar(rest.length)} معلمًا</span></header>{rest.map(row=><article key={row.teacherId}><b className="race4-rank">{ar(row.rank)}</b><div className="race4-name"><strong>{row.teacherName}</strong><small>{row.active?"نشط":"متوقف"} • {ar(row.meaningfulActions)} عمل • آخر نشاط {row.lastActivityAt?timeLabel(row.lastActivityAt):"غير متوفر"}</small></div><div className="race4-chips">{LABELS.filter(([key])=>Number(row.counts?.[key]||0)>0).slice(0,4).map(([key,label])=><span key={key}>{label} {ar(Number(row.counts[key]||0))}</span>)}</div><div className="race4-score-wrap"><strong className="race4-score">{ar(row.meaningfulActions)}<small>عمل</small></strong></div></article>)}</div>}</>}
 </section>;
}