"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useTeacherClient} from "../../../../lib/teacher-client";

type Student={code:string;name:string;className:string};
type Row={name:string;score:number|null;percent:number|null;status:string;student:Student|null};
type FileResult={file:string;extracted:number;matched:number;unmatched:number;rows:Row[]};
export default function ClasseraPreview(){
 const session=useTeacherClient(); const [students,setStudents]=useState<Student[]>([]); const [files,setFiles]=useState<File[]>([]); const [result,setResult]=useState<FileResult[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{if(!session.subjectKey)return;const p=new URLSearchParams({subjectId:session.subjectKey});if(session.activeGrade)p.set("grade",String(session.activeGrade));fetch(`/api/teacher/students?${p}`).then(r=>r.json()).then(d=>setStudents((Array.isArray(d.students)?d.students:[]).map((x:any)=>({code:String(x.code||x.id||"").trim().toUpperCase(),name:String(x.name||"").trim(),className:String(x.className||x.class||"").trim()})).filter((x:Student)=>x.code&&x.name))).catch(()=>setMessage("تعذر تحميل الطلاب"))},[session.subjectKey,session.activeGrade]);
 async function analyze(){if(!files.length||!session.subjectKey)return;setBusy(true);setMessage("");setResult([]);try{const fd=new FormData();fd.set("subjectId",session.subjectKey);fd.set("roster",JSON.stringify(students));files.forEach(f=>fd.append("files",f));const r=await fetch("/api/teacher/classera-preview",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.message||"تعذر التحليل");setResult(d.files||[])}catch(e){setMessage(e instanceof Error?e.message:"تعذر التحليل")}finally{setBusy(false)}}
 return <main dir="rtl" style={{maxWidth:1100,margin:"24px auto",padding:16,fontFamily:"inherit"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h1 style={{margin:0}}>اختبار قراءة كلاسيرا</h1><p>معاينة فقط — لا يتم حفظ أو تعديل أي درجة.</p></div><Link href="/teacher/grades">العودة للتحصيل العلمي</Link></div><div style={{padding:16,border:"1px solid #ddd",borderRadius:14}}><input type="file" accept="application/pdf,.pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><button onClick={analyze} disabled={busy||!files.length} style={{marginRight:12,padding:"8px 18px"}}>{busy?"جاري القراءة...":"تحليل الملفات"}</button><span style={{marginRight:12}}>طلاب المادة: {students.length}</span></div>{message&&<p>{message}</p>}{result.map((f,i)=><section key={i} style={{marginTop:20}}><h2>{f.file}</h2><p>المستخرج: <b>{f.extracted}</b> — المطابق: <b>{f.matched}</b> — يحتاج مراجعة: <b>{f.unmatched}</b></p><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th>اسم كلاسيرا</th><th>الدرجة</th><th>النسبة</th><th>المطابقة</th><th>اسم البوابة</th></tr></thead><tbody>{f.rows.map((r,j)=><tr key={j} style={{background:r.status==="matched"?undefined:"#fff4e5"}}><td>{r.name}</td><td>{r.score??"—"}</td><td>{r.percent==null?"—":`${r.percent}%`}</td><td>{r.status==="matched"?"✓ مطابق":r.status==="ambiguous"?"⚠ متعدد":"⚠ غير مطابق"}</td><td>{r.student?.name||"—"}</td></tr>)}</tbody></table></div></section>)}</main>
}
