"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { signInWithCustomToken } from "firebase/auth";
import { auth } from "../../lib/firebase";
export default function TeacherLoginPage(){
 const[name,setName]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(false);const router=useRouter();
 async function submit(e:FormEvent){e.preventDefault();setError("");setLoading(true);try{const r=await fetch("/api/teacher-login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,password})});const d=await r.json();if(!r.ok)return setError(d?.message||"اسم المعلم أو الرقم السري غير صحيح");if(d?.firebaseToken)await signInWithCustomToken(auth,d.firebaseToken);let destination="/teacher/dashboard";try{const p=await fetch("/api/teacher/grade-plan",{cache:"no-store",credentials:"same-origin"});const plan=await p.json().catch(()=>({}));if(p.ok&&!Boolean(plan?.activePlan||plan?.hasActivePlan))destination="/teacher/grade-plan?setup=1"}catch{}router.replace(destination);router.refresh()}catch{setError("تعذر تسجيل الدخول الآن")}finally{setLoading(false)}}
 return <main className="v3-login v3-teacher-login" dir="rtl"><section className="v3-login-card"><Link href="/" className="v3-back">← العودة إلى البوابة الرئيسية</Link><span className="v3-login-icon">✦</span><small>هوية المعلم</small><h1>دخول بوابة المعلم</h1><p>استخدم الاسم والرقم السري اللذين أنشأهما مدير البوابة.</p><form onSubmit={submit}><label>اسم المعلم<input value={name} onChange={e=>{setName(e.target.value);setError("")}} autoComplete="username" autoFocus required placeholder="اكتب اسم المعلم"/></label><label>الرقم السري<div className="v3-password"><input type={show?"text":"password"} value={password} onChange={e=>{setPassword(e.target.value);setError("")}} autoComplete="current-password" required/><button type="button" onClick={()=>setShow(!show)}>{show?"إخفاء":"إظهار"}</button></div></label>{error&&<p className="v3-error">{error}</p>}<button className="v3-primary" disabled={loading||!name||!password}>{loading?"جارٍ التحقق…":"دخول بوابة المعلم"}</button></form><p className="v3-login-note">المواد وصلاحيات الحساب يحددها مدير البوابة فقط.</p></section><aside><b>مساحة عمل المعلم</b><h2>أدواتك التعليمية<br/>بوضوح وهدوء</h2><p>إدارة الطلاب والدرجات والحضور وملف الإنجاز والذكاء الاصطناعي في مساحة واحدة.</p></aside></main>;
}
