"use client";
import Link from "next/link";

const stages = [
  { href: "/admin/students?stage=middle", kind: "middle", icon: "📖", title: "المرحلة المتوسطة", short: "المتوسطة", grades: ["الأول المتوسط", "الثاني المتوسط", "الثالث المتوسط"] },
  { href: "/admin/students?stage=secondary", kind: "secondary", icon: "🎓", title: "المرحلة الثانوية", short: "الثانوية", grades: ["الأول الثانوي", "الثاني الثانوي", "الثالث الثانوي"] }
] as const;

export default function Page() {
  return <main className="schoolStagePage" dir="rtl">
    <nav className="ssNav"><div className="ssBrand"><span className="ssHome">⌂</span><div><strong>بوابة أستاذ لحوني التعليمية</strong><small>لوحة إدارة الطلاب والفصول</small></div></div><Link href="/admin" prefetch={false} className="ssBack">العودة للوحة الإدارة <span>←</span></Link></nav>
    <header className="ssHero"><div className="ssHeroText"><span className="ssPill">الطلاب والفصول</span><h1>إدارة المراحل التعليمية</h1><p>اختر المرحلة للدخول إلى مساحات إدارتها المستقلة.</p></div><div className="ssBooks" aria-hidden="true"><div>تخطيط</div><div>تنظيم</div><div>إنجاز</div></div></header>
    <div className="ssContent"><section className="ssCards" aria-label="المراحل التعليمية">{stages.map(stage => <article key={stage.kind} className={`ssCard ${stage.kind}`}><div className="ssCardHead"><div className="ssCardHeading"><h2>{stage.title}</h2><p>إدارة الطلاب والفصول والسجلات</p></div><span className="ssStageIcon" aria-hidden="true">{stage.icon}</span><div className="ssCount"><strong>٣</strong><small>صفوف دراسية</small></div></div><div className="ssGrades">{stage.grades.map((grade,index) => <div className="ssGrade" key={grade}><span className="ssGradeIcon">▱</span><b>{grade}</b><span className="ssGradeNum">{index+1}</span></div>)}</div><Link href={stage.href} prefetch={false} className="ssEnter"><span>فتح مساحة إدارة المرحلة {stage.short}</span><span aria-hidden="true">←</span></Link></article>)}</section>
    <aside className="ssNotice"><span className="ssCheck">✓</span><div><strong>المرحلتان منفصلتان بالكامل</strong><p>لا مشاركة للطلاب أو الفصول أو السجلات بين المتوسطة والثانوية.</p></div><span className="ssNoticeIcon" aria-hidden="true">▣</span></aside></div>
    <style jsx>{`
    .schoolStagePage,.schoolStagePage *{box-sizing:border-box}.schoolStagePage{font-family:"Tajawal",Tahoma,Arial,sans-serif;min-height:100dvh;color:#093b4b;background:#f1f9fc;overflow-x:clip}
    .ssNav{height:87px;background:linear-gradient(100deg,#063b49,#062f3b);border-bottom:4px solid #eeb94e;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:0 max(24px,calc((100vw - 1390px)/2));color:#fff}
    .ssBrand{display:flex;align-items:center;gap:17px}.ssHome{display:grid;place-items:center;width:57px;height:57px;border-radius:17px;background:linear-gradient(135deg,#f5b83d,#ffe19a);color:#064c64;font-size:40px;font-weight:950}.ssBrand strong,.ssBrand small{display:block}.ssBrand strong{font-size:20px;font-weight:950}.ssBrand small{font-size:13px;color:#bad5df;margin-top:3px}.ssBack{display:inline-flex;align-items:center;gap:10px;color:#ffd16c!important;font-size:14px;font-weight:850;text-decoration:none!important;border-bottom:1px solid #d5b66a;padding-bottom:6px}.ssBack span{font-size:22px}
    .ssHero{position:relative;min-height:248px;display:flex;align-items:center;justify-content:center;overflow:hidden;padding:28px 210px;background:radial-gradient(ellipse at 50% 40%,#d9f4ff 0%,#e9f9ff 43%,#d5eaf1 100%);border-bottom:1px solid #c4e5ef}
    .ssHero:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 7% 75%,#f3c77766,transparent 23%),radial-gradient(circle at 92% 60%,#a5d6dd9c,transparent 30%);pointer-events:none}
    .ssHero:after{content:"";position:absolute;inset:auto -4% -43px;width:108%;height:82px;border-radius:50% 50% 0 0;background:linear-gradient(90deg,#d1eefa,#f4faff,#c4f0e9);opacity:.7}
    .ssHeroText{position:relative;z-index:1;text-align:center}.ssPill{display:inline-block;padding:7px 21px;border-radius:30px;border:2px solid #fff;background:#ffce64;color:#073c50;font-size:13px;font-weight:950}.ssHero h1{margin:15px 0 5px;color:#063d4c;font-size:clamp(29px,3.4vw,49px);line-height:1.35;font-weight:950}.ssHero p{margin:0;color:#607f8a;font-size:16px}.ssBooks{position:absolute;z-index:1;left:5%;bottom:26px;transform:rotate(-5deg);display:grid;gap:4px}.ssBooks div{min-width:160px;text-align:center;padding:7px 17px;border:2px solid #ffffffa8;border-radius:7px;color:#083e54;font-size:16px;font-weight:900;box-shadow:4px 7px 13px #123a4426}.ssBooks div:nth-child(1){background:#45a5d6}.ssBooks div:nth-child(2){background:#ffd17d}.ssBooks div:nth-child(3){background:#6cbd8d}
    .ssContent{width:min(1450px,calc(100% - 48px));margin:-4px auto 0;position:relative;z-index:2}.ssCards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:23px}.ssCard{border-radius:24px;padding:5px;border:2px solid white;box-shadow:0 13px 32px #163b5b22;min-width:0}.ssCard.middle{background:linear-gradient(140deg,#d7f0ff,#f1faff)}.ssCard.secondary{background:linear-gradient(140deg,#eadbff,#fbf6ff)}
    .ssCardHead{position:relative;min-height:167px;padding:26px 24px;display:flex;flex-direction:column;justify-content:center;overflow:hidden;border-radius:19px 19px 0 0}.middle .ssCardHead{background:linear-gradient(115deg,#d0ebff,#eaf7ff)}.secondary .ssCardHead{background:linear-gradient(115deg,#ead8ff,#f7efff)}.ssCardHead:after{content:"";position:absolute;left:-20px;bottom:-45px;width:65%;height:110px;border-radius:50%;background:#ffffff50}.ssCardHeading{position:relative;z-index:1;max-width:72%}.ssCard h2{font-size:clamp(24px,2.6vw,38px);line-height:1.35;margin:0 0 8px;font-weight:950}.middle h2{color:#07528e}.secondary h2{color:#57208c}.ssCardHeading p{margin:0;color:#557182;font-size:14px}.ssStageIcon{position:absolute;top:23px;left:25px;font-size:45px;z-index:1}.ssCount{position:absolute;left:18px;bottom:13px;z-index:1;display:flex;flex-direction:column;align-items:center;justify-content:center;min-width:110px;padding:9px 15px;border:1px solid #fff;border-radius:15px;background:#ffffffdf;box-shadow:0 5px 12px #22527c13}.ssCount strong{font-size:28px;line-height:1;color:#0a578e}.secondary .ssCount strong{color:#6223a1}.ssCount small{font-size:11px;color:#52728b}
    .ssGrades{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:16px 12px}.ssGrade{min-height:126px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:12px 7px;border-radius:17px;border:1px solid #c7e2f5;background:#fff;box-shadow:0 5px 11px #144e7b0b;text-align:center}.secondary .ssGrade{border-color:#e4d0fb}.ssGradeIcon{font-size:24px;font-weight:950;line-height:1;color:#0c6aa2}.secondary .ssGradeIcon{color:#6b2bb1}.ssGrade b{font-size:13px;color:#123c62;line-height:1.5}.secondary .ssGrade b{color:#4d1e82}.ssGradeNum{display:grid;place-items:center;width:31px;height:31px;border-radius:10px;background:#0c659e;color:#fff;font-size:16px;font-weight:950}.secondary .ssGradeNum{background:#6325a3}
    .ssEnter{margin:0 13px 14px;min-height:62px;display:flex;align-items:center;justify-content:center;gap:22px;border-radius:16px;background:linear-gradient(100deg,#0872ac,#138fc3);color:#fff!important;text-decoration:none!important;font-size:16px;font-weight:950;box-shadow:0 8px 14px #13608e29;transition:transform .18s,filter .18s}.secondary .ssEnter{background:linear-gradient(100deg,#5923a3,#7a3dc1);box-shadow:0 8px 14px #5d2b8d29}.ssEnter:hover{transform:translateY(-2px);filter:brightness(1.08)}.ssEnter>span:last-child{font-size:25px}
    .ssNotice{margin:25px 0 0;display:flex;align-items:center;gap:16px;padding:19px 23px;border-radius:20px;border:1px solid #b7e5d9;background:linear-gradient(110deg,#e5f9f1,#f2fbfa);color:#0a4550}.ssCheck{display:grid;place-items:center;flex:none;width:47px;height:47px;border-radius:14px;background:#05b789;color:white;font-size:29px;font-weight:950}.ssNotice strong{font-size:17px;font-weight:950}.ssNotice p{margin:5px 0 0;font-size:13px;color:#52727d}.ssNoticeIcon{margin-right:auto;color:#18a87e;font-size:35px}
    @media(max-width:950px){.ssHero{padding-inline:100px}.ssBooks{left:2%;transform:scale(.7) rotate(-5deg);transform-origin:left bottom}.ssCardHead{min-height:150px;padding:20px}.ssGrades{gap:7px;padding:10px}.ssGrade b{font-size:11px}.ssEnter{font-size:13px}}
    @media(max-width:680px){.ssNav{padding:0 12px;height:72px}.ssHome{width:39px;height:39px;font-size:27px;border-radius:12px}.ssBrand{gap:8px}.ssBrand strong{font-size:12px}.ssBrand small{font-size:10px}.ssBack{font-size:10px;gap:4px}.ssHero{min-height:200px;padding:30px 12px 42px}.ssHero h1{font-size:30px}.ssHero p{font-size:12px}.ssBooks{display:none}.ssContent{width:calc(100% - 22px)}.ssCards{grid-template-columns:1fr;gap:15px}.ssCardHead{min-height:145px}.ssCard h2{font-size:26px}.ssStageIcon{font-size:35px}.ssGrade{min-height:100px;padding:8px 5px}.ssGrade b{font-size:10px}.ssGradeIcon{font-size:18px}.ssEnter{min-height:54px;font-size:13px}.ssNotice{margin-top:15px;padding:13px;gap:10px}.ssNotice strong{font-size:13px}.ssNotice p{font-size:11px}.ssNoticeIcon{display:none}}
    @media(max-width:350px){.ssBrand small{display:none}.ssGrades{grid-template-columns:1fr}.ssGrade{min-height:50px;flex-direction:row;justify-content:space-between;padding:7px 12px}.ssGrade b{font-size:12px}}
    @media(prefers-reduced-motion:reduce){.ssEnter{transition:none}}
    `}</style>
  </main>;
}
