import { NextResponse } from "next/server";
import { adminDb } from "../../../../lib/server/firebase-admin";
import { requireSession } from "../../../../lib/server/portal-auth";
import { recordTeacherWork } from "../../../../lib/server/teacher-work-activity";
import { SCHOOL_STUDENTS_COLLECTION } from "../../../../lib/school-roster";

type NoteEntry={id:string;type:string;label:string;message:string;createdAt:string;teacherName:string;subject:string};
type NotesRow={studentCode:string;studentName:string;className:string;notes:NoteEntry[]};
const READ_TTL=2*60*1000;
const notesCache=new Map<string,{at:number;rows:NotesRow[]}>();
const notesInflight=new Map<string,Promise<NotesRow[]>>();
function clean(value:unknown,limit=500){return String(value||"").replace(/\s+/g," ").trim().slice(0,limit)}
function normalizedCode(value:unknown){return clean(value,40).toUpperCase()}
function cacheKey(teacherId:string,subjectId:string){return `${teacherId}:${subjectId}`}
function invalidate(teacherId:string,subjectId:string){notesCache.delete(cacheKey(teacherId,subjectId))}
async function readRows(teacherId:string,subjectId:string){const key=cacheKey(teacherId,subjectId),cached=notesCache.get(key);if(cached&&Date.now()-cached.at<READ_TTL)return cached.rows;const pending=notesInflight.get(key);if(pending)return pending;const request=(async()=>{const snapshot=await adminDb().collection(`portalV2Data/${teacherId}/subjects/${subjectId}/students`).get();const rows=snapshot.docs.map(document=>{const data=document.data() as Record<string,unknown>;const notes=Array.isArray(data.teacherNotes)?data.teacherNotes as NoteEntry[]:[];return{studentCode:clean(data.code||data.accessCode||data.studentCode||document.id,40),studentName:clean(data.name,120),className:clean(data.className||data.class,80),notes:notes.slice().sort((a,b)=>String(b.createdAt||"").localeCompare(String(a.createdAt||"")))}}).filter(row=>row.studentCode&&row.studentName);notesCache.set(key,{at:Date.now(),rows});return rows})().finally(()=>notesInflight.delete(key));notesInflight.set(key,request);return request}
async function findOfficialStudent(code:string){const students=adminDb().collection(SCHOOL_STUDENTS_COLLECTION);const direct=await students.doc(code).get();if(direct.exists)return direct;for(const field of ["code","accessCode","studentCode"] as const){const snapshot=await students.where(field,"==",code).limit(1).get();if(!snapshot.empty)return snapshot.docs[0]!}return null}
async function findStudentDoc(teacherId:string,subjectId:string,code:string){const students=adminDb().collection(`portalV2Data/${teacherId}/subjects/${subjectId}/students`),directRef=students.doc(code),direct=await directRef.get();if(direct.exists)return{snapshot:direct,reference:directRef};for(const field of ["code","accessCode","studentCode"] as const){const snapshot=await students.where(field,"==",code).limit(1).get();if(!snapshot.empty){const found=snapshot.docs[0]!;return{snapshot:found,reference:students.doc(found.id)}}}const official=await findOfficialStudent(code);if(!official)return null;const data=official.data() as Record<string,unknown>,officialCode=normalizedCode(data.code||data.accessCode||data.studentCode||official.id);if(!officialCode||officialCode!==normalizedCode(code))return null;const reference=students.doc(officialCode),seed={code:officialCode,accessCode:clean(data.accessCode||officialCode,40),studentCode:clean(data.studentCode||officialCode,40),name:clean(data.name,120),className:clean(data.className||data.class,80),grade:data.grade??null,section:data.section??null,rosterActive:true,officialRoster:true,updatedAt:new Date().toISOString()};await reference.set(seed,{merge:true});const snapshot=await reference.get();return{snapshot,reference}}
export async function GET(request:Request){const session=await requireSession("teacher");if(!session)return NextResponse.json({ok:false},{status:401});const url=new URL(request.url),subjectId=clean(url.searchParams.get("subjectId"),80);if(!subjectId)return NextResponse.json({ok:true,rows:[]});try{const rows=await readRows(session.userId,subjectId);return NextResponse.json({ok:true,rows},{headers:{"Cache-Control":"private, max-age=60, stale-while-revalidate=120"}})}catch(error){console.error("teacher notes get failed",error);return NextResponse.json({ok:false,message:"تعذر تحميل الملاحظات."},{status:500})}}
export async function POST(request:Request){const session=await requireSession("teacher");if(!session)return NextResponse.json({ok:false},{status:401});try{const body=await request.json().catch(()=>({})),subjectId=clean(body.subjectId,80),studentCode=normalizedCode(body.studentCode),type=clean(body.type||"academic",40),label=clean(body.label||"ملاحظة المعلم",120),message=clean(body.message,600),subject=clean(body.subject||subjectId,100);if(!subjectId||!studentCode||message.length<3)return NextResponse.json({ok:false,message:"اختر الطالب واكتب الملاحظة."},{status:400});const student=await findStudentDoc(session.userId,subjectId,studentCode);if(!student)return NextResponse.json({ok:false,message:"تعذر العثور على سجل الطالب."},{status:404});const current=student.snapshot.data() as Record<string,unknown>,previous=Array.isArray(current.teacherNotes)?current.teacherNotes as NoteEntry[]:[],createdAt=new Date().toISOString(),id=`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`,entry:NoteEntry={id,type,label,message,createdAt,teacherName:session.name||"المعلم",subject},next=[entry,...previous].slice(0,100),counts=previous.reduce<Record<string,number>>((acc,note)=>{const key=String(note.type||"other");acc[key]=(acc[key]||0)+1;return acc},{});counts[type]=(counts[type]||0)+1;await student.reference.set({teacherNotes:next,teacherNote:message,teacherNoteCount:next.length,teacherNoteCounts:counts,teacherNoteUpdatedAt:createdAt,updatedAt:createdAt},{merge:true});invalidate(session.userId,subjectId);await recordTeacherWork({teacherId:session.userId,teacherName:session.name||"المعلم",kind:"note",signature:`${subjectId}|${studentCode}|${id}`,meta:{subjectId,studentCode,type}}).catch(()=>null);return NextResponse.json({ok:true,note:entry})}catch(error){console.error("teacher note create failed",error);return NextResponse.json({ok:false,message:"تعذر حفظ الملاحظة."},{status:500})}}
export async function DELETE(request:Request){const session=await requireSession("teacher");if(!session)return NextResponse.json({ok:false},{status:401});try{const body=await request.json().catch(()=>({})),subjectId=clean(body.subjectId,80),studentCode=normalizedCode(body.studentCode),noteId=clean(body.noteId,80),student=await findStudentDoc(session.userId,subjectId,studentCode);if(!student)return NextResponse.json({ok:false,message:"تعذر العثور على الطالب."},{status:404});const current=student.snapshot.data() as Record<string,unknown>,previous=Array.isArray(current.teacherNotes)?current.teacherNotes as NoteEntry[]:[],next=previous.filter(note=>String(note.id||"")!==noteId),counts=next.reduce<Record<string,number>>((acc,note)=>{const key=String(note.type||"other");acc[key]=(acc[key]||0)+1;return acc},{}),now=new Date().toISOString();await student.reference.set({teacherNotes:next,teacherNote:next[0]?.message||"",teacherNoteCount:next.length,teacherNoteCounts:counts,teacherNoteUpdatedAt:now,updatedAt:now},{merge:true});invalidate(session.userId,subjectId);return NextResponse.json({ok:true})}catch(error){console.error("teacher note delete failed",error);return NextResponse.json({ok:false,message:"تعذر حذف الملاحظة."},{status:500})}}
