"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useTeacherClient} from "../../../../lib/teacher-client";
import {useGradePlan} from "../../../../lib/use-grade-plan";
import {gradeEntryKey,readGradeEntry,type GradePlanItem,type GradeValueMap} from "../../../../lib/grade-plan";

type Student={id:string;code:string;name:string;className:string;gradeValues?:GradeValueMap;gradePlanValues?:Record<string,GradeValueMap>};
export default function HomeworkQuick(){
 const session=useTeacherClient();const{activePlan,loading:planLoading}=useGradePlan(true);
 const[students,setStudents]=useState<Student[]>([]),[selectedClass,setSelectedClass]=useState(""),[sectionId,setSectionId]=useState(""),[itemId,setItemId]=useState(""),[missing,setMissing]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{if(!session.subjectKey)return;const p=new URLSearchParams({subjectId:session.subjectKey});if(session.activeGrade)p.set("grade",String(session.activeGrade));Promise.all([fetch(`/api/teacher/students?${p}`).then(r=>r.json()),fetch(`/api/teacher/grade-data?subjectId=${encodeURIComponent(session.subjectKey)}`).then(r=>r.json())]).then(([a,g])=>{const by=g.byCode||{};const list=(Array.isArray(a.students)?a.students:[]).map((x:any)=>{const code=String(x.code||x.id||"").trim().toUpperCase(),saved=by[code]||{};return{id:code,code,name:String(x.name||"").trim(),className:String(x.className||x.class||"").trim(),gradeValues:saved.gradeValues||x.gradeValues||{},gradePlanValues:saved.gradePlanValues||x.gradePlanValues||{}}}).filter((x:Student)=>x.code&&x.name&&x.className);setStudents(list)}).catch(()=>setMessage("تعذر تحميل الطلاب."))},[session.subjectKey,session.activeGrade]);
 const classes=useMemo(()=>[...new Set(students.map(x=>x.className))].sort((a,b)=>a.localeCompare(b,"ar",{numeric:true})),[students]);
 useEffect(()=>{if(classes.length&&!classes.includes(selectedClass))setSelectedClass(classes[0])},[classes,selectedClass]);
 const section=useMemo(()=>activePlan?.sections.find(x=>x.id===sectionId)||activePlan?.sections[0]||null,[activePlan,sectionId]);
 useEffect(()=>{if(activePlan?.sections.length&&!activePlan.sections.some(x=>x.id===sectionId))setSectionId(activePlan.sections[0].id)},[activePlan,sectionId]);
 useEffect(()=>{if(section?.items.length&&!section.items.some(x=>x.id===itemId)){const likely=section.items.find(x=>/واجب|مهم|تكليف/i.test(x.label));setItemId((likely||section.items[0]).id)}},[section,itemId]);
 const item=section?.items.find(x=>x.id===itemId)||null,classStudents=students.filter(x=>x.className===selectedClass);
 useEffect(()=>{setMissing({});setMessage("")},[selectedClass,sectionId,itemId]);
 function toggle(id:string){setMissing(x=>({...x,[id]:!x[id]}))}
 async function save(){if(!activePlan||!section||!item||!session.subjectKey||!classStudents.length)return;setBusy(true);setMessage("");try{const now=new Date().toISOString(),key=gradeEntryKey(section.id,item.id);const rows=classStudents.map(student=>{const existing=student.gradePlanValues?.[activePlan.id]||student.gradeValues||{};const values={...existing,[key]:missing[student.id]?0:item.max};return{id:student.id,code:student.code,name:student.name,className:student.className,gradeValues:values,gradePlanValues:{...(student.gradePlanValues||{}),[activePlan.id]:values},activeGradePlanId:activePlan.id,activeGradePlanVersion:activePlan.version,gradePlanUpdatedAt:now}});const r=await fetch("/api/teacher/grade-data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subjectId:session.subjectKey,rows})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"تعذر الحفظ");setStudents(cur=>cur.map(s=>{const row=rows.find(x=>x.code===s.code);return row?{...s,gradeValues:row.gradeValues,gradePlanValues:row.gradePlanValues}:s}));setMessage(`تم رصد ${item.label}: ${classStudents.length-Object.values(missing).filter(Boolean).length} مسلّم، ${Object.values(missing).filter(Boolean).length} لم يسلّم.`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر الحفظ") }finally{setBusy(false)}}
 if(planLoading)return <main dir="rtl" style={{padding:24}}>جارٍ التحميل…</main>;
 return <main dir="rtl" style={{maxWidth:900,margin:"24px auto",padding:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h1>رصد الواجبات السريع</h1><p>الجميع مسلّم افتراضيًا؛ اضغط فقط على الطالب الذي لم يسلّم.</p></div><Link href="/teacher/grades">العودة للتحصيل العلمي</Link></div>{message&&<p style={{padding:12,border:"1px solid #ccc",borderRadius:10}}>{message}</p>}<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:18}}><label>الفصل<select style={{width:"100%",padding:10}} value={selectedClass} onChange={e=>setSelectedClass(e.target.value)}>{classes.map(x=><option key={x}>{x}</option>)}</select></label><label>الوحدة / الفترة<select style={{width:"100%",padding:10}} value={section?.id||""} onChange={e=>setSectionId(e.target.value)}>{activePlan?.sections.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>الواجب<select style={{width:"100%",padding:10}} value={item?.id||""} onChange={e=>setItemId(e.target.value)}>{section?.items.map(x=><option key={x.id} value={x.id}>{x.label} — {x.max} درجات</option>)}</select></label></section><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",marginBottom:12,flexWrap:"wrap"}}><b>لم يسلّم: {Object.values(missing).filter(Boolean).length} من {classStudents.length}</b><button type="button" onClick={()=>setMissing({})}>إلغاء جميع النواقص</button></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:8}}>{classStudents.map((s,i)=><button key={s.id} type="button" onClick={()=>toggle(s.id)} style={{padding:14,textAlign:"right",borderRadius:12,border:missing[s.id]?"2px solid currentColor":"1px solid #bbb",fontWeight:700,opacity:missing[s.id]?.85:1}}><span>{i+1}. {s.name}</span><small style={{display:"block",marginTop:4}}>{missing[s.id]?"✕ لم يسلّم":"✓ مسلّم"}</small></button>)}</div><div style={{position:"sticky",bottom:10,marginTop:18,padding:12,background:"rgba(255,255,255,.95)",border:"1px solid #ccc",borderRadius:14}}><button type="button" disabled={busy||!item||!selectedClass} onClick={()=>void save()} style={{width:"100%",padding:14,fontWeight:800}}>{busy?"جارٍ الحفظ…":`اعتماد ${item?.label||"الواجب"}`}</button></div></main>
}
