"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { calculateGradePlanResult, gradeEntryKey, normalizeGradePlan, type GradePlan, type GradeValueMap } from "../../../lib/grade-plan";
import "./academic-record.css";

type GradeHistoryEntry={id?:string;planId?:string;teacherId?:string;teacherName?:string;subjectKey?:string;sectionLabel?:string;itemLabel?:string;maximum?:number;before?:number;after?:number;delta?:number;changedAt?:string};
type StudentRecord={name?:string;class?:string;gradePlan?:GradePlan|null;gradeValues?:GradeValueMap;gradePlanValues?:Record<string,GradeValueMap>;gradePlanUpdatedAt?:string;gradeHistory?:GradeHistoryEntry[]};
type Match={id:string;teacherId:string;subjectKey:string;subjectLabel:string;teacherName:string;accessToken:string;data:StudentRecord};
type Snapshot=Record<string,number>;
type Change={id:string;subject:string;section:string;item:string;before:number;after:number;maximum:number;delta:number;at:string;teacher?:string;persistent?:boolean};

const CODE_PATTERN=/^TH[123]\d{3}$/;
const logo="/icons/lahooni-identity-320.jpg";
const ar=(value:number)=>new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:2}).format(Number.isFinite(value)?value:0);
function normalizeCode(value:string){return value.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)}
function dateLabel(value?:string){if(!value)return"";const d=new Date(value);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("ar-SA",{dateStyle:"medium",timeStyle:"short"}).format(d)}
function valuesFor(match:Match,plan:GradePlan){return match.data.gradePlanValues?.[plan.id]||match.data.gradeValues||{}}
function snapshotFor(matches:Match[]):Snapshot{const out:Snapshot={};for(const match of matches){const plan=normalizeGradePlan(match.data.gradePlan);if(!plan)continue;const values=valuesFor(match,plan);for(const section of plan.sections)for(const item of section.items){const key=gradeEntryKey(section.id,item.id);out[`${match.subjectKey}::${plan.id}::${key}`]=Number(values[key]||0)}}return out}
function liveChanges(before:Snapshot,after:Snapshot,matches:Match[]):Change[]{const changes:Change[]=[];for(const match of matches){const plan=normalizeGradePlan(match.data.gradePlan);if(!plan)continue;for(const section of plan.sections)for(const item of section.items){const key=gradeEntryKey(section.id,item.id);const snapKey=`${match.subjectKey}::${plan.id}::${key}`;const oldValue=Number(before[snapKey]||0);const newValue=Number(after[snapKey]||0);if(newValue!==oldValue)changes.push({id:`live:${snapKey}:${newValue}`,subject:match.subjectLabel,section:section.label,item:item.label,before:oldValue,after:newValue,maximum:item.max,delta:Number((newValue-oldValue).toFixed(2)),at:new Date().toISOString(),teacher:match.teacherName})}}return changes}
function historyFor(matches:Match[]):Change[]{const seen=new Set<string>();const rows:Change[]=[];for(const match of matches){for(const entry of match.data.gradeHistory||[]){const id=String(entry.id||`${match.subjectKey}:${entry.changedAt}:${entry.itemLabel}:${entry.after}`);if(seen.has(id))continue;seen.add(id);rows.push({id,subject:match.subjectLabel,section:String(entry.sectionLabel||"التقييم"),item:String(entry.itemLabel||"بند الدرجة"),before:Number(entry.before||0),after:Number(entry.after||0),maximum:Number(entry.maximum||0),delta:Number(entry.delta??(Number(entry.after||0)-Number(entry.before||0))),at:String(entry.changedAt||""),teacher:String(entry.teacherName||match.teacherName),persistent:true})}}return rows.sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,60)}

export default function AcademicRecordPage(){
 const[code,setCode]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);const[matches,setMatches]=useState<Match[]>([]);const[selectedKey,setSelectedKey]=useState("");const[live,setLive]=useState<Change[]>([]);const refreshTimer=useRef<number|undefined>(undefined);
 const selected=matches.find(m=>m.subjectKey===selectedKey)||matches[0]||null;
 async function hydrate(match:Match){try{const response=await fetch("/api/student/profile",{headers:{Authorization:`Bearer ${match.accessToken}`},cache:"no-store"});const payload=await response.json().catch(()=>({}));return response.ok&&payload.data?{...match,data:payload.data as StudentRecord}:match}catch{return match}}
 async function lookup(raw:string){const normalized=normalizeCode(raw);setMessage("");if(!CODE_PATTERN.test(normalized))return setMessage("أدخل كود الطالب الصحيح مثل TH1234.");setLoading(true);try{const response=await fetch("/api/student/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessCode:normalized}),cache:"no-store"});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||"تعذر فتح السجل الأكاديمي");const list=await Promise.all((Array.isArray(payload.matches)?payload.matches:[]).map((m:Match)=>hydrate(m)));setMatches(list);setSelectedKey(list[0]?.subjectKey||"");const current=snapshotFor(list);const storageKey=`lahooni-academic-snapshot:${normalized}`;const previousRaw=localStorage.getItem(storageKey);if(previousRaw){try{setLive(liveChanges(JSON.parse(previousRaw) as Snapshot,current,list))}catch{setLive([])}}localStorage.setItem(storageKey,JSON.stringify(current));}catch(error){setMessage(error instanceof Error?error.message:"تعذر الوصول إلى البيانات الآن")}finally{setLoading(false)}}
 function submit(event:FormEvent){event.preventDefault();void lookup(code)}
 useEffect(()=>()=>{if(refreshTimer.current)window.clearTimeout(refreshTimer.current)},[]);
 useEffect(()=>{if(!matches.length)return;const run=async()=>{const before=snapshotFor(matches);const updated=await Promise.all(matches.map(hydrate));const after=snapshotFor(updated);const changed=liveChanges(before,after,updated);if(changed.length)setLive(current=>[...changed,...current].slice(0,30));setMatches(updated);refreshTimer.current=window.setTimeout(run,15000)};refreshTimer.current=window.setTimeout(run,15000);return()=>{if(refreshTimer.current)window.clearTimeout(refreshTimer.current)}},[matches.length]);
 const academic=useMemo(()=>matches.map(match=>{const plan=normalizeGradePlan(match.data.gradePlan);const result=plan?calculateGradePlanResult(plan,{...match.data,gradeValues:valuesFor(match,plan)}):null;return{match,plan,result}}),[matches]);
 const persisted=useMemo(()=>historyFor(matches),[matches]);
 const changes=useMemo(()=>{const seen=new Set<string>();return[...persisted,...live].filter(c=>{if(seen.has(c.id))return false;seen.add(c.id);return true}).sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,30)},[persisted,live]);
 const selectedAcademic=academic.find(x=>x.match.subjectKey===selected?.subjectKey)||academic[0];
 if(!matches.length)return <main className="sar-gateway" dir="rtl"><section><img src={logo} alt="بوابة أستاذ لحوني التعليمية"/><small>بوابة الطالب</small><h1>سجلي الأكاديمي الذكي</h1><p>شاهد كل مادة كشهادة تفصيلية، واعرف بالضبط أين أضيفت درجتك ومن كم.</p><form onSubmit={submit}><label>كود الطالب</label><input value={code} onChange={e=>setCode(normalizeCode(e.target.value))} placeholder="TH1234" dir="ltr"/><button disabled={loading}>{loading?"جارٍ فتح السجل…":"فتح سجلي الأكاديمي"}</button></form>{message?<strong className="sar-error">{message}</strong>:null}</section></main>;
 const studentName=matches[0]?.data.name||"الطالب";const className=matches[0]?.data.class||"";
 return <main className="sar" dir="rtl"><header className="sar-top"><div><img src={logo} alt="هوية البوابة"/><span><small>بوابة أستاذ لحوني التعليمية</small><strong>السجل الأكاديمي الذكي</strong></span></div><div><b>{studentName}</b><small>{className}</small></div></header>
 <section className="sar-hero"><div><small>شهادتك الأكاديمية الحية</small><h1>{studentName}</h1><p>كل درجة مرتبطة مباشرة بخطة معلم المادة. لا توجد درجة مجهولة المصدر: كل بند يظهر باسمه، درجتك فيه، ومن كم.</p></div><span className="sar-seal">موثق<br/>من البوابة</span></section>
 {changes.length?<section className="sar-updates"><header><div><small>سجل محفوظ من رصد المعلمين</small><h2>من أين جاءت الزيادة أو التعديل؟</h2></div><span>{changes.length} تحديث</span></header><div>{changes.slice(0,10).map(c=><article key={c.id}><b className={c.delta>=0?"up":"down"}>{c.delta>=0?"+":""}{ar(c.delta)}</b><div><strong>{c.subject} • {c.item}</strong><span>{c.section}{c.persistent?" • محفوظ في السجل":" • تحديث مباشر"}</span><small>كانت {ar(c.before)} وأصبحت {ar(c.after)} من {ar(c.maximum)}</small></div><time>{dateLabel(c.at)}{c.teacher?` • ${c.teacher}`:""}</time></article>)}</div></section>:<section className="sar-no-updates"><b>سجل الزيادات</b><span>عند حفظ المعلم لأي تغيير في الدرجة سيظهر هنا دائمًا باسم البند، الدرجة السابقة والجديدة، ومن كم.</span></section>}
 <section className="sar-subjects">{academic.map(({match,result})=><button key={match.subjectKey} className={selected?.subjectKey===match.subjectKey?"active":""} onClick={()=>setSelectedKey(match.subjectKey)}><span><b>{match.subjectLabel}</b><small>{match.teacherName}</small></span><strong>{result?.recordedMaximum?`${ar(result.earned)} / ${ar(result.maximum)}`:"بانتظار الرصد"}</strong></button>)}</section>
 {selectedAcademic?.plan&&selectedAcademic.result?<section className="sar-certificate"><header><div><small>كشف تحصيل تفصيلي</small><h2>{selectedAcademic.match.subjectLabel}</h2><p>المعلم: {selectedAcademic.match.teacherName}</p></div><div className="sar-total"><small>الدرجة الحالية</small><strong>{ar(selectedAcademic.result.earned)} <i>/ {ar(selectedAcademic.result.maximum)}</i></strong><span>اكتمال الرصد {ar(selectedAcademic.result.completion)}٪</span></div></header>
 <div className="sar-sections">{selectedAcademic.result.sections.map(section=><article key={section.id}><div className="sar-section-head"><span><small>قسم التقييم</small><b>{section.label}</b></span><strong>{ar(section.earned)} / {ar(section.maximum)}</strong></div><div className="sar-items">{section.items.map(entry=><div key={entry.key} className={entry.recorded?"recorded":"pending"}><span><b>{entry.item.label}</b><small>{entry.recorded?"تم الرصد":"لم تُرصد بعد"}</small></span><strong>{entry.recorded?ar(entry.value):"—"} <i>/ {ar(entry.maximum)}</i></strong></div>)}</div></article>)}</div>
 <footer><img src={logo} alt=""/><div><b>كشف تحصيل صادر آليًا من بوابة أستاذ لحوني التعليمية</b><span>يعكس آخر رصد محفوظ في خطة معلم المادة{selectedAcademic.match.data.gradePlanUpdatedAt?` • آخر تحديث ${dateLabel(selectedAcademic.match.data.gradePlanUpdatedAt)}`:""}</span></div><span className="sar-stamp">معتمد</span></footer></section>:<section className="sar-empty"><h2>{selected?.subjectLabel}</h2><p>لم يعتمد معلم المادة خطة درجات تفصيلية بعد.</p></section>}
 </main>
}
