"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useTeacherClient} from "../../../../lib/teacher-client";
import {gradeEntryKey,roundGrade,type GradeValueMap} from "../../../../lib/grade-plan";
import {useGradePlan} from "../../../../lib/use-grade-plan";
import "./classera.css";

type Student={code:string;name:string;className:string;gradeValues?:GradeValueMap;gradePlanValues?:Record<string,GradeValueMap>};
type MatchRow={code:string;name:string;className:string;count:number};
type MatchResult={ok:boolean;totalFiles:number;rows:MatchRow[];files:{name:string;matched:number}[];message?:string};
const allowed=(label:string)=>/(واجب|واجبات|اختبار|اختبارات)/.test(label);
const clamp=(value:number,max:number)=>roundGrade(Math.max(0,Math.min(max,value)));

export default function ClasseraImportPage(){
 const session=useTeacherClient();
 const {activePlan,loading:planLoading}=useGradePlan(true);
 const [students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false);
 const [files,setFiles]=useState<File[]>([]),[result,setResult]=useState<MatchResult|null>(null),[message,setMessage]=useState("");
 const [sectionId,setSectionId]=useState(""),[itemId,setItemId]=useState("");
 useEffect(()=>{if(!session.subjectKey)return;const controller=new AbortController();(async()=>{setLoading(true);try{const params=new URLSearchParams({subjectId:session.subjectKey});if(session.activeGrade)params.set("grade",String(session.activeGrade));const [roster,academic]=await Promise.all([fetch(`/api/teacher/students?${params}`,{signal:controller.signal}).then(r=>r.json()),fetch(`/api/teacher/grade-data?subjectId=${encodeURIComponent(session.subjectKey)}`,{signal:controller.signal}).then(r=>r.json())]);const byCode=academic.byCode&&typeof academic.byCode==="object"?academic.byCode:{};const list=(Array.isArray(roster.students)?roster.students:[]).map((v:any)=>{const code=String(v.code||v.id||"").trim().toUpperCase(),saved=byCode[code]||{};return{code,name:String(v.name||"").trim(),className:String(v.className||v.class||"").trim(),gradeValues:saved.gradeValues||v.gradeValues||{},gradePlanValues:saved.gradePlanValues||v.gradePlanValues||{}}}).filter((s:Student)=>s.code&&s.name);setStudents(list)}catch(e:any){if(e?.name!=="AbortError")setMessage("تعذر تحميل طلاب المادة الحالية.")}finally{setLoading(false)}})();return()=>controller.abort()},[session.subjectKey,session.activeGrade]);
 const eligible=useMemo(()=>activePlan?.sections.flatMap(section=>section.items.filter(item=>allowed(`${section.label} ${item.label}`)).map(item=>({section,item})))||[],[activePlan]);
 useEffect(()=>{if(!eligible.length)return;const current=eligible.find(x=>x.section.id===sectionId&&x.item.id===itemId)||eligible[0];setSectionId(current.section.id);setItemId(current.item.id)},[eligible,sectionId,itemId]);
 const target=eligible.find(x=>x.section.id===sectionId&&x.item.id===itemId)||null;
 async function preview(){if(!session.subjectKey||!files.length)return;setMessage("");setResult(null);const form=new FormData();form.set("subjectId",session.subjectKey);form.set("roster",JSON.stringify(students.map(s=>({code:s.code,name:s.name,className:s.className}))));files.forEach(file=>form.append("files",file));setLoading(true);try{const r=await fetch("/api/teacher/classera-match",{method:"POST",body:form});const data=await r.json();if(!r.ok)throw new Error(data.message||"تعذر تحليل الملفات");setResult(data)}catch(e:any){setMessage(e?.message||"تعذر تحليل الملفات") }finally{setLoading(false)}}
 function proposed(row:MatchRow){if(!target||!result?.totalFiles)return 0;return clamp((row.count/result.totalFiles)*Number(target.item.max||0),Number(target.item.max||0))}
 async function apply(){if(!activePlan||!target||!result||!session.subjectKey)return;setSaving(true);setMessage("");try{const byCode=new Map(students.map(s=>[s.code,s]));const key=gradeEntryKey(target.section.id,target.item.id);const rows=result.rows.map(match=>{const student=byCode.get(match.code)!;const base=student.gradePlanValues?.[activePlan.id]||student.gradeValues||{};const merged={...base,[key]:proposed(match)};return{code:student.code,name:student.name,className:student.className,gradeValues:merged,gradePlanValues:{...(student.gradePlanValues||{}),[activePlan.id]:merged},activeGradePlanId:activePlan.id,activeGradePlanVersion:activePlan.version||1,gradePlanUpdatedAt:new Date().toISOString()}});for(let i=0;i<rows.length;i+=90){const r=await fetch("/api/teacher/grade-data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subjectId:session.subjectKey,rows:rows.slice(i,i+90)})});const data=await r.json();if(!r.ok)throw new Error(data.message||"تعذر حفظ الرصد") }setMessage(`تم اعتماد ${result.totalFiles} ملفات على بند ${target.item.label}.`)}catch(e:any){setMessage(e?.message||"تعذر اعتماد الدرجات") }finally{setSaving(false)}}
 if(planLoading)return <main className="ci-page"><p>جارٍ تحميل خطة الدرجات…</p></main>;
 return <main className="ci-page" dir="rtl"><header><div><small>التحصيل العلمي</small><h1>استيراد كلاسيرا</h1><p>مطابقة بالاسم فقط لملفات الواجبات والاختبارات. لا نعتمد درجة كلاسيرا.</p></div><Link href="/teacher/grades">العودة للتحصيل العلمي</Link></header>
 <section className="ci-card"><div className="ci-grid"><label><span>بند الرصد</span><select value={`${sectionId}|${itemId}`} onChange={e=>{const [s,i]=e.target.value.split("|");setSectionId(s);setItemId(i);setResult(null)}}>{eligible.map(({section,item})=><option key={`${section.id}|${item.id}`} value={`${section.id}|${item.id}`}>{section.label} — {item.label} ({item.max} درجات)</option>)}</select></label><label className="ci-files"><span>تقارير كلاسيرا</span><input type="file" multiple accept=".pdf,.txt" onChange={e=>{setFiles(Array.from(e.target.files||[]));setResult(null)}}/><b>{files.length?`${files.length} ملفات مختارة`:"اختر جميع الواجبات أو الاختبارات دفعة واحدة"}</b></label></div><div className="ci-actions"><button onClick={()=>void preview()} disabled={!files.length||!eligible.length||loading}>{loading?"جارٍ المطابقة…":"معاينة المطابقة والحساب"}</button></div>{!eligible.length?<p className="ci-warn">لا يوجد في خطة الرصد الحالية بند اسمه واجبات أو اختبارات؛ لذلك الاستيراد مقفل حمايةً للدرجات.</p>:null}</section>
 {message?<p className="ci-message">{message}</p>:null}
 {result&&target?<section className="ci-card"><div className="ci-summary"><b>{result.totalFiles} ملفات</b><span>الدرجة الكاملة: {target.item.max}</span><span>طلاب المادة: {result.rows.length}</span><span>المعادلة: عدد مرات ظهور الاسم ÷ عدد الملفات × درجة البند</span></div><div className="ci-table"><table><thead><tr><th>الطالب</th><th>فصله الحالي</th><th>ظهر في</th><th>النسبة</th><th>الدرجة المقترحة</th></tr></thead><tbody>{result.rows.sort((a,b)=>a.className.localeCompare(b.className,"ar",{numeric:true})||a.name.localeCompare(b.name,"ar")).map(row=><tr key={row.code}><td><b>{row.name}</b><small>{row.code}</small></td><td>{row.className}</td><td>{row.count} من {result.totalFiles}</td><td>{Math.round((row.count/result.totalFiles)*100)}%</td><td><strong>{proposed(row)} / {target.item.max}</strong></td></tr>)}</tbody></table></div><div className="ci-actions ci-approve"><span>لن يُحفظ شيء حتى تضغط اعتماد.</span><button onClick={()=>void apply()} disabled={saving}>{saving?"جارٍ الاعتماد…":"اعتماد الدرجات في التحصيل العلمي"}</button></div></section>:null}
 </main>
}
