"use client";

import { useEffect, useMemo, useState } from "react";
import { collection, doc, onSnapshot, setDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import { ACADEMIC_UNITS, FINAL_MAX, RESEARCH_MAX, UNIT_MAX } from "../../../lib/academic-config";
import { getSubjectConfig, type SubjectKey } from "../../../lib/subject-config";
import { tenantCollection } from "../../../lib/teacher-tenant";
import "./portfolio.css";

type TeacherSession={teacherId:string;teacherName:string;subjectKey:SubjectKey};
type UnitRecord={total?:number;attendance?:number;participation?:number;homework?:number;unitExam?:number;exam1?:number;exam2?:number;updatedAt?:string};
type Student={name?:string;class?:string;research?:number;researchScore?:number;units?:Record<string,UnitRecord>};
type AttendanceDoc={records?:Record<string,"present"|"absent"|"late"|"excused"|"escaped">};
type Evidence={id:string;title:string;category:string;date:string;url:string;description:string};
type PortfolioForm={school:string;academicYear:string;professionalSummary:string;goals:string;initiatives:string;reflection:string;developmentPlan:string;evidence:Evidence[]};

const emptyEvidence=():Evidence=>({id:`ev-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,title:"",category:"مبادرة",date:new Date().toISOString().slice(0,10),url:"",description:""});
const emptyForm:PortfolioForm={school:"",academicYear:"١٤٤٧هـ",professionalSummary:"",goals:"",initiatives:"",reflection:"",developmentPlan:"",evidence:[]};
const evidenceCategories=["مبادرة","نشاط طلابي","درس نموذجي","دورة تدريبية","شهادة أو تكريم","مشاركة مدرسية","تقرير أو إنجاز","أخرى"];
const ar=new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:1});
const n=(value:number)=>ar.format(Number.isFinite(value)?value:0);

export default function PortfolioPage(){
 const[tenant,setTenant]=useState<TeacherSession|null>(null),[students,setStudents]=useState<Student[]>([]),[attendance,setAttendance]=useState<AttendanceDoc[]>([]),[form,setForm]=useState<PortfolioForm>(emptyForm),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/teacher-session",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const s=await r.json();setTenant({teacherId:String(s.teacherId),teacherName:String(s.teacherName),subjectKey:s.subjectKey})}).catch(()=>setMessage("تعذر قراءة جلسة المعلم"))},[]);
 useEffect(()=>{if(!tenant)return;const studentsPath=tenantCollection(tenant.teacherId,tenant.subjectKey,"students"),attendancePath=tenantCollection(tenant.teacherId,tenant.subjectKey,"attendance"),portfolioPath=tenantCollection(tenant.teacherId,tenant.subjectKey,"portfolio");const a=onSnapshot(collection(db,studentsPath),snap=>setStudents(snap.docs.map(d=>d.data() as Student)));const b=onSnapshot(collection(db,attendancePath),snap=>setAttendance(snap.docs.map(d=>d.data() as AttendanceDoc)));const c=onSnapshot(doc(db,portfolioPath,"profile"),snap=>{if(snap.exists()){const data=snap.data() as Partial<PortfolioForm>;setForm({...emptyForm,...data,evidence:Array.isArray(data.evidence)?data.evidence:[]})}});return()=>{a();b();c()}},[tenant]);
 const stats=useMemo(()=>{const classes=new Set(students.map(s=>(s.class||"").trim()).filter(Boolean));let totalGrades=0,recordedStudents=0,recordedUnits=0;const unitTotals=Object.fromEntries(ACADEMIC_UNITS.map(unit=>[unit.key,{sum:0,count:0}]));const classTotals:Record<string,{sum:number,count:number}>={};students.forEach(student=>{let studentTotal=0,hasAny=false;ACADEMIC_UNITS.forEach(unit=>{const u=student.units?.[unit.key];if(!u)return;const total=Math.min(UNIT_MAX,Number(u.total??Number(u.attendance||0)+Number(u.participation||0)+Number(u.homework||0)+Number(u.unitExam??u.exam1??u.exam2??0)));studentTotal+=total;if(u.updatedAt||u.total!==undefined){recordedUnits++;hasAny=true;unitTotals[unit.key].sum+=total;unitTotals[unit.key].count++}});studentTotal+=Math.min(RESEARCH_MAX,Number(student.researchScore??student.research??0));if(hasAny){const safe=Math.min(FINAL_MAX,studentTotal);recordedStudents++;totalGrades+=safe;const className=(student.class||"").trim();if(className){classTotals[className]??={sum:0,count:0};classTotals[className].sum+=safe;classTotals[className].count++}}});let present=0,all=0;attendance.forEach(day=>Object.values(day.records||{}).forEach(status=>{all++;if(status==="present")present++}));const achievement=students.length?Math.round(recordedUnits/(students.length*ACADEMIC_UNITS.length)*100):0;const bestUnit=ACADEMIC_UNITS.map(unit=>({label:unit.label,average:unitTotals[unit.key].count?unitTotals[unit.key].sum/unitTotals[unit.key].count:0})).sort((a,b)=>b.average-a.average)[0];const bestClass=Object.entries(classTotals).map(([name,value])=>({name,average:value.count?value.sum/value.count:0})).sort((a,b)=>b.average-a.average)[0];return{students:students.length,classes:classes.size,average:recordedStudents?Math.round(totalGrades/recordedStudents*10)/10:0,attendanceRate:all?Math.round(present/all*100):0,achievement,bestUnit,bestClass,recordedStudents}},[students,attendance]);
 const subject=tenant?getSubjectConfig(tenant.subjectKey):getSubjectConfig("history");
 const validEvidence=form.evidence.filter(item=>item.title.trim());
 const completionItems=[form.school,form.academicYear,form.professionalSummary,form.goals,form.initiatives,form.reflection,form.developmentPlan,validEvidence.length>=2?"evidence":"",stats.achievement>=80?"tracking":""];
 const completion=completionItems.filter(value=>typeof value==="string"&&value.trim()).length,completionRate=Math.round(completion/completionItems.length*100);
 const missing=[!form.school.trim()?"اسم المدرسة":"",!form.professionalSummary.trim()?"النبذة المهنية":"",!form.goals.trim()?"الأهداف المهنية":"",!form.initiatives.trim()?"المبادرات والإنجازات":"",!form.reflection.trim()?"التأمل المهني":"",!form.developmentPlan.trim()?"خطة التطوير":"",validEvidence.length<2?"إضافة شاهدين على الأقل":"",stats.achievement<80?"رفع اكتمال رصد الوحدات إلى ٨٠٪":""].filter(Boolean);
 function update<K extends keyof PortfolioForm>(key:K,value:PortfolioForm[K]){setForm(current=>({...current,[key]:value}))}
 function addEvidence(){if(form.evidence.length>=12)return setMessage("الحد الخفيف للشواهد هو ١٢ شاهدًا. اجمع الروابط المتشابهة في شاهد واحد.");update("evidence",[...form.evidence,emptyEvidence()])}
 function updateEvidence(id:string,key:Exclude<keyof Evidence,"id">,value:string){update("evidence",form.evidence.map(item=>item.id===id?{...item,[key]:value}:item))}
 function removeEvidence(id:string){update("evidence",form.evidence.filter(item=>item.id!==id))}
 async function save(){if(!tenant)return;try{setSaving(true);setMessage("");await setDoc(doc(db,tenantCollection(tenant.teacherId,tenant.subjectKey,"portfolio"),"profile"),{...form,evidence:form.evidence.slice(0,12),teacherId:tenant.teacherId,teacherName:tenant.teacherName,subjectKey:tenant.subjectKey,updatedAt:new Date().toISOString()},{merge:true});setMessage("تم حفظ ملف الإنجاز والشواهد") }catch{setMessage("تعذر حفظ ملف الإنجاز") }finally{setSaving(false)}}
 return <main className="portfolio-page" dir="rtl"><section className="portfolio-toolbar no-print"><div><span>🏆 مركز إنجاز المعلم</span><h1>ملف الإنجاز المهني</h1><p>بيانات خفيفة في مستند واحد، والشواهد تُحفظ كروابط دون رفع ملفات ثقيلة.</p></div><div className="portfolio-actions"><button onClick={save} disabled={saving}>{saving?"جارٍ الحفظ...":"💾 حفظ"}</button><button className="print" onClick={()=>window.print()}>📄 إصدار PDF</button></div></section>{message&&<p className="portfolio-message no-print">{message}</p>}
 <section className="portfolio-cover"><div className="cover-mark">ت</div><p>شركة التهذيب للخدمات التعليمية</p><small>إدارة التطوير والجودة التعليمية</small><h2>ملف الإنجاز المهني للمعلم</h2><div className="cover-line"/><h3>سعادة إدارة شركة التهذيب للخدمات التعليمية</h3><dl><div><dt>اسم المعلم</dt><dd>{tenant?.teacherName||"—"}</dd></div><div><dt>المادة</dt><dd>{subject.label}</dd></div><div><dt>المدرسة</dt><dd>{form.school||"لم تُحدد"}</dd></div><div><dt>العام الدراسي</dt><dd>{form.academicYear||"—"}</dd></div></dl></section>
 <section className="portfolio-progress no-print"><div className="completion-ring" style={{"--value":`${completionRate*3.6}deg`} as React.CSSProperties}><strong>{n(completionRate)}٪</strong></div><div><h3>اكتمال ملف الإنجاز</h3><p>{missing.length?`المتبقي: ${missing.slice(0,3).join("، ")}${missing.length>3?"...":""}`:"ملفك مكتمل وجاهز للإصدار الرسمي."}</p></div></section>
 <section className="portfolio-stats"><article><span>عدد الطلاب</span><strong>{n(stats.students)}</strong></article><article><span>عدد الفصول</span><strong>{n(stats.classes)}</strong></article><article><span>متوسط التحصيل</span><strong>{n(stats.average)}/١٠٠</strong></article><article><span>نسبة الحضور</span><strong>{n(stats.attendanceRate)}٪</strong></article><article><span>اكتمال رصد الوحدات</span><strong>{n(stats.achievement)}٪</strong></article></section>
 <section className="teacher-impact"><div className="impact-heading"><span>✨ أثر المعلم</span><h2>بصمتك التعليمية بالأرقام</h2><p>تحليل مباشر من بيانات الرصد الحالية، دون إنشاء جداول أو نسخ إضافية.</p></div><div className="impact-grid"><article><small>أفضل فصل أداءً</small><strong>{stats.bestClass?.name||"لم يكتمل الرصد"}</strong><p>{stats.bestClass?`متوسط ${n(stats.bestClass.average)} من ١٠٠`:"يظهر بعد توفر درجات كافية."}</p></article><article><small>أقوى وحدة</small><strong>{stats.bestUnit?.average?stats.bestUnit.label:"لم يكتمل الرصد"}</strong><p>{stats.bestUnit?.average?`متوسط ${n(stats.bestUnit.average)} من ${n(UNIT_MAX)}`:"يظهر بعد رصد الوحدات."}</p></article><article><small>نطاق الأثر</small><strong>{n(stats.recordedStudents)} طالبًا</strong><p>طلاب لديهم رصد فعلي داخل المادة.</p></article></div></section>
 <section className="portfolio-fields"><label><span>اسم المدرسة</span><input value={form.school} onChange={e=>update("school",e.target.value)} placeholder="اكتب اسم المدرسة"/></label><label><span>العام الدراسي</span><input value={form.academicYear} onChange={e=>update("academicYear",e.target.value)} /></label><label className="wide"><span>النبذة المهنية</span><textarea value={form.professionalSummary} onChange={e=>update("professionalSummary",e.target.value)} placeholder="نبذة مختصرة عن خبرتك ورسالتك التعليمية"/></label><label className="wide"><span>الأهداف المهنية والتعليمية</span><textarea value={form.goals} onChange={e=>update("goals",e.target.value)} placeholder="الأهداف التي عملت على تحقيقها خلال الفصل"/></label><label className="wide"><span>المبادرات والإنجازات</span><textarea value={form.initiatives} onChange={e=>update("initiatives",e.target.value)} placeholder="المبادرات، الأنشطة، المشاركات والنتائج"/></label><label className="wide"><span>التأمل المهني</span><textarea value={form.reflection} onChange={e=>update("reflection",e.target.value)} placeholder="ما الذي نجح؟ وما الذي تعلمته؟"/></label><label className="wide"><span>خطة التطوير القادمة</span><textarea value={form.developmentPlan} onChange={e=>update("developmentPlan",e.target.value)} placeholder="خطوات عملية للفصل القادم"/></label></section>
 <section className="evidence-section no-print"><header><div><span>📎 الشواهد الذكية</span><h2>روابط الشهادات والصور والملفات</h2><p>أضف رابط Google Drive أو أي رابط مشاركة؛ لا نرفع الملف داخل البوابة حتى تظل خفيفة.</p></div><button onClick={addEvidence}>＋ إضافة شاهد</button></header><div className="evidence-list">{form.evidence.map((item,index)=><article key={item.id}><div className="evidence-number">{n(index+1)}</div><div className="evidence-fields"><input value={item.title} onChange={e=>updateEvidence(item.id,"title",e.target.value)} placeholder="عنوان الشاهد"/><select value={item.category} onChange={e=>updateEvidence(item.id,"category",e.target.value)}>{evidenceCategories.map(category=><option key={category}>{category}</option>)}</select><input type="date" value={item.date} onChange={e=>updateEvidence(item.id,"date",e.target.value)}/><input className="evidence-url" dir="ltr" value={item.url} onChange={e=>updateEvidence(item.id,"url",e.target.value)} placeholder="https:// رابط الملف أو الصورة"/><textarea value={item.description} onChange={e=>updateEvidence(item.id,"description",e.target.value)} placeholder="وصف مختصر للأثر أو الإنجاز"/></div><button className="remove-evidence" onClick={()=>removeEvidence(item.id)}>حذف</button></article>)}{!form.evidence.length&&<div className="evidence-empty">لا توجد شواهد بعد. أضف شاهدًا واربطه بصورة أو ملف مشاركة.</div>}</div></section>
 <section className="portfolio-print-sections print-only"><article><h2>النبذة المهنية</h2><p>{form.professionalSummary||"لم تُسجل نبذة مهنية."}</p></article><article><h2>الأهداف المهنية والتعليمية</h2><p>{form.goals||"لم تُسجل أهداف."}</p></article><article><h2>المبادرات والإنجازات</h2><p>{form.initiatives||"لم تُسجل مبادرات."}</p></article><article><h2>أثر المعلم</h2><p>بلغ متوسط تحصيل الطلاب {n(stats.average)} من ١٠٠، ونسبة الحضور {n(stats.attendanceRate)}٪، واكتمال رصد الوحدات {n(stats.achievement)}٪. {stats.bestClass?`أفضل فصل أداءً هو ${stats.bestClass.name}.`:""} {stats.bestUnit?.average?`أقوى وحدة هي ${stats.bestUnit.label}.`:""}</p></article><article><h2>الشواهد المهنية</h2>{validEvidence.length?validEvidence.map((item,index)=><div className="print-evidence" key={item.id}><b>{n(index+1)}. {item.title}</b><span>{item.category} — {item.date||"بدون تاريخ"}</span><p>{item.description||"لا يوجد وصف."}</p>{item.url&&<small>{item.url}</small>}</div>):<p>لم تُسجل شواهد.</p>}</article><article><h2>التأمل المهني</h2><p>{form.reflection||"لم يُسجل التأمل المهني."}</p></article><article><h2>خطة التطوير القادمة</h2><p>{form.developmentPlan||"لم تُسجل خطة تطوير."}</p></article></section>
 </main>
}
