"use client";

import { useEffect, useMemo, useState } from "react";
import { collection, doc, onSnapshot, setDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import { ACADEMIC_UNITS, FINAL_MAX, RESEARCH_MAX, UNIT_MAX } from "../../../lib/academic-config";
import { getSubjectConfig, type SubjectKey } from "../../../lib/subject-config";
import { tenantCollection } from "../../../lib/teacher-tenant";
import "./portfolio.css";

type TeacherSession={teacherId:string;teacherName:string;subjectKey:SubjectKey};
type UnitRecord={total?:number;attendance?:number;participation?:number;homework?:number;unitExam?:number;exam1?:number;exam2?:number;updatedAt?:string};
type Student={name?:string;class?:string;research?:number;researchScore?:number;units?:Record<string,UnitRecord>};
type AttendanceDoc={records?:Record<string,"present"|"absent"|"late"|"excused"|"escaped">};
type PortfolioForm={school:string;academicYear:string;professionalSummary:string;goals:string;initiatives:string;reflection:string;developmentPlan:string};

const emptyForm:PortfolioForm={school:"",academicYear:"١٤٤٧هـ",professionalSummary:"",goals:"",initiatives:"",reflection:"",developmentPlan:""};
const ar=new Intl.NumberFormat("ar-SA-u-nu-arab",{maximumFractionDigits:1});
const n=(value:number)=>ar.format(Number.isFinite(value)?value:0);

export default function PortfolioPage(){
 const[tenant,setTenant]=useState<TeacherSession|null>(null),[students,setStudents]=useState<Student[]>([]),[attendance,setAttendance]=useState<AttendanceDoc[]>([]),[form,setForm]=useState<PortfolioForm>(emptyForm),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/teacher-session",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();const s=await r.json();setTenant({teacherId:String(s.teacherId),teacherName:String(s.teacherName),subjectKey:s.subjectKey})}).catch(()=>setMessage("تعذر قراءة جلسة المعلم"))},[]);
 useEffect(()=>{if(!tenant)return;const studentsPath=tenantCollection(tenant.teacherId,tenant.subjectKey,"students"),attendancePath=tenantCollection(tenant.teacherId,tenant.subjectKey,"attendance"),portfolioPath=tenantCollection(tenant.teacherId,tenant.subjectKey,"portfolio");const a=onSnapshot(collection(db,studentsPath),snap=>setStudents(snap.docs.map(d=>d.data() as Student)));const b=onSnapshot(collection(db,attendancePath),snap=>setAttendance(snap.docs.map(d=>d.data() as AttendanceDoc)));const c=onSnapshot(doc(db,portfolioPath,"profile"),snap=>{if(snap.exists())setForm({...emptyForm,...snap.data()} as PortfolioForm)});return()=>{a();b();c()}},[tenant]);
 const stats=useMemo(()=>{const classes=new Set(students.map(s=>(s.class||"").trim()).filter(Boolean));let totalGrades=0,recordedStudents=0,recordedUnits=0;students.forEach(student=>{let studentTotal=0,hasAny=false;ACADEMIC_UNITS.forEach(unit=>{const u=student.units?.[unit.key];if(!u)return;const total=Math.min(UNIT_MAX,Number(u.total??Number(u.attendance||0)+Number(u.participation||0)+Number(u.homework||0)+Number(u.unitExam??u.exam1??u.exam2??0)));studentTotal+=total;if(u.updatedAt||u.total!==undefined){recordedUnits++;hasAny=true}});studentTotal+=Math.min(RESEARCH_MAX,Number(student.researchScore??student.research??0));if(hasAny){recordedStudents++;totalGrades+=Math.min(FINAL_MAX,studentTotal)}});let present=0,all=0;attendance.forEach(day=>Object.values(day.records||{}).forEach(status=>{all++;if(status==="present")present++}));const achievement=students.length?Math.round(recordedUnits/(students.length*ACADEMIC_UNITS.length)*100):0;return{students:students.length,classes:classes.size,average:recordedStudents?Math.round(totalGrades/recordedStudents*10)/10:0,attendanceRate:all?Math.round(present/all*100):0,achievement}},[students,attendance]);
 const subject=tenant?getSubjectConfig(tenant.subjectKey):getSubjectConfig("history");
 const completion=[form.school,form.academicYear,form.professionalSummary,form.goals,form.initiatives,form.reflection,form.developmentPlan].filter(v=>v.trim()).length;const completionRate=Math.round(completion/7*100);
 function update<K extends keyof PortfolioForm>(key:K,value:PortfolioForm[K]){setForm(current=>({...current,[key]:value}))}
 async function save(){if(!tenant)return;try{setSaving(true);setMessage("");await setDoc(doc(db,tenantCollection(tenant.teacherId,tenant.subjectKey,"portfolio"),"profile"),{...form,teacherId:tenant.teacherId,teacherName:tenant.teacherName,subjectKey:tenant.subjectKey,updatedAt:new Date().toISOString()},{merge:true});setMessage("تم حفظ ملف الإنجاز") }catch{setMessage("تعذر حفظ ملف الإنجاز") }finally{setSaving(false)}}
 return <main className="portfolio-page" dir="rtl"><section className="portfolio-toolbar no-print"><div><span>🏆 مركز إنجاز المعلم</span><h1>ملف الإنجاز المهني</h1><p>بيانات خفيفة في مستند واحد، والإحصاءات تُحسب مباشرة من رصدك الحالي.</p></div><div className="portfolio-actions"><button onClick={save} disabled={saving}>{saving?"جارٍ الحفظ...":"💾 حفظ"}</button><button className="print" onClick={()=>window.print()}>📄 إصدار PDF</button></div></section>{message&&<p className="portfolio-message no-print">{message}</p>}
 <section className="portfolio-cover"><div className="cover-mark">ت</div><p>شركة التهذيب للخدمات التعليمية</p><small>إدارة التطوير والجودة التعليمية</small><h2>ملف الإنجاز المهني للمعلم</h2><div className="cover-line"/><h3>سعادة إدارة شركة التهذيب للخدمات التعليمية</h3><dl><div><dt>اسم المعلم</dt><dd>{tenant?.teacherName||"—"}</dd></div><div><dt>المادة</dt><dd>{subject.label}</dd></div><div><dt>المدرسة</dt><dd>{form.school||"لم تُحدد"}</dd></div><div><dt>العام الدراسي</dt><dd>{form.academicYear||"—"}</dd></div></dl></section>
 <section className="portfolio-progress no-print"><div className="completion-ring" style={{"--value":`${completionRate*3.6}deg`} as React.CSSProperties}><strong>{n(completionRate)}٪</strong></div><div><h3>اكتمال ملف الإنجاز</h3><p>أكمل الحقول المهنية ثم احفظ، وبعدها أصدر الملف بصيغة PDF.</p></div></section>
 <section className="portfolio-stats"><article><span>عدد الطلاب</span><strong>{n(stats.students)}</strong></article><article><span>عدد الفصول</span><strong>{n(stats.classes)}</strong></article><article><span>متوسط التحصيل</span><strong>{n(stats.average)}/١٠٠</strong></article><article><span>نسبة الحضور</span><strong>{n(stats.attendanceRate)}٪</strong></article><article><span>اكتمال رصد الوحدات</span><strong>{n(stats.achievement)}٪</strong></article></section>
 <section className="portfolio-fields"><label><span>اسم المدرسة</span><input value={form.school} onChange={e=>update("school",e.target.value)} placeholder="اكتب اسم المدرسة"/></label><label><span>العام الدراسي</span><input value={form.academicYear} onChange={e=>update("academicYear",e.target.value)} /></label><label className="wide"><span>النبذة المهنية</span><textarea value={form.professionalSummary} onChange={e=>update("professionalSummary",e.target.value)} placeholder="نبذة مختصرة عن خبرتك ورسالتك التعليمية"/></label><label className="wide"><span>الأهداف المهنية والتعليمية</span><textarea value={form.goals} onChange={e=>update("goals",e.target.value)} placeholder="الأهداف التي عملت على تحقيقها خلال الفصل"/></label><label className="wide"><span>المبادرات والإنجازات</span><textarea value={form.initiatives} onChange={e=>update("initiatives",e.target.value)} placeholder="المبادرات، الأنشطة، المشاركات والنتائج"/></label><label className="wide"><span>التأمل المهني</span><textarea value={form.reflection} onChange={e=>update("reflection",e.target.value)} placeholder="ما الذي نجح؟ وما الذي تعلمته؟"/></label><label className="wide"><span>خطة التطوير القادمة</span><textarea value={form.developmentPlan} onChange={e=>update("developmentPlan",e.target.value)} placeholder="خطوات عملية للفصل القادم"/></label></section>
 <section className="portfolio-print-sections print-only"><article><h2>النبذة المهنية</h2><p>{form.professionalSummary||"لم تُسجل نبذة مهنية."}</p></article><article><h2>الأهداف المهنية والتعليمية</h2><p>{form.goals||"لم تُسجل أهداف."}</p></article><article><h2>المبادرات والإنجازات</h2><p>{form.initiatives||"لم تُسجل مبادرات."}</p></article><article><h2>التأمل المهني</h2><p>{form.reflection||"لم يُسجل التأمل المهني."}</p></article><article><h2>خطة التطوير القادمة</h2><p>{form.developmentPlan||"لم تُسجل خطة تطوير."}</p></article></section>
 </main>
}
