export type SchoolStage = "middle" | "secondary";

export type SchoolStudent = {
  id: string; code: string; name: string; stage: SchoolStage; grade: number; section: string; className: string; active: boolean;
  createdAt?: string; updatedAt?: string; transferredAt?: string; archivedAt?: string;
};
export type SchoolClass = { id:string; stage:SchoolStage; grade:number; section:string; name:string; active:boolean; createdAt?:string; updatedAt?:string };
export type AssignmentLike = { subjectId?:string; stage?:string; grade?:string; section?:string };
export const SCHOOL_STUDENTS_COLLECTION="portalV2Students";
export const SCHOOL_CLASSES_COLLECTION="portalV2Classes";
export const GRADE_OPTIONS=[1,2,3] as const;
export const SECTION_OPTIONS=["1","2","3","4","5","6","7"] as const;
export const STAGE_OPTIONS=["middle","secondary"] as const;
const ARABIC_DIGITS="٠١٢٣٤٥٦٧٨٩";
const ORDINALS:Record<string,string>={"1":"1","اول":"1","الاول":"1","اولي":"1","الاولى":"1","2":"2","ثاني":"2","الثاني":"2","ثانيه":"2","الثانيه":"2","3":"3","ثالث":"3","الثالث":"3","ثالثه":"3","الثالثه":"3","4":"4","رابع":"4","الرابع":"4","رابعه":"4","الرابعه":"4","5":"5","خامس":"5","الخامس":"5","خامسه":"5","الخامسه":"5","6":"6","سادس":"6","السادس":"6","سادسه":"6","السادسه":"6","7":"7","سابع":"7","السابع":"7","سابعه":"7","السابعه":"7","8":"8","ثامن":"8","الثامن":"8","ثامنه":"8","الثامنه":"8"};
export function clean(value:unknown){return String(value??"").replace(/\s+/g," ").trim()}
export function westernDigits(value:unknown){return clean(value).replace(/[٠-٩]/g,d=>String(ARABIC_DIGITS.indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)))}
export function normalizeArabic(value:unknown){return westernDigits(value).replace(/[\u064B-\u065F\u0670]/g,"").replace(/ـ/g,"").replace(/[إأآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").toLowerCase()}
function ordinalValues(value:unknown){const normalized=normalizeArabic(value).replace(/[\/_\-–—]+/g," ");const tokens=normalized.split(/\s+/).filter(Boolean);const values:string[]=[];for(const token of tokens){const direct=ORDINALS[token];if(direct)values.push(direct);else{const numeric=token.match(/^\d+$/)?.[0];if(numeric)values.push(numeric)}}return values}
export function gradeNumber(value:unknown):1|2|3|null{const exact=Number(westernDigits(value));if(exact===1||exact===2||exact===3)return exact;const first=ordinalValues(value).find(i=>i==="1"||i==="2"||i==="3");return first?Number(first) as 1|2|3:null}
export function schoolStage(value:unknown,className?:unknown):SchoolStage{const source=normalizeArabic(`${clean(value)} ${clean(className)}`);if(source.includes("متوسط")||source.includes("middle"))return "middle";return "secondary"}
export function stageLabel(stage:SchoolStage){return stage==="middle"?"المرحلة المتوسطة":"المرحلة الثانوية"}
export function gradeLabel(grade:number,stage:SchoolStage="secondary"){if(grade===1)return stage==="middle"?"الأول المتوسط":"الأول الثانوي";if(grade===2)return stage==="middle"?"الثاني المتوسط":"الثاني الثانوي";if(grade===3)return stage==="middle"?"الثالث المتوسط":"الثالث الثانوي";return ""}
export function arabicNumber(value:string|number){return String(value).replace(/\d/g,d=>ARABIC_DIGITS[Number(d)]||d)}
export function sectionNumber(value:unknown,className?:unknown){const explicitNumbers=westernDigits(value).match(/\d+/g)||[];if(explicitNumbers.length)return explicitNumbers[explicitNumbers.length-1];const explicitOrdinals=ordinalValues(value);if(explicitOrdinals.length)return explicitOrdinals[explicitOrdinals.length-1];const classNumbers=westernDigits(className).match(/\d+/g)||[];if(classNumbers.length>=2)return classNumbers[classNumbers.length-1];if(classNumbers.length===1){const classOrdinals=ordinalValues(className);return classOrdinals.length>=2?classOrdinals[classOrdinals.length-1]:classNumbers[0]}const classOrdinals=ordinalValues(className);return classOrdinals.length>=2?classOrdinals[classOrdinals.length-1]:""}
export function canonicalClassName(grade:number,section:string,stage:SchoolStage="secondary"){return `${gradeLabel(grade,stage)} ${arabicNumber(section)}`.trim()}
// Preserve every existing secondary id exactly. Middle-school ids are namespaced so no class can collide.
export function classId(grade:number,section:string,stage:SchoolStage="secondary"){return stage==="secondary"?`${grade}-${westernDigits(section)}`:`middle-${grade}-${westernDigits(section)}`}
export function normalizeClassRecord(value:Partial<SchoolClass>&{className?:string;name?:string}){const sourceName=value.className||value.name;const stage=schoolStage(value.stage,sourceName);const grade=gradeNumber(value.grade||sourceName);const section=sectionNumber(value.section,sourceName);if(!grade||!section)return null;return{id:classId(grade,section,stage),stage,grade,section,name:canonicalClassName(grade,section,stage),active:value.active!==false,createdAt:value.createdAt,updatedAt:value.updatedAt} satisfies SchoolClass}
export function normalizeStudentRecord(value:Record<string,unknown>,fallbackId=""){const name=clean(value.name);const className=clean(value.className||value.class);const stage=schoolStage(value.stage,className);const grade=gradeNumber(value.grade||className);const section=sectionNumber(value.section,className);const code=clean(value.code||value.accessCode||value.studentCode||fallbackId).toUpperCase();if(!name||!grade||!section||!code)return null;return{...value,id:code,code,name,stage,grade,section,className:canonicalClassName(grade,section,stage),active:value.active!==false&&value.rosterActive!==false} as SchoolStudent}
export function nextStudentCode(students:Array<Pick<SchoolStudent,"code">>,grade:number,stage:SchoolStage="secondary"){const used=new Set(students.map(s=>clean(s.code).toUpperCase()));const prefix=stage==="middle"?`MT${grade}`:`TH${grade}`;for(let number=1;number<=999;number+=1){const code=`${prefix}${String(number).padStart(3,"0")}`;if(!used.has(code))return code}return ""}
export function subjectAssignments(assignments:AssignmentLike[]|undefined,subjectId:string){return(Array.isArray(assignments)?assignments:[]).filter(i=>clean(i.subjectId)===clean(subjectId))}
export function assignmentMatchesClass(assignment:AssignmentLike,grade:number,section:string,stage:SchoolStage="secondary"){const assignedStage=schoolStage(assignment.stage);if(assignedStage!==stage)return false;const assignedGrade=gradeNumber(assignment.grade);if(!assignedGrade||assignedGrade!==grade)return false;const assignedSection=sectionNumber(assignment.section);return !assignedSection||assignedSection===westernDigits(section)}
export function studentMatchesAssignments(student:Pick<SchoolStudent,"stage"|"grade"|"section">,assignments:AssignmentLike[]|undefined,subjectId:string){return subjectAssignments(assignments,subjectId).some(a=>assignmentMatchesClass(a,student.grade,student.section,student.stage))}
export function classMatchesAssignments(schoolClass:Pick<SchoolClass,"stage"|"grade"|"section">,assignments:AssignmentLike[]|undefined,subjectId:string){return subjectAssignments(assignments,subjectId).some(a=>assignmentMatchesClass(a,schoolClass.grade,schoolClass.section,schoolClass.stage))}
export function studentIdentity(student:Pick<SchoolStudent,"stage"|"name"|"grade"|"section">){return `${normalizeArabic(student.name)}|${student.stage}|${student.grade}|${westernDigits(student.section)}`}
