"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import "./students-admin.css";
import "./students-command-v3.css";

type Student={id:string;code:string;name:string;grade:number;section:string;className:string;active:boolean};
type SchoolClass={id:string;grade:number;section:string;name:string;active:boolean};
type ImportRow={name:string;grade?:number|null;section?:string;code?:string;source?:string};
const GRADES=[{value:1,label:"الأول الثانوي"},{value:2,label:"الثاني الثانوي"},{value:3,label:"الثالث الثانوي"}];
const ar=(v:string|number)=>String(v).replace(/\d/g,d=>"٠١٢٣٤٥٦٧٨٩"[Number(d)]||d);
const normalizeDigits=(v:string)=>v.replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d)));
async function api(input:RequestInfo|URL,init:RequestInit={},timeoutMs=20000){const c=new AbortController();const t=window.setTimeout(()=>c.abort(),timeoutMs);try{const r=await fetch(input,{...init,credentials:"same-origin",signal:c.signal,cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){if(r.status===401)throw new Error("انتهت جلسة الإدارة. سجّل الدخول من جديد ثم أعد المحاولة.");throw new Error(d.message||`تعذر تنفيذ العملية (${r.status})`)}return d}finally{window.clearTimeout(t)}}
export default function AdminStudentsPage(){
 const[students,setStudents]=useState<Student[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]);const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const[grade,setGrade]=useState(1);const[classId,setClassId]=useState("");const[search,setSearch]=useState("");const[newStudent,setNewStudent]=useState("");const[showClass,setShowClass]=useState(false);const[newClassSection,setNewClassSection]=useState("");const[showUpload,setShowUpload]=useState(false);const[file,setFile]=useState<File|null>(null);const[previewRows,setPreviewRows]=useState<ImportRow[]>([]);const[editing,setEditing]=useState<Student|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const d=await api("/api/admin/students");setStudents(Array.isArray(d.students)?d.students:[]);setClasses(Array.isArray(d.classes)?d.classes:[]);setMessage("")}catch(e){setMessage(e instanceof Error?e.message:"تعذر تحميل الطلاب")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const gradeClasses=useMemo(()=>classes.filter(x=>x.grade===grade&&x.active!==false).sort((a,b)=>Number(a.section)-Number(b.section)),[classes,grade]);useEffect(()=>{if(!gradeClasses.length){setClassId("");return}if(!gradeClasses.some(x=>x.id===classId))setClassId(gradeClasses[0].id)},[gradeClasses,classId]);
 const selectedClass=useMemo(()=>classes.find(x=>x.id===classId&&x.active!==false)||null,[classes,classId]);const classStudents=useMemo(()=>selectedClass?students.filter(s=>s.active!==false&&s.grade===selectedClass.grade&&s.section===selectedClass.section).sort((a,b)=>a.name.localeCompare(b.name,"ar")):[],[students,selectedClass]);const visibleStudents=useMemo(()=>{const q=search.trim().toLocaleLowerCase("ar");return q?classStudents.filter(s=>s.name.toLocaleLowerCase("ar").includes(q)||s.code.toLowerCase().includes(q)):classStudents},[classStudents,search]);const gradeCount=useMemo(()=>students.filter(s=>s.active!==false&&s.grade===grade).length,[students,grade]);const editClasses=useMemo(()=>classes.filter(c=>c.active!==false&&c.grade===editing?.grade).sort((a,b)=>Number(a.section)-Number(b.section)),[classes,editing?.grade]);
 async function addClass(e:FormEvent){e.preventDefault();const section=normalizeDigits(newClassSection).replace(/\D/g,"").trim();if(!/^[1-8]$/.test(section))return setMessage("رقم الفصل يجب أن يكون من ١ إلى ٨.");setBusy(true);try{const d=await api("/api/admin/students/classes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({grade,section})});const c=d.schoolClass as SchoolClass;if(!c?.id)throw new Error("تعذر إنشاء الفصل");setClasses(x=>[...x.filter(i=>i.id!==c.id),{...c,active:true}]);setClassId(c.id);setShowClass(false);setNewClassSection("");setMessage(`تمت إضافة ${c.name}.`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر إضافة الفصل")}finally{setBusy(false)}}
 async function addStudent(e:FormEvent){e.preventDefault();if(!selectedClass)return setMessage("اختر الفصل أولًا.");const name=newStudent.replace(/\s+/g," ").trim();if(name.length<3)return setMessage("اكتب اسم الطالب كاملًا.");setBusy(true);try{const d=await api("/api/admin/students",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,grade:selectedClass.grade,section:selectedClass.section})});setNewStudent("");if(d.student?.id)setStudents(current=>[...current.filter(s=>s.id!==d.student.id),d.student as Student]);else await load();setMessage(`تمت إضافة ${name} • الكود ${d.student?.code||"تم إنشاؤه"}`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر إضافة الطالب")}finally{setBusy(false)}}
 async function saveEdit(){if(!editing)return;const target=classes.find(c=>c.active!==false&&c.grade===editing.grade&&c.section===editing.section);if(!target)return setMessage("اختر فصلًا موجودًا من القائمة.");setBusy(true);try{await api(`/api/admin/students/${editing.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:editing.name,grade:target.grade,section:target.section})});const updated={...editing,grade:target.grade,section:target.section,className:target.name,active:true};setStudents(current=>current.map(s=>s.id===updated.id?updated:s));setEditing(null);setGrade(target.grade);setClassId(target.id);setMessage(`تم نقل الطالب إلى ${target.name} وحفظ التعديل.`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر نقل الطالب")}finally{setBusy(false)}}
 async function removeStudent(s:Student){if(!confirm(`حذف ${s.name} من القائمة الحالية؟`))return;setBusy(true);try{await api(`/api/admin/students/${s.id}`,{method:"DELETE"});setStudents(current=>current.filter(item=>item.id!==s.id));setMessage("تم حذف الطالب من القائمة الحالية.")}catch(e){setMessage(e instanceof Error?e.message:"تعذر حذف الطالب")}finally{setBusy(false)}}
 async function removeClass(item:SchoolClass){const count=students.filter(s=>s.active!==false&&s.grade===item.grade&&s.section===item.section).length;if(!confirm(count?`حذف ${item.name} وفيه ${ar(count)} طالبًا؟\nستبقى السجلات التاريخية محفوظة.`:`حذف ${item.name}؟`))return;setBusy(true);try{await api(`/api/admin/students/classes/${item.id}${count?"?force=1":""}`,{method:"DELETE"},30000);setClassId("");await load();setMessage(`تم حذف ${item.name} مع حفظ السجلات السابقة.`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر حذف الفصل")}finally{setBusy(false)}}
 async function previewFile(){if(!file||!selectedClass)return setMessage("اختر الفصل والملف أولًا.");setBusy(true);setPreviewRows([]);try{const f=new FormData();f.append("file",file);f.append("defaultGrade",String(selectedClass.grade));f.append("defaultSection",selectedClass.section);const d=await api("/api/admin/students/import",{method:"POST",body:f},30000);const rows=Array.isArray(d.rows)?d.rows:[];setPreviewRows(rows);setMessage(`تمت قراءة ${ar(rows.length)} اسمًا.`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر قراءة الملف")}finally{setBusy(false)}}
 async function importPreview(){if(!previewRows.length||!selectedClass)return;setBusy(true);try{const rows=previewRows.map(r=>({...r,grade:r.grade||selectedClass.grade,section:r.section||selectedClass.section}));const d=await api("/api/admin/students/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows})},30000);await load();setShowUpload(false);setFile(null);setPreviewRows([]);setMessage(`تمت إضافة ${ar(d.imported||0)} طالبًا.`)}catch(e){setMessage(e instanceof Error?e.message:"تعذر اعتماد القائمة")}finally{setBusy(false)}}
 return <section className="roster-v3" dir="rtl"><header className="roster-v3-hero"><div><small>إدارة الطلاب والفصول</small><h1>الطلاب والفصول</h1><p>اختر الصف والفصل، وانقل الطالب مباشرة إلى أي فصل مسجل.</p></div><div className="roster-v3-hero-actions"><button onClick={()=>setShowClass(true)}>+ إضافة فصل</button><button className="primary" disabled={!selectedClass} onClick={()=>setShowUpload(true)}>رفع كشف كامل</button></div></header>{message&&<div className="roster-v3-message">{message}</div>}
 <section className="roster-v3-step"><header><span>١</span><div><b>اختر الصف</b><small>{ar(gradeCount)} طالبًا</small></div></header><div className="roster-v3-grades">{GRADES.map(g=><button key={g.value} className={grade===g.value?"active":""} onClick={()=>{setGrade(g.value);setSearch("")}}>{g.label}<small>{ar(students.filter(s=>s.active!==false&&s.grade===g.value).length)}</small></button>)}</div></section>
 <section className="roster-v3-step"><header><span>٢</span><div><b>اختر الفصل</b><small>القائمة الرسمية للفصل المحدد</small></div></header><div className="roster-v3-classes">{gradeClasses.map(c=><button key={c.id} className={classId===c.id?"active":""} onClick={()=>{setClassId(c.id);setSearch("")}}><b>فصل {ar(c.section)}</b><small>{ar(students.filter(s=>s.active!==false&&s.grade===c.grade&&s.section===c.section).length)} طالب</small></button>)}<button className="add-class" onClick={()=>setShowClass(true)}>＋<small>فصل جديد</small></button></div></section>
 {selectedClass?<section className="roster-v3-work"><header className="roster-v3-work-head"><div><small>٣ • قائمة العمل</small><h2>{selectedClass.name}</h2><p>{ar(classStudents.length)} طالبًا</p></div><div><button className="upload" onClick={()=>setShowUpload(true)}>رفع كشف</button><button className="delete" onClick={()=>void removeClass(selectedClass)} disabled={busy}>حذف الفصل</button></div></header><form className="roster-v3-add-student" onSubmit={addStudent}><div><b>إضافة طالب لهذا الفصل</b><small>الصف والفصل محددان تلقائيًا</small></div><input value={newStudent} onChange={e=>setNewStudent(e.target.value)} placeholder="اسم الطالب كاملًا"/><button disabled={busy}>+ إضافة</button></form><div className="roster-v3-listbar"><div><b>الطلاب</b><small>«تعديل / نقل» يعرض الفصول المتاحة</small></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم أو الكود"/></div>{loading?<div className="roster-v3-empty">جارٍ التحميل…</div>:<div className="roster-v3-table"><div className="head"><span>م</span><span>اسم الطالب</span><span>الكود</span><span>الإجراء</span></div>{visibleStudents.map((s,i)=><div className="row" key={s.id}><span>{ar(i+1)}</span><strong>{s.name}</strong><code>{s.code}</code><div><button onClick={()=>setEditing({...s})}>تعديل / نقل</button><button className="danger" onClick={()=>void removeStudent(s)}>حذف</button></div></div>)}{!visibleStudents.length&&<div className="roster-v3-empty">لا توجد أسماء في هذا الفصل.</div>}</div>}</section>:<section className="roster-v3-select-hint"><b>اختر فصلًا لتظهر قائمته.</b></section>}
 {showClass&&<div className="roster-v3-modal"><form onSubmit={addClass}><header><div><small>{GRADES.find(g=>g.value===grade)?.label}</small><h2>إضافة فصل</h2></div><button type="button" onClick={()=>setShowClass(false)}>×</button></header><label>رقم الفصل<input inputMode="numeric" value={newClassSection} onChange={e=>setNewClassSection(e.target.value)} autoFocus/></label><footer><button type="button" onClick={()=>setShowClass(false)}>إلغاء</button><button className="primary" disabled={busy}>إضافة الفصل</button></footer></form></div>}
 {showUpload&&selectedClass&&<div className="roster-v3-modal"><section className="roster-v3-upload"><header><div><small>{selectedClass.name}</small><h2>رفع كشف الطلاب</h2></div><button type="button" onClick={()=>{setShowUpload(false);setFile(null);setPreviewRows([])}}>×</button></header><label className="roster-v3-drop"><input type="file" accept=".xlsx,.xls,.csv,.pdf,application/pdf" onChange={e=>{setFile(e.target.files?.[0]||null);setPreviewRows([])}}/><b>{file?.name||"اختر Excel أو CSV أو PDF"}</b></label><button className="roster-v3-read" onClick={()=>void previewFile()} disabled={!file||busy}>قراءة ومعاينة</button>{previewRows.length>0&&<div className="roster-v3-preview"><div><b>وجدنا {ar(previewRows.length)} اسمًا</b>{previewRows.slice(0,8).map((r,i)=><span key={`${r.name}-${i}`}>{ar(i+1)}. {r.name}</span>)}</div><button onClick={()=>void importPreview()} disabled={busy}>اعتماد وإضافة القائمة</button></div>}</section></div>}
 {editing&&<div className="roster-v3-modal"><section><header><div><small>الكود ثابت: {editing.code}</small><h2>تعديل أو نقل الطالب</h2></div><button type="button" onClick={()=>setEditing(null)}>×</button></header><label>اسم الطالب<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>الصف<select value={editing.grade} onChange={e=>{const g=Number(e.target.value);const first=classes.filter(c=>c.active!==false&&c.grade===g).sort((a,b)=>Number(a.section)-Number(b.section))[0];setEditing({...editing,grade:g,section:first?.section||""})}}>{GRADES.map(g=><option key={g.value} value={g.value}>{g.label}</option>)}</select></label><label>الفصل<select value={editing.section} onChange={e=>setEditing({...editing,section:e.target.value})}><option value="">اختر الفصل</option>{editClasses.map(c=><option key={c.id} value={c.section}>فصل {ar(c.section)} — {c.name}</option>)}</select></label>{!editClasses.length&&<p>لا توجد فصول مسجلة لهذا الصف. أضف الفصل أولًا.</p>}<footer><button onClick={()=>setEditing(null)}>إلغاء</button><button className="primary" onClick={()=>void saveEdit()} disabled={busy||!editing.section}>نقل وحفظ</button></footer></section></div>}
 </section>;
}