plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ostadlahooni.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ostadlahooni.app'
        minSdk 24
        targetSdk 35
        versionCode 9
        versionName '1.5.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
