"use client";
import {useEffect,useState} from "react";
import {useTeacherClient} from "../../../lib/teacher-client";
import {useGradePlan} from "../../../lib/use-grade-plan";

type Selection={className:string;sectionId:string};
function readSelection(activeSection=""):Selection{if(typeof document==="undefined")return{className:"",sectionId:activeSection};const root=document.querySelector<HTMLElement>(".grades-page");let className="",sectionId=activeSection;root?.querySelectorAll<HTMLSelectElement>("select").forEach(sel=>{const label=(sel.closest("label")?.textContent||"").trim();if(!className&&/الفصل/.test(label))className=sel.value.trim();if(/(الوحدة|الفترة)/.test(label)&&sel.value.trim())sectionId=sel.value.trim()});return{className,sectionId}}
export default function GradeApproval(){const s=useTeacherClient(),{activePlan}=useGradePlan(true);const[selection,setSelection]=useState<Selection>({className:"",sectionId:""}),[status,setStatus]=useState("open"),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 useEffect(()=>{const sync=()=>setSelection(readSelection(activePlan?.sections?.[0]?.id||""));sync();const onChange=()=>setTimeout(sync,0);document.addEventListener("change",onChange);const timer=setInterval(sync,1200);return()=>{document.removeEventListener("change",onChange);clearInterval(timer)}},[activePlan?.id]);
 const section=activePlan?.sections.find(x=>x.id===selection.sectionId)||activePlan?.sections[0]||null;
 useEffect(()=>{if(!s.subjectKey||!activePlan||!selection.className||!section){document.documentElement.dataset.gradeApproved="0";return}setNote("");fetch(`/api/teacher/grade-status?subjectId=${encodeURIComponent(s.subjectKey)}&className=${encodeURIComponent(selection.className)}&planId=${encodeURIComponent(activePlan.id)}&sectionId=${encodeURIComponent(section.id)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{const next=d.status==="approved"?"approved":"open";setStatus(next);document.documentElement.dataset.gradeApproved=next==="approved"?"1":"0"}).catch(()=>{})},[s.subjectKey,activePlan?.id,selection.className,section?.id]);
 async function act(action:"approve"|"open"){if(!s.subjectKey||!activePlan||!selection.className||!section)return;setBusy(true);setNote("");try{const r=await fetch("/api/teacher/grade-status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subjectId:s.subjectKey,className:selection.className,planId:activePlan.id,sectionId:section.id,sectionLabel:section.label,action})});const d=await r.json();if(!r.ok)throw new Error(d.message||"تعذر التحديث");setStatus(d.status);document.documentElement.dataset.gradeApproved=d.status==="approved"?"1":"0";setNote(d.status==="approved"?"تم اعتماد الرصد وقفل جدول هذه الوحدة.":"تم فتح الرصد للتعديل. عدّل الدرجات ثم أعد الاعتماد.")}catch(e){setNote(e instanceof Error?e.message:"تعذر التحديث")}finally{setBusy(false)}}
 const ready=Boolean(selection.className&&section);
 return <section dir="rtl" className="grade-approval-panel" style={{maxWidth:1500,margin:"18px auto 28px",padding:"0 18px",color:"#000"}}><div style={{padding:16,borderRadius:16,border:"2px solid #b8c9c0",background:status==="approved"?"#edf9f1":"#fff8df",boxShadow:"0 8px 24px rgba(0,0,0,.06)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><div style={{fontSize:13,fontWeight:800,marginBottom:5}}>حالة رصد الوحدة / الفترة</div><b style={{fontSize:18}}>{!ready?"اختر الفصل والوحدة أولًا":status==="approved"?"🔒 تم الرصد واعتماد الدرجات":"🟠 الرصد مفتوح للتعديل"}</b>{ready?<div style={{fontSize:14,marginTop:5}}>{selection.className} — {section?.label}</div>:null}</div><button data-grade-approval="1" disabled={busy||!ready} onClick={()=>void act(status==="approved"?"open":"approve")} style={{padding:"12px 22px",borderRadius:11,border:"1px solid #777",background:"#fff",color:"#000",fontWeight:900,fontSize:15,cursor:ready?"pointer":"not-allowed"}}>{busy?"جارٍ التحديث…":status==="approved"?"✏️ فتح الرصد للتعديل":"🔒 اعتماد وإنهاء رصد الوحدة"}</button></div>{note?<div style={{marginTop:10,fontWeight:800}}>{note}</div>:null}</div><style>{`html[data-grade-approved="1"] .grades-page input[type="number"],html[data-grade-approved="1"] .grades-page textarea{pointer-events:none;opacity:.58}html[data-grade-approved="1"] .grades-page table button{pointer-events:none;opacity:.58}`}</style></section>}
