"use client";
import {useEffect,useState} from "react";
import {useTeacherClient} from "../../../lib/teacher-client";
import {useGradePlan} from "../../../lib/use-grade-plan";
type Status="tracking"|"editing"|"approved";
function normalize(v:unknown):Status{return v==="approved"?"approved":v==="editing"?"editing":"tracking"}
function cleanText(v:string){return v.replace(/\s*(🟢|🟠|🔴|✓|●|↻|🔒)?\s*(قيد الرصد|إعادة الرصد|تم الرصد|تم الرصد واعتماده|إعادة الرصد \/ تعديل)\s*$/u,"").trim()}
function findSectionFromDom(sections:{id:string;label:string}[],fallback=""){if(typeof document==="undefined")return fallback;const selected=document.querySelector<HTMLElement>('[aria-selected="true"],.active,[data-active="true"]');if(selected){const t=cleanText(selected.textContent||"");const hit=sections.find(x=>t===x.label||t.includes(x.label));if(hit)return hit.id}for(const sel of Array.from(document.querySelectorAll<HTMLSelectElement>("select"))){const opt=sel.options[sel.selectedIndex];const t=cleanText(opt?.textContent||"");const hit=sections.find(x=>t===x.label||t.includes(x.label));if(hit)return hit.id}return fallback}
function paintTabs(statuses:Record<string,Status>,sections:{id:string;label:string}[]){if(typeof document==="undefined")return;document.querySelectorAll<HTMLElement>("button,[role=tab],option").forEach(el=>{if(el.closest('.grade-approval-panel'))return;const raw=cleanText(el.textContent||"");const sec=sections.find(x=>raw===x.label||raw.includes(x.label));if(!sec)return;const st=statuses[sec.id]||"tracking",suffix=st==="approved"?" 🔴 تم الرصد":st==="editing"?" 🟠 إعادة الرصد":" 🟢 قيد الرصد";if(el instanceof HTMLOptionElement)el.textContent=raw+suffix;else{el.dataset.gradeStatus=st;let badge=el.querySelector<HTMLElement>(".grade-status-badge");if(!badge){badge=document.createElement("span");badge.className="grade-status-badge";el.appendChild(badge)}badge.textContent=suffix}})}
export default function GradeApproval(){const s=useTeacherClient(),{activePlan}=useGradePlan(true);const[sectionId,setSectionId]=useState(""),[statuses,setStatuses]=useState<Record<string,Status>>({}),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 useEffect(()=>{if(!activePlan?.sections.length)return;const sync=()=>setSectionId(cur=>findSectionFromDom(activePlan.sections,cur||activePlan.sections[0].id));sync();const click=(e:Event)=>{const target=(e.target as HTMLElement)?.closest<HTMLElement>("button,[role=tab],option,label");if(!target)return;const t=cleanText(target.textContent||"");const hit=activePlan.sections.find(x=>t===x.label||t.includes(x.label));if(hit)setTimeout(()=>setSectionId(hit.id),0)};document.addEventListener("click",click,true);document.addEventListener("change",sync,true);return()=>{document.removeEventListener("click",click,true);document.removeEventListener("change",sync,true)}},[activePlan?.id]);
 const section=activePlan?.sections.find(x=>x.id===sectionId)||activePlan?.sections[0]||null;const status:Status=section?(statuses[section.id]||"tracking"):"tracking";
 useEffect(()=>{const subjectKey=s.subjectKey;if(!subjectKey||!activePlan)return;let cancelled=false;Promise.all(activePlan.sections.map(async sec=>{try{const r=await fetch(`/api/teacher/grade-status?subjectId=${encodeURIComponent(subjectKey)}&planId=${encodeURIComponent(activePlan.id)}&sectionId=${encodeURIComponent(sec.id)}`,{cache:"no-store"});const d=await r.json();return[sec.id,normalize(d.status)] as const}catch{return[sec.id,"tracking"] as const}})).then(rows=>{if(cancelled)return;const next=Object.fromEntries(rows) as Record<string,Status>;setStatuses(next);paintTabs(next,activePlan.sections)});return()=>{cancelled=true}},[s.subjectKey,activePlan?.id]);
 useEffect(()=>{document.documentElement.dataset.gradeApproved=status==="approved"?"1":"0";if(activePlan)paintTabs(statuses,activePlan.sections)},[section?.id,status,statuses,activePlan]);
 async function change(next:Status){const subjectKey=s.subjectKey;if(!subjectKey||!activePlan||!section||busy||next===status)return;if(status==="approved"&&next==="tracking")return;setBusy(true);setNote("");try{const r=await fetch("/api/teacher/grade-status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subjectId:subjectKey,planId:activePlan.id,sectionId:section.id,sectionLabel:section.label,action:next})});const d=await r.json();if(!r.ok)throw new Error(d.message||"تعذر التحديث");const actual=normalize(d.status),updated={...statuses,[section.id]:actual};setStatuses(updated);paintTabs(updated,activePlan.sections);document.documentElement.dataset.gradeApproved=actual==="approved"?"1":"0";setNote(actual==="approved"?"تم اعتماد هذه الوحدة وقفل جدولها فقط.":actual==="editing"?"تم فتح هذه الوحدة للتعديل.":"هذه الوحدة قيد الرصد.")}catch(e){setNote(e instanceof Error?e.message:"تعذر التحديث")}finally{setBusy(false)}}
 if(!section)return null;const choices:[Status,string,string][]=[["tracking","🟢","قيد الرصد"],["editing","🟠","إعادة الرصد / تعديل"],["approved","🔴","تم الرصد واعتماده"]];return <section dir="rtl" className="grade-approval-panel" style={{maxWidth:1500,margin:"12px auto 24px",padding:"0 18px",color:"#111"}}><div style={{fontWeight:950,fontSize:16,marginBottom:8}}>حالة رصد: {section.label}</div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{choices.map(([value,icon,title])=><button key={value} type="button" disabled={busy||(status==="approved"&&value==="tracking")} onClick={()=>void change(value)} style={{padding:"11px 18px",borderRadius:12,border:status===value?"3px solid #111":"1px solid #aaa",background:value==="tracking"?"#dff5e7":value==="editing"?"#ffedcc":"#ffdede",color:"#111",fontWeight:950,fontSize:14,cursor:"pointer"}}>{icon} {title}{status===value?" ✓":""}</button>)}</div>{status==="approved"?<div style={{marginTop:10,padding:"10px 12px",borderRadius:9,background:"#fff0f0",border:"1px solid #e4aaaa",fontWeight:900}}>🔒 {section.label} مقفلة. لتعديل درجاتها اختر «إعادة الرصد / تعديل». تغيير الوحدة لا يتأثر بهذا القفل.</div>:null}{note?<div style={{marginTop:8,fontWeight:850}}>{note}</div>:null}<style>{`html[data-grade-approved="1"] main table{opacity:.48!important;filter:grayscale(.45)!important;pointer-events:none!important}html[data-grade-approved="1"] main [data-grade-cell]{pointer-events:none!important}html[data-grade-approved="1"] main input[type="number"]{pointer-events:none!important}.grade-status-badge{display:inline-block!important;margin-inline-start:7px!important;padding:3px 7px!important;border-radius:999px!important;font-weight:950!important;font-size:11px!important;white-space:nowrap!important}[data-grade-status="approved"] .grade-status-badge{color:#8d1616!important;background:#ffdede!important}[data-grade-status="editing"] .grade-status-badge{color:#8a4b00!important;background:#ffedcc!important}[data-grade-status="tracking"] .grade-status-badge{color:#126b37!important;background:#dff5e7!important}`}</style></section>}
