import { NextResponse } from "next/server";
import { adminDb } from "../../../../lib/server/firebase-admin";
import { requireSession } from "../../../../lib/server/portal-auth";
import { normalizeAssignments } from "../../../../lib/teacher-assignments";
function clean(v:unknown,n=100){return String(v??"").replace(/\s+/g," ").trim().slice(0,n)}
function assigned(session:NonNullable<Awaited<ReturnType<typeof requireSession>>>,subjectId:string){return Boolean(session.user&&/^[a-z0-9_-]+$/i.test(subjectId)&&normalizeAssignments(session.user.assignments,session.user.subjectIds).some(x=>x.subjectId===subjectId))}
function docId(planId:string,sectionId:string){return Buffer.from(`${planId}\u001f${sectionId}`).toString("base64url")}
export async function GET(request:Request){const session=await requireSession("teacher");if(!session)return NextResponse.json({ok:false},{status:401});try{const u=new URL(request.url),subjectId=clean(u.searchParams.get("subjectId"),80),planId=clean(u.searchParams.get("planId"),80),sectionId=clean(u.searchParams.get("sectionId"),80);if(!assigned(session,subjectId))return NextResponse.json({ok:false},{status:403});if(!planId||!sectionId)return NextResponse.json({ok:true,status:"open"});const snap=await adminDb().doc(`portalV2Data/${session.userId}/subjects/${subjectId}/gradeStatuses/${docId(planId,sectionId)}`).get();const d=snap.exists?snap.data()||{}:{};return NextResponse.json({ok:true,status:d.status==="approved"?"approved":"open",approvedAt:d.approvedAt||null,openedAt:d.openedAt||null,sectionLabel:d.sectionLabel||""},{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({ok:false},{status:500})}}
export async function POST(request:Request){const session=await requireSession("teacher");if(!session)return NextResponse.json({ok:false},{status:401});try{const b=await request.json() as Record<string,unknown>,subjectId=clean(b.subjectId,80),planId=clean(b.planId,80),sectionId=clean(b.sectionId,80),sectionLabel=clean(b.sectionLabel,120),action=clean(b.action,20);if(!assigned(session,subjectId))return NextResponse.json({ok:false},{status:403});if(!planId||!sectionId||!["approve","open"].includes(action))return NextResponse.json({ok:false,message:"بيانات الحالة غير مكتملة."},{status:400});const now=new Date().toISOString(),status=action==="approve"?"approved":"open";await adminDb().doc(`portalV2Data/${session.userId}/subjects/${subjectId}/gradeStatuses/${docId(planId,sectionId)}`).set({teacherId:session.userId,subjectId,planId,sectionId,sectionLabel,status,scope:"all-classes",updatedAt:now,...(status==="approved"?{approvedAt:now}:{openedAt:now})},{merge:true});return NextResponse.json({ok:true,status,updatedAt:now})}catch{return NextResponse.json({ok:false,message:"تعذر تحديث حالة الرصد."},{status:500})}}
