"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { collection, doc, onSnapshot, updateDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import { ClientTenant, migrateLegacyHistoryStudents, tenantStudentsPath } from "../../../lib/firestore-tenant-client";
import { RESEARCH_MAX, subjectLabel as getSubjectLabel } from "../../../lib/academic-config";
import { useTeacherClient } from "../../../lib/teacher-client";
import "../grades/register.css";

type Student = { id: string; name?: string; class?: string; research?: number; researchScore?: number };

export default function ResearchPage() {
  const session = useTeacherClient();
  const tenant = useMemo<ClientTenant | null>(()=>session?.teacherId&&session?.subjectKey?{teacherId:session.teacherId,teacherName:session.teacherName||"",subjectKey:session.subjectKey as any}:null,[session?.teacherId,session?.teacherName,session?.subjectKey]);
  const [students, setStudents] = useState<Student[]>([]);
  const [selectedClass, setSelectedClass] = useState("");
  const [scores, setScores] = useState<Record<string, number>>({});
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");

  useEffect(()=>{ if(!tenant){ setMessage("انتهت جلسة المعلم. سجّل الدخول من جديد."); return; } let unsubscribe=()=>{};let cancelled=false; migrateLegacyHistoryStudents(db,tenant).catch(()=>{}).finally(()=>{ if(cancelled) return; unsubscribe=onSnapshot(collection(db,tenantStudentsPath(tenant)),snapshot=>{const list=snapshot.docs.map(item=>({id:item.id,...item.data()})) as Student[];list.sort((a,b)=>(a.name||"").localeCompare(b.name||"","ar"));setStudents(list);},()=>setMessage("تعذر تحميل طلاب مادة المعلم الحالي"));}); return ()=>{cancelled=true;unsubscribe();}; },[tenant]);

  const classes = useMemo(() => Array.from(new Set(students.map(s=>(s.class||"").trim()).filter(Boolean))).sort((a,b)=>a.localeCompare(b,"ar")), [students]);
  const classStudents = useMemo(() => students.filter(s=>(s.class||"").trim()===selectedClass), [students,selectedClass]);
  useEffect(()=>{if(!classes.length){setSelectedClass("");return}if(!selectedClass||!classes.includes(selectedClass))setSelectedClass(classes[0])},[classes,selectedClass]);
  useEffect(() => { setScores(Object.fromEntries(classStudents.map(student=>[student.id,Number(student.researchScore??student.research??0)]))); }, [classStudents]);
  function updateScore(studentId:string,raw:string){const value=Math.max(0,Math.min(RESEARCH_MAX,Number(raw)||0));setScores(current=>({...current,[studentId]:value}));}
  function adjustScore(studentId:string,amount:number){setScores(current=>({...current,[studentId]:Math.max(0,Math.min(RESEARCH_MAX,Number(current[studentId]||0)+amount))}));}
  function applyAll(){setScores(Object.fromEntries(classStudents.map(student=>[student.id,RESEARCH_MAX])));}
  function studentRef(studentId:string){if(!tenant)throw new Error("missing tenant");return doc(db,tenantStudentsPath(tenant),studentId);}
  async function save(){if(!selectedClass||!tenant)return setMessage("اختر الفصل أولًا");try{setSaving(true);setMessage("");await Promise.all(classStudents.map(student=>{const score=Number(scores[student.id]||0);return updateDoc(studentRef(student.id),{researchScore:score,research:score,researchUpdatedAt:new Date().toISOString(),teacherId:tenant.teacherId,subjectKey:tenant.subjectKey})}));setMessage("تم حفظ درجات البحث بنجاح");}catch(error){console.error(error);setMessage("تعذر حفظ درجات البحث")}finally{setSaving(false)}}
  async function clearAll(){if(!selectedClass||!tenant)return setMessage("اختر الفصل أولًا");if(!window.confirm(`هل تريد حذف جميع درجات البحث للفصل ${selectedClass}؟`))return;try{setSaving(true);setScores(Object.fromEntries(classStudents.map(student=>[student.id,0])));await Promise.all(classStudents.map(student=>updateDoc(studentRef(student.id),{researchScore:0,research:0,researchUpdatedAt:new Date().toISOString()})));setMessage("تم حذف جميع درجات البحث")}catch(error){console.error(error);setMessage("تعذر حذف درجات البحث")}finally{setSaving(false)}}
  const subjectLabel=getSubjectLabel(tenant?.subjectKey);

  return <main className="gradebook-page research-page" dir="rtl"><div className="gradebook-wrap"><section className="gradebook-card">
    <style>{`.research-page .research-mobile-list{display:none}.research-page .gradebook-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}.research-page .research-table{min-width:720px}.research-page .research-grade-link{display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 17px;border-radius:13px;background:#17263d;color:#fff;font-weight:900;text-decoration:none;white-space:nowrap;box-shadow:0 8px 20px rgba(23,38,61,.2)}.research-page .research-grade-link:active{transform:scale(.98)}@media(max-width:700px){.research-page .gradebook-card{padding:12px!important;border-radius:18px!important}.research-page .gradebook-head{display:block!important}.research-page .gradebook-head h1{font-size:21px!important}.research-page .gradebook-actions{display:grid!important;grid-template-columns:1fr 1fr;gap:9px!important;width:100%;margin-top:14px}.research-page .gradebook-actions label{grid-column:1/-1;width:100%}.research-page .gradebook-actions select{width:100%;min-height:48px}.research-page .gradebook-actions button,.research-page .research-grade-link{width:100%;min-height:48px;padding:8px;font-size:12px}.research-page .research-desktop-table{display:none!important}.research-page .research-mobile-list{display:grid!important;gap:10px;margin-top:14px}.research-page .research-student-card{display:grid;grid-template-columns:1fr auto;align-items:center;gap:12px;padding:13px;border:1px solid #dfe7ee;border-radius:16px;background:#fff;box-shadow:0 8px 22px rgba(20,46,70,.07)}.research-page .research-student-info{min-width:0}.research-page .research-student-info strong{display:block;font-size:14px;color:#17263d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.research-page .research-student-info small{display:block;margin-top:4px;color:#64748b;font-size:10px}.research-page .mobile-grade-control{min-width:132px}.research-page .gradebook-footer{display:grid!important;grid-template-columns:1fr 1fr;gap:5px;font-size:10px}}@media(max-width:390px){.research-page .gradebook-actions{grid-template-columns:1fr}.research-page .gradebook-actions label{grid-column:auto}.research-page .research-student-card{grid-template-columns:1fr}.research-page .mobile-grade-control{width:100%}}`}</style>
    <header className="gradebook-head"><div><h1>رصد درجة البحث — {subjectLabel}</h1><p>{tenant?.teacherName||"المعلم"} — درجة البحث من {RESEARCH_MAX} درجات. تظهر قائمة الطلاب تلقائيًا، ثم اضغط حفظ الدرجات.</p></div><div className="gradebook-actions"><label>الفصل<select value={selectedClass} onChange={e=>setSelectedClass(e.target.value)}>{classes.map(name=><option key={name}>{name}</option>)}</select></label><Link href="/teacher/grades" className="research-grade-link">📊 العودة لرصد الدرجات</Link><button type="button" className="save-button" onClick={applyAll} disabled={!selectedClass}>✓ الدرجة كاملة للجميع</button><button type="button" className="save-button" onClick={save} disabled={!selectedClass||saving}>{saving?"جارٍ الحفظ...":"💾 حفظ درجات البحث"}</button><button type="button" className="delete-all-button" onClick={clearAll} disabled={!selectedClass||saving}>🗑 مسح درجات البحث</button></div></header>
    <div className="gradebook-scroll research-desktop-table"><table className="gradebook-table research-table"><thead><tr><th className="sticky-number">م</th><th className="sticky-name">اسم الطالب</th><th className="exam-head"><span>درجة البحث</span><small>من {RESEARCH_MAX}</small></th></tr></thead><tbody>{classStudents.map((student,index)=><tr key={student.id}><td className="sticky-number">{index+1}</td><td className="sticky-name"><strong>{student.name}</strong></td><td className="exam-cell"><div className="mobile-grade-control"><button type="button" className="grade-step minus" onClick={()=>adjustScore(student.id,-1)}>−</button><input className="grade-input" type="number" inputMode="numeric" min="0" max={RESEARCH_MAX} step="1" value={scores[student.id]||0} onChange={e=>updateScore(student.id,e.target.value)} onFocus={e=>e.currentTarget.select()}/><button type="button" className="grade-step plus" onClick={()=>adjustScore(student.id,1)}>+</button><button type="button" className="grade-max" onClick={()=>updateScore(student.id,String(RESEARCH_MAX))}>كامل</button></div></td></tr>)}{!students.length&&<tr><td colSpan={3} className="empty-row">لا يوجد طلاب في المادة الحالية.</td></tr>}</tbody></table></div>
    <div className="research-mobile-list">{classStudents.map((student,index)=><article className="research-student-card" key={student.id}><div className="research-student-info"><strong>{index+1}. {student.name}</strong><small>الفصل: {student.class||selectedClass||"—"}</small></div><div className="mobile-grade-control"><button type="button" className="grade-step minus" onClick={()=>adjustScore(student.id,-1)}>−</button><input className="grade-input" aria-label={`درجة بحث ${student.name||"الطالب"}`} type="number" inputMode="numeric" min="0" max={RESEARCH_MAX} step="1" value={scores[student.id]||0} onChange={e=>updateScore(student.id,e.target.value)} onFocus={e=>e.currentTarget.select()}/><button type="button" className="grade-step plus" onClick={()=>adjustScore(student.id,1)}>+</button><button type="button" className="grade-max" onClick={()=>updateScore(student.id,String(RESEARCH_MAX))}>كامل</button></div></article>)}{!students.length&&<div className="empty-row">لا يوجد طلاب في المادة الحالية.</div>}</div>
    <footer className="gradebook-footer"><span>المادة: {subjectLabel}</span><span>الدرجة القصوى: {RESEARCH_MAX}</span><span>عدد الطلاب: {classStudents.length}</span></footer>{message&&<p className="gradebook-message">{message}</p>}
  </section></div></main>;
}
