import Link from "next/link";
import type { ReactNode } from "react";
import styles from "./portal-v2.module.css";

type NavItem={href:string;label:string;icon?:string};
export function PortalShell({title,subtitle,nav=[],children}:{title:string;subtitle?:string;nav?:NavItem[];children:ReactNode}){return <div className={styles.root} dir="rtl"><aside className={styles.sidebar}><div className={styles.logoMark}>ت</div><div className={styles.logoText}><b>التهذيب</b><span>البوابة التعليمية</span></div><nav className={styles.sideNav}>{nav.map((item,i)=><Link key={`${item.href}-${item.label}`} className={i===0?styles.active:""} href={item.href}><span>{item.icon||"•"}</span>{item.label}</Link>)}</nav><div className={styles.sideFoot}>نظام مدرسي موحد<br/><small>إدارة • معلم • طالب • ولي أمر</small></div></aside><div className={styles.workspace}><header className={styles.topbar}><div><span className={styles.eyebrow}>مدرسة التهذيب الأهلية</span><strong>{title}</strong></div><div className={styles.userChip}><span className={styles.avatar}>ح</span><div><b>الأستاذ حسن علي الطويل</b><small>{subtitle||"بوابة تعليمية موحدة"}</small></div></div></header><main className={styles.main}>{children}</main></div></div>}
export function V2PageHeader({title,description,action}:{title:string;description?:string;action?:ReactNode}){return <section className={styles.pageHeader}><div><span className={styles.kicker}>لوحة التحكم</span><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action&&<div>{action}</div>}</section>}
export function V2Card({title,children}:{title?:string;children:ReactNode}){return <section className={styles.card}>{title&&<div className={styles.cardTitle}><h2>{title}</h2><span>•••</span></div>}{children}</section>}
export function V2Stat({label,value,note,icon}:{label:string;value:ReactNode;note?:string;icon?:string}){return <div className={styles.stat}><div className={styles.statIcon}>{icon||"◈"}</div><div><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div></div>}
export function V2Action({title,note,href,icon}:{title:string;note:string;href:string;icon:string}){return <Link className={styles.action} href={href}><span className={styles.actionIcon}>{icon}</span><div><b>{title}</b><small>{note}</small></div><span className={styles.arrow}>←</span></Link>}
