"use client";
import { useEffect, useMemo, useState } from "react";
import { useTeacherClient } from "../../../../lib/teacher-client";
import "../follow-up.css";
import "./referrals.css";

type Referral={id:string;studentName?:string;className?:string;referralType?:"mastery"|"achievement"|"other";referralTypeLabel?:string;reason?:string;status?:string;createdAt?:string};
export default function PreviousReferralsPage(){
 const session=useTeacherClient(); const [rows,setRows]=useState<Referral[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [filter,setFilter]=useState<"all"|"mastery"|"other">("all");
 useEffect(()=>{if(!session.subjectKey)return;let active=true;let busy=false;let controller:AbortController|null=null;const refresh=async()=>{if(!active||busy)return;busy=true;controller?.abort();controller=new AbortController();try{setLoading(true);const subjectId=String(session.subjectKey).split("--")[0];const response=await fetch(`/api/teacher/counselor-referrals?subjectId=${encodeURIComponent(subjectId)}`,{cache:"no-store",credentials:"same-origin",signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"تعذر تحميل الإحالات السابقة.");if(active)setRows(Array.isArray(data.referrals)?data.referrals:[]);}catch(error){if((error as Error)?.name!=="AbortError"&&active)setMessage(error instanceof Error?error.message:"تعذر تحميل الإحالات السابقة.");}finally{busy=false;if(active)setLoading(false);}};void refresh();window.addEventListener("online",refresh);return()=>{active=false;controller?.abort();window.removeEventListener("online",refresh);};},[session.subjectKey]);
 const shown=useMemo(()=>filter==="all"?rows:rows.filter(row=>filter==="mastery"?(row.referralType==="mastery"||row.referralType==="achievement"):row.referralType===filter),[rows,filter]); const mastery=rows.filter(row=>row.referralType==="mastery"||row.referralType==="achievement").length; const other=rows.filter(row=>row.referralType==="other").length;
 const date=(value?:string)=>{if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat("ar-SA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(parsed);};
 const printReferrals=()=>{const win=window.open("","_blank","width=1100,height=820");if(!win)return setMessage("تعذر فتح نافذة الطباعة. اسمح بالنوافذ المنبثقة ثم أعد المحاولة.");const esc=(value:unknown)=>String(value??"—").replace(/[&<>"\\\']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","\\\'":"&#039;"}[ch]||ch));const body=shown.map((row,index)=>`<tr><td>${index+1}</td><td>${esc(row.studentName)}</td><td>${esc(row.className)}</td><td>${esc(row.referralTypeLabel||(row.referralType==="other"?"إحالة أخرى":"الإتقان والتحصيل"))}</td><td>${esc(row.reason)}</td><td>${esc(row.status||"جديدة")}</td><td>${esc(date(row.createdAt))}</td></tr>`).join("");win.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>سجل الإحالات</title><style>@page{size:A4 landscape;margin:11mm}body{font-family:Arial,Tahoma,sans-serif;color:#17384a}h1{color:#0b716d;margin-bottom:4px}.meta{display:flex;gap:18px;flex-wrap:wrap;margin:12px 0;padding:10px;background:#eef7f6;border:1px solid #d5e8e5}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #cbdad8;padding:7px;text-align:right;vertical-align:top}th{background:#0b716d;color:#fff}tbody tr:nth-child(even){background:#f7faf9}</style></head><body><h1>سجل الإحالات للمرشد الطلابي</h1><p>بوابة أستاذ لحوني التعليمية</p><div class="meta"><b>المعلم: ${esc(session.teacherName||"—")}</b><b>المادة: ${esc(session.subject||"—")}</b><b>التصنيف: ${filter==="all"?"الكل":filter==="other"?"إحالات أخرى":"الإتقان والتحصيل"}</b><b>العدد: ${shown.length}</b></div><table><thead><tr><th>م</th><th>الطالب</th><th>الفصل</th><th>نوع الإحالة</th><th>السبب</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>${body||`<tr><td colspan="7">لا توجد إحالات في هذا التصنيف.</td></tr>`}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),220)<\/script></body></html>`);win.document.close();};
 return <main className="follow-page referral-history-page" dir="rtl"><section className="follow-head"><div><span>الإتقان والمتابعة</span><h1>الإحالات السابقة للمرشد الطلابي</h1><p>السجل السابق محفوظ كما هو، ويعرض إحالات الإتقان والتحصيل والإحالات الأخرى من قاعدة البوابة نفسها.</p></div><div className="follow-actions"><button type="button" className="referral-print-button" onClick={printReferrals} disabled={loading}>PDF / طباعة الجدول</button><a className="counselor-button referral-link-button" href="/teacher/follow-up">العودة إلى الإتقان</a></div></section>{message&&<p className="follow-inline-message">{message}</p>}<section className="follow-overview referral-overview"><article><span>إجمالي الإحالات</span><strong>{rows.length}</strong><small>المحفوظة لهذه المادة</small></article><article className="mastered"><span>الإتقان والتحصيل</span><strong>{mastery}</strong><small>إحالات مرتبطة بالمستوى</small></article><article className="support"><span>إحالات أخرى</span><strong>{other}</strong><small>الحالة الأخرى كما كانت سابقًا</small></article></section><section className="follow-card"><header className="referral-history-head"><div><h2>سجل الإحالات</h2><p>لا يتم إنشاء أو حذف أي إحالة عند فتح هذه الصفحة.</p></div><div className="referral-filter"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>الكل</button><button className={filter==="mastery"?"active":""} onClick={()=>setFilter("mastery")}>الإتقان</button><button className={filter==="other"?"active":""} onClick={()=>setFilter("other")}>إحالة أخرى</button></div></header><div className="follow-table-wrap"><table><thead><tr><th>الطالب</th><th>الفصل</th><th>نوع الإحالة</th><th>السبب</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{shown.map(row=><tr key={row.id}><td className="student-name-cell"><b>{row.studentName||"—"}</b></td><td>{row.className||"—"}</td><td><span className={`referral-type ${row.referralType==="other"?"other":"mastery"}`}>{row.referralTypeLabel||(row.referralType==="other"?"إحالة أخرى":"الإتقان والتحصيل")}</span></td><td className="referral-reason">{row.reason||"—"}</td><td><span className="referral-status">{row.status||"جديدة"}</span></td><td>{date(row.createdAt)}</td></tr>)}</tbody></table>{loading?<p className="empty">جارٍ تحميل الإحالات السابقة…</p>:!shown.length?<p className="empty">لا توجد إحالات محفوظة في هذا التصنيف.</p>:null}</div></section></main>;
}
