"use client";
import { useEffect, useMemo, useState } from "react";
import { useTeacherClient } from "../../../../lib/teacher-client";
import "../follow-up.css";

type Referral={id:string;studentName?:string;className?:string;referralType?:"mastery"|"other";referralTypeLabel?:string;reason?:string;status?:string;createdAt?:string};
export default function PreviousReferralsPage(){
 const session=useTeacherClient(); const [rows,setRows]=useState<Referral[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [filter,setFilter]=useState<"all"|"mastery"|"other">("all");
 useEffect(()=>{if(!session.subjectKey)return;let active=true;let busy=false;let controller:AbortController|null=null;const refresh=async()=>{if(!active||busy)return;busy=true;controller?.abort();controller=new AbortController();try{setLoading(true);const subjectId=String(session.subjectKey).split("--")[0];const response=await fetch(`/api/teacher/counselor-referrals?subjectId=${encodeURIComponent(subjectId)}`,{cache:"no-store",credentials:"same-origin",signal:controller.signal});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"تعذر تحميل الإحالات السابقة.");if(active)setRows(Array.isArray(data.referrals)?data.referrals:[]);}catch(error){if((error as Error)?.name!=="AbortError"&&active)setMessage(error instanceof Error?error.message:"تعذر تحميل الإحالات السابقة.");}finally{busy=false;if(active)setLoading(false);}};const visible=()=>{if(document.visibilityState==="visible")void refresh();};void refresh();window.addEventListener("focus",refresh);window.addEventListener("online",refresh);document.addEventListener("visibilitychange",visible);return()=>{active=false;controller?.abort();window.removeEventListener("focus",refresh);window.removeEventListener("online",refresh);document.removeEventListener("visibilitychange",visible);};},[session.subjectKey]);
 const shown=useMemo(()=>filter==="all"?rows:rows.filter(row=>row.referralType===filter),[rows,filter]); const mastery=rows.filter(row=>row.referralType==="mastery").length; const other=rows.filter(row=>row.referralType==="other").length;
 const date=(value?:string)=>{if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat("ar-SA",{timeZone:"Asia/Riyadh",year:"numeric",month:"2-digit",day:"2-digit"}).format(parsed);};
 return <main className="follow-page referral-history-page" dir="rtl"><section className="follow-head"><div><span>الإتقان والمتابعة</span><h1>الإحالات السابقة للمرشد الطلابي</h1><p>السجل السابق محفوظ كما هو، ويعرض إحالات الإتقان والتحصيل والإحالات الأخرى من قاعدة البوابة نفسها.</p></div><div className="follow-actions"><a className="counselor-button referral-link-button" href="/teacher/follow-up">العودة إلى الإتقان</a></div></section>{message&&<p className="follow-inline-message">{message}</p>}<section className="follow-overview referral-overview"><article><span>إجمالي الإحالات</span><strong>{rows.length}</strong><small>المحفوظة لهذه المادة</small></article><article className="mastered"><span>الإتقان والتحصيل</span><strong>{mastery}</strong><small>إحالات مرتبطة بالمستوى</small></article><article className="support"><span>إحالات أخرى</span><strong>{other}</strong><small>الحالة الأخرى كما كانت سابقًا</small></article></section><section className="follow-card"><header className="referral-history-head"><div><h2>سجل الإحالات</h2><p>لا يتم إنشاء أو حذف أي إحالة عند فتح هذه الصفحة.</p></div><div className="referral-filter"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>الكل</button><button className={filter==="mastery"?"active":""} onClick={()=>setFilter("mastery")}>الإتقان</button><button className={filter==="other"?"active":""} onClick={()=>setFilter("other")}>إحالة أخرى</button></div></header><div className="follow-table-wrap"><table><thead><tr><th>الطالب</th><th>الفصل</th><th>نوع الإحالة</th><th>السبب</th><th>الحالة</th><th>التاريخ</th></tr></thead><tbody>{shown.map(row=><tr key={row.id}><td className="student-name-cell"><b>{row.studentName||"—"}</b></td><td>{row.className||"—"}</td><td><span className={`referral-type ${row.referralType||"mastery"}`}>{row.referralTypeLabel||(row.referralType==="other"?"إحالة أخرى":"الإتقان والتحصيل")}</span></td><td className="referral-reason">{row.reason||"—"}</td><td><span className="referral-status">{row.status||"جديدة"}</span></td><td>{date(row.createdAt)}</td></tr>)}</tbody></table>{loading?<p className="empty">جارٍ تحميل الإحالات السابقة…</p>:!shown.length?<p className="empty">لا توجد إحالات محفوظة في هذا التصنيف.</p>:null}</div></section></main>;
}
