"use client";
import { useEffect, useMemo, useState } from "react";
import { collection, doc, onSnapshot, setDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import { useTeacherClient } from "../../../lib/teacher-client";
import { ACADEMIC_UNITS, RESEARCH_MAX, UNIT_MAX } from "../../../lib/academic-config";
import { tenantCollection } from "../../../lib/teacher-tenant";
import "./teacher-ai.css";

type UnitRecord = { attendance?: number; participation?: number; homework?: number; unitExam?: number; exam1?: number; exam2?: number; total?: number };
type Student = { id: string; name?: string; nationalId?: string; class?: string; research?: number; researchScore?: number; units?: Record<string, UnitRecord> };
type Analyzed = Student & { percentage: number; weakest: string; action: string };
function analyze(student: Student): Analyzed { let total = 0, recorded = 0; const components = { "الحضور والانضباط": 0, "المشاركة الصفية": 0, "الواجبات والتطبيق": 0, "فهم المفاهيم والاختبارات": 0 }; ACADEMIC_UNITS.forEach(unit => { const value = student.units?.[unit.key]; if (!value) return; recorded++; total += Math.min(UNIT_MAX, Number(value.total ?? (Number(value.attendance || 0) + Number(value.participation || 0) + Number(value.homework || 0) + Number(value.unitExam ?? value.exam1 ?? value.exam2 ?? 0)))); components["الحضور والانضباط"] += Number(value.attendance || 0); components["المشاركة الصفية"] += Number(value.participation || 0); components["الواجبات والتطبيق"] += Number(value.homework || 0); components["فهم المفاهيم والاختبارات"] += Number(value.unitExam ?? value.exam1 ?? value.exam2 ?? 0); }); total += Math.min(RESEARCH_MAX, Number(student.researchScore ?? student.research ?? 0)); const maximum = recorded * UNIT_MAX + RESEARCH_MAX; const percentage = maximum ? Math.round(total / maximum * 100) : 0; const weakest = Object.entries(components).sort((a, b) => a[1] - b[1])[0]?.[0] || "المهارات الأساسية"; const actions: Record<string, string> = { "الحضور والانضباط": "متابعة الحضور يوميًا وتعزيز الالتزام بمهمة قصيرة في بداية الحصة.", "المشاركة الصفية": "إشراك الطلاب في سؤال تمهيدي ونشاط ثنائي مع تغذية راجعة مباشرة.", "الواجبات والتطبيق": "تدريبات قصيرة متدرجة مع تصحيح فوري وإعادة المحاولة.", "فهم المفاهيم والاختبارات": "شرح مصغر للمفاهيم غير المتقنة ثم تقويم قصير متدرج." }; return { ...student, percentage, weakest, action: actions[weakest] || "تدريب موجه ثم تقويم بعدي." }; }

export default function TeacherAiPage() {
  const session = useTeacherClient(), teacherId = session.teacherId || "", teacherName = session.teacherName || "المعلم", subjectKey = session.subjectKey || "history", subject = session.subject || "المادة";
  const [students, setStudents] = useState<Student[]>([]), [scope, setScope] = useState<"threshold" | "class" | "manual">("threshold"), [selectedClass, setSelectedClass] = useState(""), [threshold, setThreshold] = useState(60), [selectedIds, setSelectedIds] = useState<string[]>([]), [duration, setDuration] = useState("٤ أسابيع"), [message, setMessage] = useState("");
  const studentsPath = useMemo(() => teacherId ? tenantCollection(teacherId, subjectKey as never, "students") : "", [teacherId, subjectKey]);
  const plansPath = useMemo(() => teacherId ? tenantCollection(teacherId, subjectKey as never, "treatmentPlans") : "", [teacherId, subjectKey]);
  useEffect(() => { if (!studentsPath) return; return onSnapshot(collection(db, studentsPath), snapshot => setStudents(snapshot.docs.map(item => ({ id: item.id, ...item.data() } as Student)).sort((a, b) => (a.name || "").localeCompare(b.name || "", "ar")))); }, [studentsPath]);
  const analyzed = useMemo(() => students.map(analyze), [students]);
  const classes = useMemo(() => Array.from(new Set(students.map(student => student.class).filter(Boolean) as string[])).sort((a, b) => a.localeCompare(b, "ar")), [students]);
  const candidates = useMemo(() => scope === "threshold" ? analyzed.filter(student => student.percentage < threshold) : scope === "class" ? analyzed.filter(student => !selectedClass || student.class === selectedClass) : analyzed.filter(student => selectedIds.includes(student.id)), [analyzed, scope, threshold, selectedClass, selectedIds]);
  const average = candidates.length ? Math.round(candidates.reduce((sum, student) => sum + student.percentage, 0) / candidates.length) : 0;
  const weakSkills = useMemo(() => Object.entries(candidates.reduce<Record<string, number>>((result, student) => ({ ...result, [student.weakest]: (result[student.weakest] || 0) + 1 }), {})).sort((a, b) => b[1] - a[1]), [candidates]);
  async function savePlan() { if (!candidates.length) return setMessage("لا يوجد طلاب مطابقون للاختيار الحالي."); const id = crypto.randomUUID(); await setDoc(doc(db, plansPath, id), { title: `الخطة العلاجية لمادة ${subject}`, teacherName, subject, subjectKey, duration, threshold: scope === "threshold" ? threshold : null, scope, className: scope === "class" ? selectedClass : "", students: candidates.map(student => ({ id: student.id, name: student.name || "", className: student.class || "", percentage: student.percentage, weakest: student.weakest })), objectives: weakSkills.map(([skill]) => `رفع إتقان ${skill}`), createdAt: new Date().toISOString() }); setMessage("تم حفظ الخطة العلاجية في بوابة المعلم."); }

  return <main className="teacher-ai-page" dir="rtl"><section className="teacher-ai-hero no-print"><div><span>المساعد التعليمي الذكي</span><h1>إنشاء خطة علاجية من درجات الطلاب</h1><p>حدد الطلاب بالطريقة المناسبة، ثم راجع الخطة واحفظها أو اطبعها PDF.</p></div><div className="teacher-ai-status"><b>{subject}</b><small>المعلم: {teacherName}</small></div></section>
    <section className="plan-builder no-print"><header><div><small>١</small><h2>حدد نطاق الخطة</h2></div></header><div className="scope-buttons"><button className={scope === "threshold" ? "active" : ""} onClick={() => setScope("threshold")}>حسب الدرجة</button><button className={scope === "class" ? "active" : ""} onClick={() => setScope("class")}>فصل كامل</button><button className={scope === "manual" ? "active" : ""} onClick={() => setScope("manual")}>طلاب محددون</button></div>{scope === "threshold" && <label className="threshold-field">اختر كل طالب درجته أقل من <span><input type="number" min="1" max="100" value={threshold} onChange={event => setThreshold(Number(event.target.value))} /><b>٪</b></span></label>}{scope === "class" && <label>الفصل<select value={selectedClass} onChange={event => setSelectedClass(event.target.value)}><option value="">جميع الفصول</option>{classes.map(name => <option key={name}>{name}</option>)}</select></label>}{scope === "manual" && <div className="manual-students"><div><button onClick={() => setSelectedIds(analyzed.map(student => student.id))}>تحديد الكل</button><button onClick={() => setSelectedIds([])}>إلغاء التحديد</button></div>{analyzed.map(student => <label key={student.id}><input type="checkbox" checked={selectedIds.includes(student.id)} onChange={event => setSelectedIds(current => event.target.checked ? [...new Set([...current, student.id])] : current.filter(id => id !== student.id))} /><span><b>{student.name || "—"}</b><small>{student.class || "—"} • {student.percentage}%</small></span></label>)}</div>}<label>مدة الخطة<select value={duration} onChange={event => setDuration(event.target.value)}><option>أسبوعان</option><option>٣ أسابيع</option><option>٤ أسابيع</option><option>٦ أسابيع</option></select></label></section>
    <section className="plan-selection no-print"><article><small>الطلاب المختارون</small><strong>{candidates.length}</strong></article><article><small>متوسطهم الحالي</small><strong>{average}%</strong></article><article><small>أكثر مهارة تحتاج دعمًا</small><strong>{weakSkills[0]?.[0] || "—"}</strong></article></section>
    <section className="generated-plan"><header><div><span>الخطة العلاجية المقترحة</span><h2>خطة علاجية لمادة {subject}</h2><p>إعداد المعلم: {teacherName} • المدة: {duration}</p></div><div className="plan-actions no-print"><button onClick={savePlan}>حفظ الخطة</button><button onClick={() => window.print()}>طباعة / PDF</button></div></header><div className="plan-meta"><article><b>الفئة المستهدفة</b><p>{candidates.length} طالبًا {scope === "threshold" ? `درجاتهم أقل من ${threshold}%` : scope === "class" ? `من ${selectedClass || "جميع الفصول"}` : "تم تحديدهم يدويًا"}.</p></article><article><b>الهدف العام</b><p>رفع مستوى إتقان الطلاب في مادة {subject} وقياس التحسن بعد تنفيذ التدخلات.</p></article></div><div className="plan-steps"><h3>إجراءات التنفيذ</h3>{weakSkills.slice(0, 4).map(([skill, count], index) => <article key={skill}><em>{index + 1}</em><div><b>{skill}</b><small>{count} طالب يحتاجون دعمًا في هذا المحور</small><p>{candidates.find(student => student.weakest === skill)?.action}</p></div></article>)}{!weakSkills.length && <p>اختر طلابًا ليتم بناء الخطة من درجاتهم.</p>}</div><div className="plan-schedule"><h3>الجدول الزمني وقياس الأثر</h3><span><b>الأسبوع الأول</b> تشخيص المهارات وتحديد نقطة البداية.</span><span><b>منتصف الخطة</b> تدريب موجه ومتابعة قصيرة لكل مجموعة.</span><span><b>نهاية الخطة</b> تقويم بعدي ومقارنة النتيجة بالنسبة الحالية {average}%.</span></div><div className="plan-students"><h3>الطلاب المشمولون بالخطة</h3><div>{candidates.map(student => <span key={student.id}><b>{student.name || "—"}</b><small>{student.class || "—"} • {student.percentage}% • {student.weakest}</small></span>)}</div></div></section>{message && <p className="ai-message no-print" role="status">{message}</p>}</main>;
}
